### ISSUE TITLE
Als PO wil dat wijziging van waarden in een waardentabel voor enumeratievelden tot nieuwe API versie leidt

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1007]
zodat ik weet welke mogelijke waarden er zijn en daar mijn code op kan aanpassen

Wijziging van Waardetabel waarden voor enumeratievelden moet leiden tot nieuwe versie API

Er moet proces worden beschreven en ingevoerd voor wijziging van waarden in een Waardetabel

Voor landelijke tabellen is er hiervoor een proces, dat door BZK wordt uitgevoerd.

Voor tabellen voor velden die in LO GBA beschreven staan als vast lijst van "Mogelijke waarden" (in v1.3 van de API was dit een enumeratie) moet gelden:
- bij toevoegen van een nieuwe code of vervallen van een bestaande code wordt een nieuwe minor versie van de BRP API gemaakt
- de toegevoegde tabelwaarde wordt beschreven in de release notes van die versie
- bestaande tabelwaarden worden niet verwijderd, maar kunnen wel een einddatum krijgen
- van bestaande tabelwaarden mag de code niet worden gewijzigd
- van een bestaande tabelwaarde mag alleen de omschrijving worden gewijzigd, wanneer hiermee de betekenis van de code niet wijzigt

**Comment by melsk-r** [comment]
> * bij toevoegen van een nieuwe code of vervallen van een bestaande code wordt een nieuwe minor versie van de BRP API gemaakt

Als ik het goed begrijp zou het dus voor kunnen komen dat er een nieuwe minor versie van de Haal Centraal BRP Personen Bevragen API wordt gepubliceerd omdat er in een van de gerelateerde tabellen iets is gewijzigd terwijl er in deze API niets is gewijzigd. Klopt dat?

> * bestaande tabelwaarden worden niet verwijderd, maar kunnen wel een einddatum krijgen

Ik neem aan dat ook dit wordt beschreven in de release notes van die versie.

**Comment by fsamwel** [comment]
> Als ik het goed begrijp zou het dus voor kunnen komen dat er een nieuwe minor versie van de Haal Centraal BRP Personen Bevragen API wordt gepubliceerd omdat er in een van de gerelateerde tabellen iets is gewijzigd terwijl er in deze API niets is gewijzigd. Klopt dat?

Dat is wel wat gebruikers hebben gevraagd

**Comment by fsamwel** [comment]
> > bestaande tabelwaarden worden niet verwijderd, maar kunnen wel een einddatum krijgen
>
> Ik neem aan dat ook dit wordt beschreven in de release notes van die versie.

dat lijkt mij dan ook de bedoeling
