### ISSUE TITLE
Zoek met ... en Raadpleeg met burgerservicenummer hebben verschillende field mappings voor zelfde velden

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1022]
voorbeeld: geboorte.datum.datum en geboorte.datum.type hebben respectievelijk een datum.datum en datum.type mapping voor PersoonBeperkt (Zoek met ...), maar bij Persoon (Raadpleeg met bsn) komt deze mappings niet voor.
Is dit niet verwarrend voor consumers? Een consumer zou namelijk niet alleen extra fields moeten toevoegen, maar mogelijk ook fields vervangen als hij na het zoeken specifieke personen wil raadplegen.

**Comment by CathyDingemanse** [comment]
Dat lijkt mij buitengewoon onhandig, te meer omdat het raadplegen na het zoeken de meest voorkomende vervolgactie is. Hoe kunnen we dit gelijk trekken?

**Comment by fsamwel** [comment]
volgens mij is de situatie dat:
1. er een consistente logica achter zit die gelijk werkt voor Persoon en PersoonBeperkt, met verschillende uitkomst
2. voor PersoonBeperkt soms kortere fields paden toegestaan zijn dan voor Persoon, maar de langere paden van Persoon werken altijd ook voor PersoonBeperkt
3. de mapping beschrijft wat een gebruiker mag invullen in fields, niet wat moet worden gebruikt
4. er nu steeds zoveel mogelijk wordt toegestaan, dus geen foutmelding wordt gegeven tenzij de vraag niet geïnterpreteerd kan worden
5. deze mappigs bedoeld zijn voor de provider. voor de consumer moeten we een andere lijst maken waar dit niet in voorkomt. Zie #1010.
