### ISSUE TITLE
GbaAangaanHuwelijkPartner heeft een inOnderzoek property. Is dit correct?

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1040]
Volgens mij zou de proxy dit moeten betalen uit de partner inOnderzoek property

**Comment by fsamwel** [comment]
inderdaad. GbaAangaanHuwelijkPartner heeft GEEN inOnderzoek property nodig

**Comment by melsk-r** [comment]
Volgens mij is dit inmiddels verwerkt in de specificaties en kan dit issue worden gesloten.
