### ISSUE TITLE
Uitwerken fields feature voor rule inOnderzoek

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1044]
In de fields feature staat nog een regel die moet worden uitgebreid:

```
  Rule: Wanneer een gevraagd veld in onderzoek is, dan wordt het corresponderende in onderzoek veld altijd terug gegeven
    # Scenario's worden toegevoegd als in onderzoek feature is geïmplementeerd

```

**Comment by MelvLee** [comment]
Vraag
- hele categorie/naam groep van een persoon staat in onderzoek. In de registratie heeft de persoon geen voorvoegsel en geen adellijke titel of predicaat. Met fields=naam wordt alle naam gegevens gevraagd. Zijn naam.inOnderzoek.voorvoegsel en naam.inOnderzoek.adellijkeTitelPredicaat wel of niet true? In de eerste instantie dacht ik niet omdat voorvoegsel en adellijkeTitelPredicaat geen waarde hebben. Maar hoe geef je dan aan dat het niet hebben van een waarde in onderzoek staat?
