### ISSUE TITLE
Er ontbreken specificaties voor het bepalen van de eerste partner en laatste ontbonden partner

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1048]
Er is niet beschreven hoe dit moet worden gedaan bij onvolledige datum aangaan en datum ontbinding huwelijk/geregistreerd partnerschap

Zoals nu is geïmplementeerd voor het bepalen van aanhef wordt gekeken naar de velden die beschikbaar zijn. Voorbeeld als een partner een VolledigDatum heeft en een andere partner heeft een JaarDatum dan wordt alleen jaar gebruikt om te bepalen wie een eerdere/latere partner is.
Partners met DatumOnbekend worden niet meegenomen in de bepaling. Is dit correct?

**Comment by fsamwel** [comment]
ik zou het simpel houden. Sorteer op de GBA-datum (als string), zodat je bijvoorbeeld deze volgorde krijgt:

```
1. 19940708
2. 19940700
3. 19940416
4. 19940000
5. 19870715
6. 00000000
```
