### ISSUE TITLE
Testen proxy

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1057]

**Comment by melsk-r** [comment]
Het tabblad 'Namen' in het spreadsheet [Testen proxy juni 2022.xlsx](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/files/8850900/Testen.proxy.juni.2022.xlsx) bevat de resultaten van testen op het genereren van 'aanhef', 'aanschrijfwijze' en 'gebruikInLopendeTekst'.

**Comment by fsamwel** [comment]
@melsk-r volgens mij zijn 'aanhef', 'aanschrijfwijze' en 'gebruikInLopendeTekst' nog niet volledig ontwikkeld ik de huidige versie van de proxy. Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/docs/features/test-report.html. Niet zo gek dus wanneer je daarin dingen niet krijgt zoals je verwacht
