### ISSUE TITLE
scenario's toevoegen aan tabelwaarden feature

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1083]
de scenario's die er nu inzitten zijn niet voldoende om te testen dan van een in GBA-V opgeslagen code de code-omschrijving combinatie wordt geleverd

**Comment by JohanBoer** [comment]
Ik weet niet zo goed wat nu de stand van zaken is. de tabelwaarden.feature  is niet meer terug te vinden in de develop branch. M.i. zouden deze feature thuis horen in de repo voor de waardetabellen API. Wie weet meer ?
