### ISSUE TITLE
leeftijd op verjaardag niet correct berekend

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1099]
Vandaag, 28 mei krijg ik:
- iemand die gisteren jarig was:
```
            "leeftijd": 15,
            "geboorte": {
                "datum": {
                    "type": "Datum",
                    "datum": "2007-05-27",
                    "langFormaat": "27 mei 2007"
                }
            }
```
iemand die vandaag jarig is:
```
            "leeftijd": 14,
            "geboorte": {
                "datum": {
                    "type": "Datum",
                    "datum": "2007-05-28",
                    "langFormaat": "28 mei 2007"
                }
            }
```

iemand die morgen jarig is:
 ```
           "leeftijd": 14,
            "geboorte": {
                "datum": {
                    "type": "Datum",
                    "datum": "2007-05-29",
                    "langFormaat": "29 mei 2007"
                }
            }
```

Ik verwacht dat iemand die vandaag jarig is, ook vandaag een jaar ouder is geworden. Dus iemand die op 28 mei 2007 is geboren is vandaag 15 geworden. Leeftijd geeft voor deze persoon nu de leeftijd 14.

**Comment by MelvLee** [comment]
Volgens mij loopt de tijd in de docker container niet synchroon met de host. Je kan dit testen door een command prompt op te starten voor de container en dan de time statement uitvoeren.
Op een Windows host kan dit worden gereproduceerd door de host in Sleep mode te brengen en dan een uur later te ontwaken. Dan loopt de tijd in de container een uur achter. De enige oplossing die ik heb kunnen vinden is gewoon de host restarten.
