### ISSUE TITLE
Waarom is het scenario 'De ouder heeft geslachtswijziging ondergaan, maar de gevraagde persoon erkent dit niet' van belang?

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1112]
In 'ouders.feature' is het scenario: **'De ouder heeft geslachtswijziging ondergaan, maar de gevraagde persoon erkent dit niet'** uitgewerkt.
Ik vraag me echter af waarom het van belang is om dit scenario zo uit te werken. In de persoonslijst van de persoon die uitgevraagd wordt zijn immers de gevolgen van het niet erkennen van de geslachtswijziging al verwerkt. Of zie ik dat verkeerd?

Ik ga er dus vanuit dat hier de rule geldt:

> Bij het raadplegen van een persoon worden alleen gegevens uit de persoonslijst van de gevraagde persoon gebruikt, en nooit gegevens van de persoonslijst van de ouder

Als dat inderdaad het geval is dan worden toch automatisch de juiste gegevens verstrekt. Volgens mij is er dus geen verschil tussen dit scenario en het scenario waarbij de gegevens van een ouder worden opgevraagd die geen geslachtswijziging heeft ondergaan.

**Comment by fsamwel** [comment]
ja, als je al begrijpt hoe het werkt is een voorbeeld om te illustreren hoe het werkt niet meer van belang. Het scenario illustreert dit voor mensen die het nog niet helemaal begrijpen.
