### ISSUE TITLE
Naamsamenstelling features niet correct voor vrouw met predicaat en partner

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1154]
De aanschrijfwijze feature gaat voor aanschrijfwijze.naam anders om met een gehuwde vrouw met predicaat dan in aanschrijfwijze.aanspreekvorm, gebruikInLopendeTekst en aanhef.

Wanneer een vrouw met predicaat een partner heeft, of de naam van de ex-partner gebruikt, mag ze haar predicaat niet meer gebruiken. 

Bijvoorbeeld krijg je volgens de huidige features bij naamgebruik V (partnernaam voor eigen naam):
```
    "naam.volledigeNaam": "jonkvrouw Anna voor den Eigennaam",
    "adressering.aanhef": "Geachte mevrouw De Partnernaam-voor den Eigennaam",
    "adressering.aanschrijfwijze.aanspreekvorm": null,
    "adressering.aanschrijfwijze.naam": "A. de Partnernaam-jonkvrouw voor de Eigennaam",
    "adressering.gebruikInLopendeTekst": "mevrouw De Partnernaam-voor de Eigennaam"
```

Op de site van de [Hoge Raad van de Adel](https://www.hogeraadvanadel.nl/adel/adellijke-titulatuur/richtlijnen-gebruik-adellijke-titulatuur) staat nu een andere logica beschreven dan we nu in de features hebben (is denk ik nieuw):
> Heeft zij een adellijk predicaat en voert zij tevens de naam van haar man, dan wordt het predicaat niet vermeld

Dan zou denk ik voor alle samengestelde namen, behalve volledigeNaam, hetzelfde moeten gelden:
> Het predicaat wordt niet gebruikt wanneer geslacht=="V" en aanduidingNaamgebruik≠"E".

**Comment by CathyDingemanse** [comment]
Ik kan geen andere mogelijke interpretatie verzinnen. Eens.
