### ISSUE TITLE
Gba versie van reisdocumenten API maken

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1157]
De reisdocumenten API bevat gegevens die bewerkt zijn. Hiervan moet dus een "GBA" versie gemaakt worden.

Ook staan er nog enumeraties in. Houden we dat zo?

De "normale" versie moet ook worden aangepast, want daarin zit nog een json hal link naar ingeschreven personen. In plaats daarvan moet denk ik het burgerservicenummer worden toegevoegd.

Moeten we niet ook de fields parameter toevoegen aan de reisdocumenten API?

**Comment by CathyDingemanse** [comment]
> De reisdocumenten API bevat gegevens die bewerkt zijn. Hiervan moet dus een "GBA" versie gemaakt worden.
> 
> Ook staan er nog enumeraties in. Houden we dat zo?

Liever niet
> 
> De "normale" versie moet ook worden aangepast, want daarin zit nog een json hal link naar ingeschreven personen. In plaats daarvan moet denk ik het burgerservicenummer worden toegevoegd.

Ja, en moet ook bekeken worden of geheimhouding nog onderdeel is van de API.
> 
> Moeten we niet ook de fields parameter toevoegen aan de reisdocumenten API?
Ik denk het niet, omdat alle informatie essentieel is. Kan altijd later nog worden toegevoegd wanneer meer kennis over het gebruik is opgebouwd.
