### ISSUE TITLE
Wat wordt er bedoeld/verwacht bij onbekend_waardes.feature scenario op regel 550?

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1170]
Daar wordt aangegeven dat datum en land geen waarde/lege waarde hebben.

Als dit betekent dat de persoon geen immigratie heeft, dan moet de response in dit geval een leeg persoon object zijn.
Of  heeft de persoon wel immigratie, maar hebben de twee velden geen waarde ,dan moet in dit geval de response een persoon met een leeg immigratie object zijn.
Of is er nog een derde mogelijkheid?

**Comment by fsamwel** [comment]
Ik denk dat als datum en land immigratie leeg zijn, er geen immigratie is. Dus leeg persoon object. Het scenario klopt dan niet.
