### ISSUE TITLE
Bijwerken features voor v2.0

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1186]
| feature | component | status |
|--- |--- |--- |
| aanhef | P | klaar |
| aanschrijfwijze | P | #1154, #1054|
| adres | P|klaar |
| datum |P |klaar |
| fields | G+P| klaar|
| fields-fout-cases | G+P|klaar |
| gebruik_in_lopende_tekst |P|klaar |
| immigratie | P|klaar |
| in_onderzoek | G+P| in onderzoek.xlsx bijwerken #1055; herstructurering verblijfplaats #1045 >> #1183|
| informatievragen-fields | G |klaar |
| kiesrecht | G| klaar|
| kinderen | G+P| leveren leeg object: #1187|
| leeftijd_bepaling |P |klaar |
| lege-waarden | G+P| gba scenario's ontbreken: #1187  |
| nationaliteit | G+P|klaar |
| onbekend_waardes | P|klaar |
| ouders | G+P| leveren leeg object: #1187 |
| partners |G+P |leveren leeg object: #1187 |
| verblijfplaats | P|klaar |
| verblijfstitel |G |klaar; #1200 >> PR #1215 |
| volledigeNaam | P| leveren leeg object: #1187|
| voorletters | P|leveren leeg object: #1187 |
| waardetabel | G| toevoegen rule/scenario's voor tabellen van op LO mogelijke waarden|
| zoek-met-bsn |G+P | toevoegen scenario raadplegen overleden persoon en met gemeenteVanInschrijving: #1188 |
| zoek-met-geslachtsnaam-geboortedatum | G+P | #1188; rule wildcard niet correct voor voornamen|
| zoek-met-geslachtsnaam-voornamen-gemeentevaninschrijving |G+P  | #1188|
| zoek-met-nummeraanduiding-identificatie | G+P | #1188 |
| zoek-met-postcode-huisnummer |G+P  | #1188|
| zoek-met-straat-huisnummer-gemeentevaninschrijving |G+P  | #1188|
| zoek | G+P | klaar|

# Historie
| feature | component | status |
|--- |--- |--- |
| partnerhistorie | P + G |pull request |
| nationaliteithistorie | P + G | bestaat nog niet|
| verblijfplaatshistorie | P + G | pull request|
| verblijfstitelhistorie | P + G | pull request|

# Reisdocumenten
| feature | component | status |
|--- |--- |--- |
| reisdocumenten op reisdocumentnummer | P | pull request |
| reisdocumenten op burgerservicenummer | G+P | bestaat nog niet |

# Bewoning
| feature | component | status |
|--- |--- |--- |
| bewoning in periode | G+P | pull request |
| bewoning op peildatum | G+P | bestaat nog niet |
| medebewoners in periode | G+P | bestaat nog niet|
| medebewoners op peildatum | G+P |bestaat nog niet |

**Comment by KayodeBakker** [comment]
@CathyDingemanse  @fsamwel  @MelvLee  @melsk-r 

Status update:
GBA BRP API geïmplementeerd. Features alle geïmplementeerd waar klaar stond met resterende vragen/opmerkingen.

| feature | Opmerkingen
|--- |--- |
| fields | |
| fields-fout-cases | Bespreken. Voorbeelden als een paramCombination errorcode te geven bij het ontbreken van fields is apart. |
| in_onderzoek | |
| informatievragen-fields | |
| kiesrecht | |
| kinderen | |
| lege-waarden | |
| nationaliteit | Bespreken casus  Scenario: de persoon is vastgesteld niet-Nederlander want meerdere nationaliteiten en logica voor eerste datum |
| ouders | |
| partners | |
| verblijfstitel | Vraag over scenario of dit geldt voor GBA  Rule: een verblijfstitel met aanduiding 98 "geen verblijfstitel (meer)" wordt niet opgenomen|
| waardetabel | |
| zoek-met-bsn | |
| zoek-met-geslachtsnaam-geboortedatum | |
| zoek-met-geslachtsnaam-voornamen-gemeentevaninschrijving | |
| zoek-met-nummeraanduiding-identificatie | |
| zoek-met-postcode-huisnummer | |
| zoek-met-straat-huisnummer-gemeentevaninschrijvin | |
| zoek | Bespreken keuzes |

GBA BRP historie API geïmplementeerd. Nog geen features aanpakt maar er zijn veel resterende vragen.
-  Hoe willen we geheimhoudingPersoonsgegevens laten werken?
  - We kunnen zoeken op meerdere bsn's en de geheimhoudingPersoonsgegevens is afkomstig van de PL in de GBA en niet van de verblijfplaats/nationaliteit etc. Dus 1 boolean voor n bsns is niet logisch.
- We kunnen elke historie type opvragen d.m.v. van meerdere bsns + datum velden.
  - Hoe weet je welke verblijfplaats/nationaliteit etc. bij welke bsn hoort?
- Bij de BRP 2.0.0 is ervoor gekozen om alle zoekpaden onder 1 endpoint te plaatsen '/personen'. Deze bevat meerdere request body types en meerdere response object types.
  - Waarom kiezen we er dan voor om bij BRP historie wel 4 aparte endpoints te creëren terwijl dezelfde request body modellen worden gebruikt en alleen de response objecten anders zijn.
- Wat zal de einddatum zijn bij verblijfplaatsen?
  - Antwoord al gegeven door Cathy. De einddatum is de begin datum van de volgende.
- Dit kan wellicht aan de testdata liggen van de RvIG, maar de datum aanvang bij de verblijfplaatsen is nooit gevuld.
- **Nationalisatie**historieQueryResponse ipv **Nationaliteit**historieQueryResponse?
- BRP 2.0.0 heeft bij GbaOntbindingHuwelijkPartnerschap alleen een datum waar bij historie de gelijknamige object meer heeft. Waarom dit verschil?
  - Waarom überhaupt niet een common definieren?
 

Begonnen aan GBA Bewoning API.

Nog niet begonnen aan GBA Reisdocumenten API.

**Comment by JohanBoer** [comment]
Hoe willen we geheimhoudingPersoonsgegevens laten werken?

- De actuele geheimhouding bepaalt in hoeverre persoonsgegevens en historische persoongegevens worden verstrekt. 

We kunnen zoeken op meerdere bsn's en de geheimhoudingPersoonsgegevens is afkomstig van de PL in de GBA en niet van de verblijfplaats/nationaliteit etc. Dus 1 boolean voor n bsns is niet logisch.

- In historie kunnen we niet zoeken op meerdere BSN's. 

We kunnen elke historie type opvragen d.m.v. van meerdere bsns + datum velden.

- Wat bedoel jet met Types ( de endpoints ?)  Ieder endpoint kan maar met 1 BSN tegelijk bevraagd worden. 

Hoe weet je welke verblijfplaats/nationaliteit etc. bij welke bsn hoort?

- Wederom, dit endpoint wordt maar met 1 BSN tegelijk bevraagd. 

Bij de BRP 2.0.0 is ervoor gekozen om alle zoekpaden onder 1 endpoint te plaatsen '/personen'. Deze bevat meerdere request body types en meerdere response object types.

- De functionaliteit om deze historische gegevens met elkaar in combinatie te bevragen is niet uit de user stories gebleken. We hebben dus geen trigger gehad om de initiële opzet aan te passen. 

Waarom kiezen we er dan voor om bij BRP historie wel 4 aparte endpoints te creëren terwijl dezelfde request body modellen worden gebruikt en alleen de response objecten anders zijn.

- Zie boven.

Wat zal de einddatum zijn bij verblijfplaatsen?
Antwoord al gegeven door Cathy. De einddatum is de begin datum van de volgende.

Dit kan wellicht aan de testdata liggen van de RvIG, maar de datum aanvang bij de verblijfplaatsen is nooit gevuld.

-  Dit moeten we checken. Naar welke datum kijk je nu in de database ? Mogelijk wordt hier een andere property voor gebruikt. 

NationalisatiehistorieQueryResponse ipv NationaliteithistorieQueryResponse?

- Moet aangepast worden (Johan)

BRP 2.0.0 heeft bij GbaOntbindingHuwelijkPartnerschap alleen een datum waar bij historie de gelijknamige object meer heeft. 
Waarom dit verschil?

- Bij Personen bevragen heb je minder gegevens nodig omdat het niet zozeer om de partnergegevens gaat, maar om het laatste ontbonden partnerschap. 

Waarom überhaupt niet een common definieren?

- Omdat de gegevens-behoefte bij Personen bevragen veel kleiner is.

**Comment by fsamwel** [comment]
> Hoe willen we geheimhoudingPersoonsgegevens laten werken?

> De actuele geheimhouding bepaalt in hoeverre persoonsgegevens en historische persoongegevens worden verstrekt.
> We kunnen zoeken op meerdere bsn's en de geheimhoudingPersoonsgegevens is afkomstig van de PL in de GBA en niet van de verblijfplaats/nationaliteit etc. Dus 1 boolean voor n bsns is niet logisch.

Dit gaat toch over historie? Hoe kan die gaan over meer dan 1 bsn?

**Comment by fsamwel** [comment]
> Dit kan wellicht aan de testdata liggen van de RvIG, maar de datum aanvang bij de verblijfplaatsen is nooit gevuld.

In de proefomgeving heeft een verblijfplaats altijd een datum aanvang.

**Comment by KayodeBakker** [comment]
@JohanBoer 
Om 1 of andere reden had mijn code generatie de historie request models een list van bsns gegeven. Ben benieuwd hoe dat ging. Heb waarschijnlijk iets verkeerds gedaan daar. Scheelt want anders snapte ik er totaal niks van waarom meerdere bsns :).

Ik kijk op dit moment naar datumAanvangAdreshouding. Dit was iig wat er bij 1.x gebruikt werd.

Verder helder!

@fsamwel 
Ik krijg in de database gevallen waar datum of 0 is of null. Zelfs gevallen waar een verblijfplaats meerdere volg_nrs heeft (dus historie) en dat bijv. bij volg_nr 3 er geen datum is, maar bij 0, 1, 2, 4 en 5 wel.
