### ISSUE TITLE
ouders en partners feature corrigeren

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1187]
laatste 2 scenario's in de ouders.feature en laatste feature van partners.feature zijn niet correct. Wanneer er wel een geslachtsnaam is en geen voornamen, en met fields is alleen voornamen gevraagd, dan moet naam als leeg object worden geleverd. Scenario's zeggen nu dat ouder/partner in zijn geheel als leeg object wordt geleverd

**Comment by fsamwel** [comment]
en in voorletters.feature scenario "Geen voornamen"

**Comment by fsamwel** [comment]
ook in kinderen.feature

**Comment by fsamwel** [comment]
ook lege-waarden feature correct en uitvoerbaar maken voor GBA variant. Zo nodig daarvoor gba of proxy tags toevoegen

**Comment by JohanBoer** [comment]
In ouders.feature is dit nu correct gedefinieerd. 
Partners.feature is nog niet omgezet naar end-to-end. Dus ook dit scenario nog niet gecorrigeerd. 

Bij volledigeNaam.feature vraag ik me af of je wel een leeg naam-object moet leveren (wat nu wel is doorgvoerd bij het scenario "volledig onbekende naam". De consumer krijgt daarmee de indicatie dat er wel naamgegevens zijn, maar dat hij die niet gevraagd heeft. Als hij vervolgens "naam" in de fields zet krijgt hij nog steeds een leeg object. Dan moet je volgens mij geen leeg object leveren bij het scenario, maar een persoon zonder 'naam' object.   

voorletters.feature is dit nu goed opgenomen (met leeg 'naam' object.

In kinderen.feature is dit nog niet aangepast, maar zou dat wel moeten worden gedaan. 

lege-waarden.feature is correct (leeg object leveren als er wel gegevens zijn, maar er alleen een leeg gegeven wordt gevraagd. )

lege-waarden-gba.feature moet nog gemaakt worden.
