### ISSUE TITLE
uitbreiden zoek-met features

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1188]
de zoek-met-... features zijn niet allemaal volledig. 

Dus denk ik dat in sommige van deze features moet worden toegevoegd of aangepast:
- scenario's zoeken en niks vinden bij andere waarde (m.n. optionele parameters); 
- scenario's zoeken met gemeenteVanInschrijving
- zoeken met diacrieten
- rule en/of scenario's voor overleden personen (soms ontbreekt scenario, soms zit scenario onder algemene rule)
- @fout-case scenario's

**Comment by MelvLee** [comment]
>     * scenario's zoeken en niks vinden bij andere waarde (m.n. optionele parameters);
Kan een voorbeeld worden gegeven wat er moet worden getoets?

**Comment by MelvLee** [comment]
>     * @gba of @Proxy (nu niet duidelijk welke component dit moet leveren)
Zoals eerder aangegeven is het toevoegen van de @gba tag alleen nodig als een scenario wordt gebruikt om de werking van de GBA API te beschrijven/documenteren en pas voor end to end testen kan worden gebruikt als de GBA API is geïmplementeerd. Alle zoek scenario's kunnen nu al worden gebruikt (icm de GBA API mock) en is het naar mijn mening dus niet nodig om het te taggen
