### ISSUE TITLE
verbeteren in onderzoek feature

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1202]
- Scenario: persoon heeft EU-persoonsnummer van nationaliteit in onderzoek die niet voorkomt in de resource >>> toevoegen nationaliteit en evt. EU-persoonsnummer in Gegeven, zodat type Nationaliteit wordt. Scenario wordt daarvan realistischer.
- Op regel 179/188 staat | geslacht            |           |. Dit suggereert dat veld geslacht voorkomt met lege waarde. Maar geslacht wordt niet geleverd, omdat we lege gegevens niet leveren. Apart scenario voor maken, want is wel belangrijk om te tonen dat inOnderzoek geleverd kan worden voor veld dat zelf geen waarde heeft (en daarom niet geleverd wordt)
- Opmerking bovenaan "Ook wanneer een gegeven geen waarde heeft en daardoor niet in het antwoord opgenomen wordt kan het in onderzoek zijn. In dat geval wordt alleen in inOnderzoek een veld opgenomen met die naam en de waarde true." moet een rule of expliciet scenario worden.
- waarden in Gegeven en Dan stappen realistischer maken. Dus niet locatiebeschrijving="locatiebeschrijving" of geslachtsnaam="geslachtsnaam"
- Scenario: kind heeft hele groep geboorte in onderzoek: naast geboorteplaats.code ook geboorte.plaats.omschrijving toevoegen in gegeven en dan stap

**Comment by fsamwel** [comment]
is het eerste punt wel terecht, gezien wat in issue #1204 wordt gevraagd?

**Comment by melsk-r** [comment]
> * Scenario: persoon heeft EU-persoonsnummer van nationaliteit in onderzoek die niet voorkomt in de resource >>> toevoegen nationaliteit en evt. EU-persoonsnummer in Gegeven, zodat type Nationaliteit wordt. Scenario wordt daarvan realistischer.

'nationaliteit' is inmiddels toegevoegd.

> * Op regel 179/188 staat | geslacht            |           |. Dit suggereert dat veld geslacht voorkomt met lege waarde. Maar geslacht wordt niet geleverd, omdat we lege gegevens niet leveren. Apart scenario voor maken, want is wel belangrijk om te tonen dat inOnderzoek geleverd kan worden voor veld dat zelf geen waarde heeft (en daarom niet geleverd wordt)

In 'in_onderzoek.feature' in de branch 'e2e-automation-inOnderzoek' vind je hiervoor het scenario 'vragen om <gegeven> zonder waarde bij <in onderzoek> in onderzoek'. Een veld zonder waarde voeren we in een 'Gegeven' stap nooit op dus zowel 'geboortedatum (03.10)' als  'voorvoegsel (02.30)' vind je daar niet terug.
Ook heb ik daar n.a.v. deze opmerking het scenario 'vragen om geboortedatum met standaardwaarde bij persoon in onderzoek' toegevoegd.

De Rule die daaraan ten grondslag ligt heb ik dus ook gewijzigd van:

_- deze wordt ook geleverd wanneer het gevraagde gegeven geen waarde heeft en daarom niet wordt geleverd in het antwoord_

in:

_- deze wordt ook geleverd wanneer het gevraagde gegeven geen waarde *of een standaardwaarde* heeft en daarom niet wordt geleverd in het antwoord_

> * Opmerking bovenaan "Ook wanneer een gegeven geen waarde heeft en daardoor niet in het antwoord opgenomen wordt kan het in onderzoek zijn. In dat geval wordt alleen in inOnderzoek een veld opgenomen met die naam en de waarde true." moet een rule of expliciet scenario worden.

Zie mijn voorgaande reactie. Ook de door jou aangehaalde opmerking heb ik overeenkomstig met mijn voorgaande reactie gewijzigd (zie 'in_onderzoek.feature' in de eerder genoemde branch).

> * waarden in Gegeven en Dan stappen realistischer maken. Dus niet locatiebeschrijving="locatiebeschrijving" of geslachtsnaam="geslachtsnaam"

Dat lijkt inmiddels gebeurd.

> * Scenario: kind heeft hele groep geboorte in onderzoek: naast geboorteplaats.code ook geboorte.plaats.omschrijving toevoegen in gegeven en dan stap

Dit is inmiddels niet meer van toepassing aangezien geboorteplaats in de bron geen waarde heeft en dus niet wordt teruggegeven.

Volgens mij kan dit issue gesloten worden.
