### ISSUE TITLE
features beperken tot de essentie

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1204]
zowel in Gegeven als in Dan stappen alleen dingen noemen die relevant zijn voor de functionaliteit die je wilt illustreren.

Nadeel/consequentie: voorbeeld is in zijn geheel niet meer heel "realistisch" (gegevens ontbreken die in het echt er wel zouden moeten zijn)
Voordelen: duidelijker wat getoond wordt en waarom dat gebeurt; minder kans op regressie doordat andere functionaliteit verweven is.

**Comment by JohanBoer** [comment]
Dit is meer een vuistregel dan een issue. Of willen we concrete acties aan deze issue koppelen (en zo ja, welke )
