### ISSUE TITLE
Uitwerken historie features

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1205]
In features map per endpoint (soort historie) een mapje voor betreffende features

Bijv. voor partnerhistorie de volgende features maken:
- peildatum-periode-filtering.feature
- sortering.feature
- bepalen-partnerschap.feature
- filtering-datum-onbekend.feature
- request-validatie.feature
- in-onderzoek.feature
- fields.feature
- datum.feature
- ...

**Comment by melsk-r** [comment]
De tweede rule is niet correct, deze moet volgens mij als volgt luiden:

_Bij vragen van partnerhistorie op periode worden alleen de partners geleverd waarbij de Datum huwelijkssluiting/aangaan geregistreerd partnerschap niet op of na de datumTot ligt of de eventuele Datum ontbinding huwelijk/geregistreerd partnerschap niet voor of op de datumVan ligt._

Tenminste als de gewenste situatie als volgt is:

![image](https://user-images.githubusercontent.com/20185784/178516563-9bb8ff5d-c34c-432a-8c98-5a2e4bed1d1a.png)

Waarbij elk aaneen gesloten kleurblok 1 huwelijk is. Persoon 1 is dus 5 keer gehuwd en persoon 7 maar 1 keer. 

Ik ben er hier vanuit gegaan dat alleen de groene huwelijken worden opgenomen in de response n.a.v. de hierboven gedefinieerde rule omdat ze deels of geheel binnen de datumVan en datumTot periode liggen.

Als de huidige rule gebruikt zou worden dan zouden juist de rode blokken worden opgenomen in de response.

Wat ik nog wel wil weten is of de huwelijken die eindigen op de datumVan datum of beginnen op de datumTot datum nog/al wel of juist niet opgenomen moeten worden in de response. Ik ben er in de nieuwe rule definitie vanuit gegaan dat deze niet opgenomen moeten worden in de response.
