### ISSUE TITLE
adressering wordt leeg geleverd wanneer hele groep gevraagd

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1237]
```
{
  "fields": ["adressering"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999992466"]
}
```
Dit geeft:
```
            "adressering": {}
```
Zelfde bij "fields": ["adressering", "adresregel1"].

Maar wanneer ik daarnaast een detailveld vraag krijg ik wel naamvelden in de adressering, niet alleen het gevraagde veld:
```
{
  "fields": ["adressering", "adressering.aanhef"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999992466"]
}
```
levert:
```
            "adressering": {
                "aanhef": "Geachte mevrouw Le Sommer",
                "gebruikInLopendeTekst": "mevrouw Le Sommer"
            }
```

**Comment by JohanBoer** [comment]
> ```
> {
>   "fields": ["adressering"],
>   "type": "RaadpleegMetBurgerservicenummer",
>   "burgerservicenummer": ["999992466"]
> }
> ```

Hierbij wordt inmiddels de volledig adressering geleverd. 
 
Bij de vraag met "fields": ["adressering", "adresregel1"]. wordt echter 
> 
> ```
>             "adressering": {}
> ```
> 
geleverd terwijl er wel degelijk een adresregel1 is

Vragen om het detailveld "aanhef" lever ook netjes de adressering.aanhef terug.
