### ISSUE TITLE
fields "adresregel1" geeft foutmelding op verblijfplaats.naamOpenbareRuimte

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1250]
ik krijg bij zoeken (niet bij raadpleeg met burgerservicenummer) en fields "adresregel1" een foutmelding:

```
    "invalidParams": [
        {
            "name": "fields",
            "code": "fields",
            "reason": "Deel van de parameterwaarde niet correct: verblijfplaats.naamOpenbareRuimte."
        }
    ]
```

N.B. naamOpenbareRuimte is niet nodig voor het bepalen van adresregel1
N.B. naamOpenbareRuimte komt niet voor in GbaVerblijfplaatsBeperkt (wel in GbaVerblijfplaats)

**Comment by KayodeBakker** [comment]
@fsamwel Opvallend genoeg, krijg ik wat anders maar ook dat is fout wat ik krijg. Alleen des te belangrijker dat we bij issues voortaan de image container versie erbij vernoemen.
