### ISSUE TITLE
Kinderen feature niet correct voor lege objecten

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1257]
Volgens mij was afgesproken dat de wijzigingen uit P.R. #1198 zouden worden overgenomen in de features, zodat die PR kan vervallen. Dit is voor de kinderen feature nog niet gedaan.
Daarnaast zijn er nog enkele andere correcties die n.m.m. moeten worden doorgevoerd.

Regel 88: Dan heeft de response een persoon met een 'kind' zonder 'naam' gegevens
Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object

Regel 124: Dan heeft de response een persoon zonder 'kind' gegevens
Moet worden: heeft de persoon een 'kind' zonder gegevens

Regel 130 e.v.: hier wordt de PL van het kind niet opgevoerd. Daardoor doet het scenario niet meer wat het bedoelt te tonen.

Regel 160 en 161, 187: wat gebeurt hier met het opvoeren van een leeg burgerservicenummer en leeg geslacht resp. lege voornamen? Zijn deze gegevens er wel, maar dan met lege string waarde? Of NULL waarde? Volgens mij hebben we afgesproken dat wanneer een element geen waarde heeft (null, none, undefined), het niet in Gegeven wordt opgenomen.

Regel 175: Dan heeft de response een persoon met een leeg 'kind' object
Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object
En heeft de response een persoon met een 'kind' met een leeg 'geboorte' object
@MelvLee klopt dit zo? Kan je met twee stappen op hetzelfde kind van dezelfde persoon controleren op beide lege objecten?

In de proxy scenario's zijn in de Gegeven-stappen de veldnamen nog niet in LO formaat. Bijvoorbeeld "voornamen" i.p.v. "voornamen (02.10)".

Regel 197: Dan heeft de response een persoon met een leeg 'kind' object
Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object

**Comment by MelvLee** [comment]
> Regel 88: Dan heeft de response een persoon met een 'kind' zonder 'naam' gegevens Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object
>
Beide dan stappen bestaan. De eerste is toegevoegd omdat die minder technisch leest. Tweede bestaat nog om ervoor te zorgen dat 'proxy' scenario's blijven werken.

 
> Regel 124: Dan heeft de response een persoon zonder 'kind' gegevens Moet worden: heeft de persoon een 'kind' zonder gegevens
>
Zie opmerking hierboven
 
> Regel 130 e.v.: hier wordt de PL van het kind niet opgevoerd. Daardoor doet het scenario niet meer wat het bedoelt te tonen.
> 
> Regel 160 en 161, 187: wat gebeurt hier met het opvoeren van een leeg burgerservicenummer en leeg geslacht resp. lege voornamen? Zijn deze gegevens er wel, maar dan met lege string waarde? Of NULL waarde? Volgens mij hebben we afgesproken dat wanneer een element geen waarde heeft (null, none, undefined), het niet in Gegeven wordt opgenomen.
> 
Dit zijn op dit moment nog proxy scenario's en geen end-to-end scenario's. Ik dacht dat we afgesproken hadden om deze nog niet te veranderen.

> Regel 175: Dan heeft de response een persoon met een leeg 'kind' object Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object En heeft de response een persoon met een 'kind' met een leeg 'geboorte' object @MelvLee klopt dit zo? Kan je met twee stappen op hetzelfde kind van dezelfde persoon controleren op beide lege objecten?
> 
Nee, zoals het nu is aangegeven krijgt je 2 personen in de response. Een met een kind met een leeg 'naam' object en één met een leeg 'geboorte' object. Deze moet worden
```
Dan heeft de response een 'kind' zonder 'naam' gegevens
En heeft het 'kind' geen 'geboorte' gegevens
```
of
```
Dan heeft de response een 'kind' met een leeg 'naam' object
En heeft het 'kind' een leeg 'geboorte' object
```


> In de proxy scenario's zijn in de Gegeven-stappen de veldnamen nog niet in LO formaat. Bijvoorbeeld "voornamen" i.p.v. "voornamen (02.10)".
> 
> Regel 197: Dan heeft de response een persoon met een leeg 'kind' object Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object

**Comment by melsk-r** [comment]
> Regel 88: Dan heeft de response een persoon met een 'kind' zonder 'naam' gegevens Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object

De step 'Dan heeft de response een persoon met een 'kind' zonder 'naam' gegevens' levert:

```
[ 
  {
    "kinderen": [
      {
        "naam": {}
      }
    ]
  }
]
```
op wat volgens mij is wat je wil. Toch?

> Regel 124: Dan heeft de response een persoon zonder 'kind' gegevens Moet worden: heeft de persoon een 'kind' zonder gegevens

Volgens mij is dit het verschil tussen resp. ` [ { kinderen: [] } ] `  en `[ { kinderen: [ {} ] ]`
Lijkt mij dat als je een ontkent een kind te hebben dat je het eerste wil, of zie ik dat verkeerd?

> Regel 130 e.v.: hier wordt de PL van het kind niet opgevoerd. Daardoor doet het scenario niet meer wat het bedoelt te tonen.

Dit begrijp ik niet, hier staat `Gegeven de persoon met burgerservicenummer '000000085' heeft een 'kind' met de volgende gegevens`. Volgens mij wordt daar juist wel de PL van het kind mee opgevoerd. Hoe zou het in jouw ogen moeten dan?

> Regel 160 en 161, 187: wat gebeurt hier met het opvoeren van een leeg burgerservicenummer en leeg geslacht resp. lege voornamen? Zijn deze gegevens er wel, maar dan met lege string waarde? Of NULL waarde? Volgens mij hebben we afgesproken dat wanneer een element geen waarde heeft (null, none, undefined), het niet in Gegeven wordt opgenomen.

Klopt maar omdat het hier om @proxy scenario's gaat hebben we besloten deze voorlopig ongewijzigd te laten. Ik heb hier dus niet naar gekeken.
 
> Regel 175: Dan heeft de response een persoon met een leeg 'kind' object Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object En heeft de response een persoon met een 'kind' met een leeg 'geboorte' object @MelvLee klopt dit zo? Kan je met twee stappen op hetzelfde kind van dezelfde persoon controleren op beide lege objecten?

Ik zal dit wijzigen omdat dit in #1198 is gewijzigd maar hier geldt eigenlijk hetzelfde als voor regel 160, 161 en 187.
 
> In de proxy scenario's zijn in de Gegeven-stappen de veldnamen nog niet in LO formaat. Bijvoorbeeld "voornamen" i.p.v. "voornamen (02.10)".

Zie voorgaande opmerkingen.
 
> Regel 197: Dan heeft de response een persoon met een leeg 'kind' object Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object

Zie voorgaande opmerkingen.

**Comment by fsamwel** [comment]
> > Regel 88: Dan heeft de response een persoon met een 'kind' zonder 'naam' gegevens Moet worden: Dan heeft de response een persoon met een 'kind' met een leeg 'naam' object
> Beide dan stappen bestaan. De eerste is toegevoegd omdat die minder technisch leest. Tweede bestaat nog om ervoor te zorgen dat 'proxy' scenario's blijven werken.

Ik vind dit geen duidelijke Dan stap voor dit scenario. We hebben om aan te geven dat je een leeg object op een groep krijgt nu drie varianten:
1. heeft de persoon een 'kind' zonder 'naam' gegevens
2. heeft het 'kind' geen 'naam' gegevens
3. heeft de response een persoon met een 'kind' met een leeg 'naam' object

Ik vind de eerste twee varianten nogal impliciet op wat je hier wilt vertellen en controleren. Het gaat er in deze stappen om dat je wilt zeggen dat het 'kind' een veld 'naam' heeft dat een leeg object is:
```'kinderen': [{ 'naam': {} }]```

"zonder 'naam' gegevens", of "geen 'naam' gegevens" zou je ook kunnen lezen als "zonder 'naam' gegeven" (zonder de 's'), dus er is geen gegeven 'naam'. En dat is nu net juist wat we niet willen. Het correct lezen van de stap hangt dan af van 1 letter, weglaten van die ene letter maakt de betekenis het tegenovergestelde. 1 letter minder en de foutsituatie is goed.
Ik las/interpreteerde het in ieder geval anders en dacht daardoor dat het er fout stond.

De nu gebruikte variant is denk ik wel beter wanneer je wilt vaststellen dat bepaalde gegevens niet geleverd worden, bijvoorbeeld wanneer je wilt duidelijk maken dat geslachtsnaam="." niet geleverd wordt is het heel duidelijk om te zeggen "heeft de persoon een 'kind' zonder 'naam' gegevens". Maar wanneer je juist het technische verhaal wilt vertellen dat er wel een veld 'naam' wordt geleverd, maar daar geen gegevens in zitten, zou ik dat in de feature ook expliciet zo benoemen.

**Comment by fsamwel** [comment]
> > Regel 130 e.v.: hier wordt de PL van het kind niet opgevoerd. Daardoor doet het scenario niet meer wat het bedoelt te tonen.
> Dit begrijp ik niet, hier staat Gegeven de persoon met burgerservicenummer '000000085' heeft een 'kind' met de volgende gegevens. Volgens mij wordt daar juist wel de PL van het kind mee opgevoerd. Hoe zou het in jouw ogen moeten dan?

Het gaat erom dat er twee PLs zijn, 1 van de ouder, 1 van het kind. Op de PL van de ouder staan er -na alle wijzigingen- andere gegevens over het kind, dan op de PL van het kind.

```
    Scenario: Het kind heeft geslachtswijziging en naamswijziging ondergaan, maar de gevraagde persoon erkent dit niet
      Gegeven de persoon met burgerservicenummer '000000085' heeft een 'kind' met de volgende gegevens
      | burgerservicenummer (01.20) | voornamen (02.10) | geslachtsaanduiding (04.10) |
      | 000000097                   | Karel             | M                           |
      En het 'kind' is gewijzigd naar de volgende gegevens
      | burgerservicenummer (01.20) | voornamen (02.10) | geslachtsaanduiding (04.10) |
      | 000000097                   | Charlotte         | V                           |
      En het 'kind' is gewijzigd naar de volgende gegevens
      | burgerservicenummer (01.20) | voornamen (02.10) | geslachtsaanduiding (04.10) |
      | 000000097                   | Karel             | M                           |
      En de persoon met burgerservicenummer '000000097' heeft de volgende gegevens
      | burgerservicenummer (01.20) | voornamen (02.10) | geslachtsaanduiding (04.10) |
      | 000000097                   | Karel             | M                           |
      En de persoon is gewijzigd naar de volgende gegevens
      | burgerservicenummer (01.20) | voornamen (02.10) | geslachtsaanduiding (04.10) |
      | 000000097                   | Charlotte         | V                           |
      Als personen wordt gezocht met de volgende parameters
      | naam                | waarde                                               |
      | type                | RaadpleegMetBurgerservicenummer                      |
      | burgerservicenummer | 000000085                                            |
      | fields              | kinderen.burgerservicenummer,kinderen.naam.voornamen |
      Dan heeft de response een persoon met een 'kind' met de volgende gegevens
      | naam                | waarde    |
      | burgerservicenummer | 000000097 |
      | naam.voornamen      | Karel     |
```

**Comment by melsk-r** [comment]
De hierboven door fsamwel verzochte wijziging is aangebracht in PR #1460.
Volgens mij kan dit issue gesloten worden zodra die PR is gemerged.
