### ISSUE TITLE
Bij gemeente van inschrijving en/of datum inschrijving in de gemeente in onderzoek wordt verblijfplaats.inOnderzoek niet gevuld

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1297]
Als gemeente van inschrijving en/of datum inschrijving in de gemeente in onderzoek zijn, en deze twee velden worden middels fields opgevraagd, dan moet verblijfplaats.inOnderzoek zijn gevuld zodat de brpproxy dit kan aangeven in zijn response

reproductie pad:
- npx cucumber-js features/gba-dev/persoon.feature:39
- npx cucumber-js features/gba-dev/persoon.feature:65

versie:
- gba-api: 2.0.3

**Comment by KayodeBakker** [comment]
Op dit moment (gba-api: 2.0.7) is dit geen issue meer. Zie jij dat ook zo?
