### ISSUE TITLE
Wanneer wordt indicatieOverleden op true gezet?

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1298]
Er zijn geen scenario's die beschrijven wanneer indicatieOverleden op true wordt gezet

**Comment by CathyDingemanse** [comment]
Als: 
**07.67.10 Datum opschorting bijhouding**
De datum waarop de bijhouding van de persoonslijst is opgeschort. Dit is
in dit geval de overlijdensdatum.
**07.67.20 Omschrijving reden opschorting bijhouding**
De aanduiding van de reden waarom de bijhouding van de persoonslijst is
opgeschort. Dit is in dit geval de waarde "O" van overlijden.

Kun jij zelf deze scenario's beschrijven?

**Comment by MelvLee** [comment]
> Als: **07.67.10 Datum opschorting bijhouding** De datum waarop de bijhouding van de persoonslijst is opgeschort. Dit is in dit geval de overlijdensdatum. **07.67.20 Omschrijving reden opschorting bijhouding** De aanduiding van de reden waarom de bijhouding van de persoonslijst is opgeschort. Dit is in dit geval de waarde "O" van overlijden.
> 
> Kun jij zelf deze scenario's beschrijven?

Sorry. Mijn issue is niet duidelijk. Het betreft overlijden. Daarvoor is niet gespecificeerd wanneer indicatieOverleden op true wordt gezet. Ik ben getriggered door twee redenen:
- in de overlijden.yaml. Daar staat bij IndicatieOverleden als description: Geeft aan dat iemand is overleden (waarde true), ongeacht of de overlijdensdatum bekend is. Geldt dit dan niet als land en/of plaats?
- p.r. #1269, in_onderzoek.feature regel 964. Daar staat alleen bij datum overlijden in onderzoek wordt indicatieOverleden in onderzoek gezet. Dus niet voor land en/of plaats? Maar als groep of categorie in onderzoek is, wordt indicatieOverleden wel in onderzoek gezet.

**Comment by CathyDingemanse** [comment]
1. hoe het precies in de registraties voorkomt (wanneer datum gevuld (evt. met 00-00--0000) ook plaats en land bekend etc.?) en de gevolgen daarvan voor indicatie geheim bespreken met @fsamwel 
2. indicatie overleden altijd teruggeven, ookal heeft consumer er niet om gevraagd. @MelvLee wil jij daarvoor een feature maken?

**Comment by MelvLee** [comment]
> 1. hoe het precies in de registraties voorkomt (wanneer datum gevuld (evt. met 00-00--0000) ook plaats en land bekend etc.?) en de gevolgen daarvan voor indicatie geheim bespreken met @fsamwel
>
Ik neem aan dat hier indicatie overleden wordt bedoeld ipv indicatie geheim
 
>     2. indicatie overleden altijd teruggeven, ookal heeft consumer er niet om gevraagd. @MelvLee wil jij daarvoor een feature maken?

Zie p.r. #1320

**Comment by CathyDingemanse** [comment]
> Ik neem aan dat hier indicatie overleden wordt bedoeld ipv indicatie geheim
> 
> > ```
yess aangepast, excuus.

**Comment by JohanBoer** [comment]
> * hoe het precies in de registraties voorkomt (wanneer datum gevuld (evt. met 00-00--0000) ook plaats en land bekend etc.?) en de gevolgen daarvan voor indicatie overleden bespreken met @fsamwel
> * indicatie overleden altijd teruggeven, ookal heeft consumer er niet om gevraagd. @MelvLee wil jij daarvoor een feature maken?

Er is nu een dev-feature "overlijden.feature" gemaakt waarbij de scenario's afdwingen dat de indicatieoverleden altijd geleverd wordt als de persoon is overleden en er wordt om gegevens uit de groep overlijden gevraagd . Maar: 

- Er moet aan dev/overlijde.feature een scenario worden toegevoegd dat indicatieoverleden teruggeeft als er niet om overlijdengegevens wordt gevraagd. 
- Er moet een gba-dev/overlijden worden gemaakt waarin duidelijk gemaakt moet worden dat als er iets van een persoon gevraagd wordt en deze is overleden dat dan altijd de overlijdensdatum wordt geretourneerd.
- Er moet een feature komen waar in business-termen de rule beschreven wordt dat bij een overleden persoon altijd de indicatieoverleden wordt geretourneerd.

**Comment by JohanBoer** [comment]
Zie pull request #1444

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse ik begrijp een paar dingen niet aan dit issue, die in #1320 en #1444 zijn doorgevoerd.
> 
> 1. indicatieOverleden wordt afgeleid van overlijdensdatum en wordt nu automatisch (ongevraagd) geleverd. Daarnaast wordt ook opschoringBijhouding geleverd, in dit geval met waarde O (overlijden). Is daarbij ook automatisch leveren indicatieOverleden dan niet dubbelop?

Ja dat kan. Ik ben me er niet van bewust dat ook op[schorting ook automatisch wordt geleverd als daar niet om wordt gevraagd. Is dat beschreven? Graag even bespreken.

>    De gba API stuurt dan ook de overlijdensdatum mee. Waarom wordt indicatieOverleden niet afgeleid van opschortingBijhouding=O? Scheelt weer een extra veld meesturen.

Ik meen dat deze werkwijze was afgeleid uit de handleiding, en getoetst bij Frans.


> 2. wanneer er onderzoek is naar bijvoorbeeld de plaats van overlijden, wordt ook indicatieOverleden in onderzoek gezet. Waarom? Er is toch geen twijfel aan of de persoon overleden is?

Dat klopt. Ik denk dat dat moet worden aangepast.
> 
> Daarnaast is vergeten deze keuze op inOnderzoek door te voeren in [in onderzoek.xlsx](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/features/in%20onderzoek.xlsx)

OK, ook even bespreken.

**Comment by fsamwel** [comment]
vraag gesteld aan RvIG of het voorkan komen dat overlijdensdatum gevuld is, maar opschorting bijhouding reden <> 'O'

**Comment by CathyDingemanse** [comment]
Antwoord gegeven op 20-12-2022:
Omgekeerd geldt hetzelfde. De Wet van Murphy bepaalt dat het ondanks het feit dat het niet kan voorkomen, toch een keer zal voorkomen. Maar het wordt aan alle kanten gecontroleerd, dus daar hoeft de API geen rekening mee te houden.
