### ISSUE TITLE
Response van de GBA API bevat ten onrechte een 'aangaanHuwelijkPartnerschap'

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1319]
Zie hiervoor scenario's in de regels 542 en 543 van in_onderzoek.feature.

Een 'aanduiding in onderzoek (83.10)' met de waarde 051500 of 051510 heeft geen betrekking op 'aangaanHuwelijkPartnerschap'.

**Comment by KayodeBakker** [comment]
Als ik in_onderzoek.feature uitvoer dan krijg ik een hoop undefined. Is dit een feature dat nog in een PR staat en niet in de develop branch? Ik kan niet nabootsen wat jij meldt.

**Comment by melsk-r** [comment]
Dit issue heeft betrekking op het abstracte scenario 'partner heeft <nauwkeurigheid> soort verbintenis in onderzoek' en kent nog steeds dezelfde fouten.

In de response wordt n.m.m. binnen partners onterecht een 'aangaanHuwelijkPartnerschap', een lege 'geboorte' en lege 'naam' geleverd. Alledrie deze gegevens horen niet voor te komen.

**Comment by fsamwel** [comment]
ik vind deze situatie niet meer in een feature
