### ISSUE TITLE
2.0 beta: hoe worden we geacht referenties naar (ingeschreven) personen op te slaan?

### ISSUE THREAD

**Issue by sergei-maertens** [BRP-API/Haal-Centraal-BRP-bevragen#1370]
Gegeven:

1. Een organisatie maakt gebruik van de 2.0.0 versie van deze API die `POST` requests gebruikt om persoonsgegevens op te halen
2. Diezelfde organisatie eist dat alle verkeer door een eigen API gateway loopt (dus er is geen landelijke registratie die bevraagd kan worden)
3. Een derde applicatie (bijvoorbeeld een zakenregister) moet verwijzingen naar personen opslaan (zoals de initiator van een zaak)

In het kader van gegevens bij de bron wil je niet de persoonsgegevens dubbel opslaan.

Doordat er nu geen API resource URLs meer bestaan voor een persoon, is er geen resource URL meer die je kan opslaan. Met enkel het BSN (wat je idealiter ook niet zou opslaan, maar wel mogelijk via v1) heb je niet voldoende: je weet immers niet precies in welke personenregistratie de gegevens te vinden zijn door gebrek aan fully qualified resource URL.

Vanuit een data-normalisatieperspectief wil je verwijzingen naar personen op een consistente manier opslaan, en dat rijmt niet met de verschillende zoekopdrachten die mogelijk zijn (dan weer op BSN, dan weer op combinatie achternaam / geboortedatum etc.). Er is ook geen garantie in het API schema dat zo'n zoekopdracht slechts 1 resultaat teruggeeft in de lijst van resultaten (en dan loop je ook nog tegen #1276 aan).

De enige praktische oplossing die ik zo snel kan bedenken is API resources met een UUID in het pad ontsluiten (dit is niet te herleiden tot een persoonsgegeven) en via een GET endpoint beschikbaar stellen. Dit is tevens ook compatibel met HTTP caches, wat de POST requests niet zijn.

**Comment by sergei-maertens** [comment]
Er komen meer vragen om BRP 2.0 te ondersteunen bij ons - is hier al een werkwijze voor beschikbaar?

**Comment by MelvLee** [comment]
De BRP API volgt zoveel mogelijk de security aanbevelingen van de OWASP Foundation en de mitigeer aanbevelingen die zijn beschreven in de CWE.

Het opnemen van gevoelige gegevens in een URL door gebruik te maken van de GET method en query string parameters leidt tot information exposure. Alleen HTTPS gebruiken om de gegevens geëncrypt te versturen lost het probleem niet op, omdat de url kan worden opgeslagen in caches en logs. De aanbevolen manier om gevoelige data te versturen is gebruik te maken van de POST method. Zie Potential Mitigations van [CWE-598](https://cwe.mitre.org/data/definitions/598.html)

Voor het opslaan van gevoelige gegevens is de aanbeveling om de gevoelige gegevens ge-encrypt op te slaan. Welke mate van encryptie moet worden toegepast hangt af of er andere en wat voor gevoelige gegevens door de applicatie/systeem moet worden opgeslagen. Aanbevelingen hiervoor zijn te vinden in de paragraaf 'How to Prevent' in [A02:2021 - Cryptographic Failures](https://owasp.org/Top10/A02_2021-Cryptographic_Failures/)

Het gebruiken van een UUID als identifier omdat hiermee niet te herleiden tot een persoonsgegeven is slechts gedeeltelijk waar. Het klopt dat een gevoelig gegeven (in dit geval de bsn) niet meer in een URL terecht komt, maar een systeem moet nu wel de relatie vastleggen van twee identificerende gegevens. In systeem A kan dit de bsn en de UUID zijn en in systeem B een e-mail adres en de UUID. Een bsn en e-mail adres zijn immers makkelijker te onthouden en foutloos handmatig op te voeren dan een UUID. Als deze gegevens niet geëncrypt worden opgeslagen, dan is het heel makkelijk om de opslag van beide systemen query-en, de gegevens aan elkaar te linken met behulp van de UUID en daarna met de gecumuleerde gegevens te herleiden naar een persoon.

De aanbevolen werkwijze voor gevoelige gegevens is dus encrypten wanneer het wordt opgeslagen of wordt verstuurd.

**Comment by sergei-maertens** [comment]
Dank voor het antwoord!

Ik ben bekend met de achtergrond daar ik héél lang geleden één van de mensen was die hier nogal vocaal over was, precies met het argument van webserver logs :wink: 

Dat terzijde heb ik nu eigenlijk nog geen praktisch antwoord in de context van het werken met verwijzingen in de ene API naar de andere API (BRP API in dit geval), heel concreet gaat het dus om de Zaakgericht Werken API's waarin verwijzingen naar een persoon vastgelegd worden als bijvoorbeeld zijnde de initiator van een zaak. Dit is een generieke, polymorfe constructie waarbij de `betrokkene` als hoedanig een verwijzing is naar de relevante registratie op basis van het betrokkeneType (bijvoorbeeld natuurlijk persoon, maar kan ook NNP of medewerker zijn...)

Deze gegevens worden door meerdere clients in meerdere applicaties uitgelezen - een generiek zaakafhandelcomponent, of bijvoorbeeld een taakspecifieke applicatie die als data-opslag een centrale Zaken API gebruikt. Deze clients moeten voldoende informatie krijgen om vervolgens zelf de relevante registratie te bevragen, zodat de (in dit geval) relevante persoonsgegevens kunnen getoond worden - aan de behandelaar, of de initiator van de zaak zelf bijvoorbeeld (in het geval van mede-initiator).

Ik snap niet goed hoe encryptie hier een probleem oplost - de opzoekparameters (zij het dan een BSN, zij het een UUID...) moeten toch naar de API client als response teruggegeven worden (merk op dat de client in dit geval ook gewoon server-side kan zijn en niet per se een browser client is). Om iets nuttigs met die gegevens te doen, moeten ze sowieso gedecrypt worden. Encryptie is dus enkel relevant voor data-at-rest, in-flight data is beschermd via HTTPS.

> Het klopt dat een gevoelig gegeven (in dit geval de bsn) niet meer in een URL terecht komt, maar een systeem moet nu wel de relatie vastleggen van twee identificerende gegevens. In systeem A kan dit de bsn en de UUID zijn en in systeem B een e-mail adres en de UUID. Een bsn en e-mail adres zijn immers makkelijker te onthouden en foutloos handmatig op te voeren dan een UUID.

Het idee is bevragen bij de bron - ik snap niet meteen het nut van het koppelen van een UUID met een BSN en die vervolgens aan mekaar linken. Met het UUID zou je direct de bron moeten kunnen bevragen en daarmee de relevante persoonsgegevens ophalen. Het hele punt van het opslaan van deze verwijzingen is net het wel kunnen herleiden tot persoonsgegevens omdat die inzichtelijk dan wel gebruikt moeten worden om überhaupt een functionele applicatie te kunnen bouwen.

Daarnaast is het m.i. taak van de server-side applicaties om een afdoend autorisatiemodel te implementeren zodat clients niet zomaar naar believen allerlei registraties kunnen bevragen om zodoende ongeoorloofd gegevens aan elkaar te koppelen en tot persoonsgegevens te herleiden. Er moet dus een relevante doelbinding zijn.

Ik heb nu eigenlijk nog steeds geen antwoord over hoe deze functionaliteit concreet gerealiseerd moet worden...

**Comment by MelvLee** [comment]
Ik interpreteerde uit je initiele vraag dat jullie geen gevoelige gegevens willen opslaan in jullie systeem. Wat ik nu uit jouw reactie opmaak is dat jullie een integratie issue hebben en niet een security/privacy issue.

Proclaimer vooraf omdat het naar mijn mening niet mogelijk is om op basis van beperkte informatie met een concrete oplossing te komen. De oplossing die ik aanreik is gebaseerd op de volgende aannames die ik maak en moet worden gezien als een oplossingsrichting:

Jullie Zaken systeem is een RESTful systeem. De clients van jullie Zaken systeem gebruiken één verwijzing (URI) naar resources en willen dynamisch/at runtime worden doorverwezen naar andere relevante resources door URIs die zijn opgenomen in de response van een request. Met andere woorden, externe APIs moeten ook RESTful zijn en HATEOAS implementeren.

Is dit realistisch, aangezien er ook andere API styles bestaan zoals GraphQL en GRPC? En als een externe API de REST API style volgt, dan kunnen zij een ander HATEOAS variant, zoals JSON HAL, Siren, json:api en JSON for Linking Data, hebben geïmplementeerd dan jullie Zaken systeem. Of zijn de clients van jullie Zaken systeem zo slim dat ze at runtime de payload van een response gaan parsen om de data en de verwijzingen uit de payload te halen?

Los van het RESTful zijn, zijn er andere constraints waardoor het niet mogelijk is om alleen met een URI een resource te bevragen, zoals security. De APIs die ik ken hanteren mTLS in combinatie met API key of oAuth2. Voor mTLS is een client certificaat vereist. Heeft elk van jullie clients een eigen client certificaat? Dat is niet handig voor de externe API want de client certificaten moeten dan bij de externe API worden geïnstalleerd. Of gebruiken al de clients van jullie Zaken systeem hetzelfde client certificaat? Wat security wise natuurlijk niet handig is. Ook de API keys en client secrets zou je niet willen delen tussen clients.

Op basis van bovenstaande zou ik adviseren om de anti-corruption layer pattern te implementeren in jullie Zaken systeem. In jullie Zaken systeem definieer je eigen URIs (met UUIDs) voor externe resources. Requests naar deze URIs worden onderschept en getransformeerd naar requests voor de externe APIs. Omgekeerd kunnen de responses van de externe APIs worden omgezet in responses die door de clients kan worden verwerkt. Hiermee wordt de logica om te kunnen koppelen met een externe API op één plek gerealiseerd in plaats van bij al de clients.

**Comment by sergei-maertens** [comment]
> Jullie Zaken systeem is een RESTful systeem.

"Ons" zakensysteem implementeert gewoon de VNG Standaarden en was één van eerste VNG projecten om Common Ground principes van "bevragen bij de bron" toe te passen op basis van services (dus loskoppelen van gegevens en applicatie/processen). Dit is vanaf het begin af aan opgezet met het idee dat het hele gegevenslandschap die kant op beweegt, en er is dus ook met een schuin oog gekeken naar ontwikkelingen in andere domeinen. Er is ook actief communicatie opgezocht zodat die andere domeinen op de hoogte zijn van de VNG ZGW ontwikkelingen om netjes op mekaar te kunnen aansluiten. Het lijkt erop dat deze afstemming gaandeweg verloren gegaan is.

Deze APIs implementeren ook niet REST puristisch, want het moet praktisch bruikbaar blijven. HATEOAS is overigens iets waarvan ik persoonlijk nog steeds geen real-world use case voor zie, het feit dat er URL referenties gebruikt worden naar externe resources heeft daar niets mee te maken - dat is puur een API design implementatie-detail. Uitgangspunt was wel dat er van SOAP services richting RESTful (-ish) toe bewogen wordt. Maar de API definities specifiëren URI's, niet per se URLs, dus een `urn` zou ook een optie zijn als verwijzing.

> Met andere woorden, externe APIs moeten ook RESTful zijn en HATEOAS implementeren.

Dit lijkt mij dus een voorbarige conclusie.

> Is dit realistisch, aangezien er ook andere API styles bestaan zoals GraphQL en GRPC? En als een externe API de REST API style volgt, dan kunnen zij een ander HATEOAS variant, zoals JSON HAL, Siren, json:api en JSON for Linking Data, hebben geïmplementeerd dan jullie Zaken systeem. Of zijn de clients van jullie Zaken systeem zo slim dat ze at runtime de payload van een response gaan parsen om de data en de verwijzingen uit de payload te halen?

Daarom worden er dus standaarden gedefinieerd waar leveranciers aan moeten voldoen. Dus ook de Haal Centraal standaard, en beide standaarden dienen zo gedefinieerd te zijn dat data-uitwisseling in daadwerkelijke applicaties mogelijk is. Het kan dus zijn dat 1 of beide kanten hiervoor aanpassingen moeten maken. Een standaard beschrijft met welke versies/stijlen van een andere standaard die compatibel is en zo weten developers wat ze kunnen verwachten. Op dit moment zijn de ZGW API's dus niet compatibel met BRP bevragen 2.0. De NL API strategie schrijft voor om bij voorkeur API's met OpenAPI 3.0 te documenteren, en dat documentatieformaat laat je dus toe om behoorlijk volledig de mogelijke content types etc. te beschrijven. Dingen zoals gRPC (en eventueel SOAP) hierbij betrekken lijkt me pas relevant als externe services dat ook gaan toepassen, maar ook zij horen hun design te baseren op de huidige en verwachte staat van het gegevenslandschap (lees: zorg eerst maar eens dat iedereen netjes JSON API's kan bouwen en dan komen we al een heel eind).

> Los van het RESTful zijn, zijn er andere constraints waardoor het niet mogelijk is om alleen met een URI een resource te bevragen, zoals security. De APIs die ik ken hanteren mTLS in combinatie met API key of oAuth2. Voor mTLS is een client certificaat vereist. Heeft elk van jullie clients een eigen client certificaat? Dat is niet handig voor de externe API want de client certificaten moeten dan bij de externe API worden geïnstalleerd. Of gebruiken al de clients van jullie Zaken systeem hetzelfde client certificaat? Wat security wise natuurlijk niet handig is. Ook de API keys en client secrets zou je niet willen delen tussen clients.

Wij hebben netjes een library gebouwd waarmee we dus precies die mTLS en API key parameters kunnen toevoegen in het runtime gedrag. Dit is een eenvoudige lookup table:

1. Gegeven URL `https://example.com/service/api/v1/resource/:uuid`
2. Zoek de service definitie voor deze URL
3. Vind service met API root `https://example.com/service/api/v1/`
4. Lees service configuratie uit (mTLS certificaten, API key, dan wel oauth2 client ID + secret...)
5. Bouw relevante Auth HTTP headers op
6. Maak HTTP request

Dit hebben we generiek en netjes in de praktijk werken in Open Formulieren én komt straks in Open Zaak. Daarnaast lost de FSC (ook wel bekend als NLX) standaard veel van die dingen op waarbij dynamisch de toegang van afnemer tot aanbieder via een management UI kan ingeregeld worden, en dan hoeft de applicatie niet eens meer zelf support voor mTLS/auth te implementeren omdat de API gateway dit dus regelt.

Het lijkt me overigens evident dat de client certificaten bij de externe api (aanbieder gegevens) geïnstalleerd worden, want dat is precies waarvoor je mTLS gebruikt - de client moet zich authenticeren. Een beetje (web) developer kan prima hiervoor een databasetabelletje en beheeromgeving bouwen hoor.

Open Zaak als aanbieder van services heeft inderdaad een admin panel waarin client IDs + secrets per client beheerd worden. Dat is niet zo heel erg anders dan de standaard OAUTH2 app die geregistreerd moet worden voordat je APIs kan gebruiken (zoals de grote spelers zoals Microsoft, Github, Google... dat ook doen).

> Op basis van bovenstaande zou ik adviseren om de anti-corruption layer pattern te implementeren in jullie Zaken systeem. In jullie Zaken systeem definieer je eigen URIs (met UUIDs) voor externe resources. Requests naar deze URIs worden onderschept en getransformeerd naar requests voor de externe APIs. Omgekeerd kunnen de responses van de externe APIs worden omgezet in responses die door de clients kan worden verwerkt. Hiermee wordt de logica om te kunnen koppelen met een externe API op één plek gerealiseerd in plaats van bij al de clients.

Dit gaat volgens mij dwars in tegen het idee van gegevens bij de bron. De Zaken API is niet de bronhouder van deze gevens. Daarnaast is er geen gestandaardiseerde manier om deze gegevens uit te wisselen/endpoints aan te roepen, wat vendor lock op een bepaald "zaaksysteem" (dit is een ouderwetse  en incorrecte term in de Common Ground visie) promoot.

**Comment by sergei-maertens** [comment]
Wat betekent het sluiten van deze vraag? Hebben jullie ergens gedocumenteerd hoe je met dit soort vraagstukken dient om te gaan?

**Comment by CathyDingemanse** [comment]
https://github.com/orgs/BRP-API/projects/2?pane=issue&itemId=69129078
