### ISSUE TITLE
Maak alle properties binnen datum componenten required

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1379]
In regl 337 van het 'fields.feature' staat:

`Rule: Wanneer een specifiek veld van een datum wordt gevraagd, dan worden velden die bij dat datumtype required zijn ook geleverd`

Als 'fields' dus bijv. de waarde 'datumEersteInschrijvingGBA.datum' heeft moeten alle required velden van 'datumEersteInschrijvingGBA' worden geleverd. In geval van een volledigedatum dus naast 'datumEersteInschrijvingGBA.datum' ook het veld 'datumEersteInschrijvingGBA.type'.

In het bestand '.../features/fields-mapping-Persoon.csv' wordt echter de volgende mapping beschreven:

| fields pad | volledig pad |
| -- | -- |
| ... | ... |
| datumEersteInschrijvingGBA.datum | datumEersteInschrijvingGBA |
| ... | ... |

Wat conflicteert met de genoemde rule aangezien je volgens deze mapping niet alleen de required velden maar juist alle velden van 'datumEersteInschrijvingGBA' moet leveren. Om de rule en het mapping bestand weer met elkaar in overeenstemming te brengen moet het mapping bestand worden aangepast wat niet eenvoudig lijkt. Voorstel is daarom om alle properties van de volgende OAS componenten:

* VolledigeDatum
* DatumOnbekend
* JaarDatum
* JaarMaandDatum

required te maken.

**Comment by CathyDingemanse** [comment]
Zullen we dit even bespreken in de dagstart van morgen?

**Comment by fsamwel** [comment]
alle velden (ook langFormaat) moeten required worden in alle typen voor datum

@melsk-r voert dit door
