### ISSUE TITLE
Response van de GBA API mist partner property in de persoon.

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1382]
De Response van het scenario `met fields is gevraagd om <fields>` in 'informatievragen-fields-gba.feature' (regels 97 t/m 103) mist de 'partner' property in de persoon.

In het resultaat van het 6e voorbeeld (regel 102) van dit scenario missen daarnaast de properties:
* voornamen 
* voorvoegsel
* geslachtsnaam
* aanduidingnaamgebruik 
 
van de gevraagde persoon.

**Comment by fsamwel** [comment]
feature bestaat niet meer
