### ISSUE TITLE
Response van de GBA API bevat een verblijfplaats met te weinig gegevens

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1383]
De responses van de voorbeelden in de regels 203, 229, 279, 281, 282, 283, 284 en 286
 in 'informatievragen-fields-gba.feature' bevatten minder gegevens in 'verblijfplaats' dan verwacht.

In de responses van de voorbeelden in de regels 204, 206, 230, 232, 285, 288, 329, 330, 332, 353, 452 en 487 is 'verblijfplaats' zelfs helemaal leeg.

**Comment by fsamwel** [comment]
feature bestaat niet meer
