### ISSUE TITLE
Response van de GBA API bevat te veel gegevens in 'immigratie'

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1384]
De Response van het scenario `met fields is gevraagd om indicatieVestigingVanuitBuitenland` in 'informatievragen-fields-gba.feature' (regel 389) levert binnen 'immigratie' onterecht een 'landVanwaarIngeschreven'.

**Comment by fsamwel** [comment]
als ik vraag om immigratie.indicatieVestigingVanuitBuitenland levert de gba API nu zowel datumVestigingInNederland als landVanwaarIngeschreven.

Dit was in v1.3 alleen datumVestigingInNederland. Hebben we hier iets bewust aan gewijzigd? Er is zo te zien nog geen feature die deze situatie beschrijft

**Comment by fsamwel** [comment]
in #1591 scenario's toegevoegd om dit te testen

**Comment by KayodeBakker** [comment]
@fsamwel De wijzigingen van jouw PR kan ik draaien en worden groen. Ik laat deze issue nog open aangezien dit rondom informatievragen-fields-gba.feature is. Deze kan ik nog steeds niet draaien omdat het nog bijgewerkt moet worden.

**Comment by KayodeBakker** [comment]
@fsamwel Wil jij nog iets hiermee want anders sluit ik de issue.
