### ISSUE TITLE
Fields waarde is onterecht niet toegestaan

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1387]
De fields waarden:
* verblijfadres.straat (280)
* verblijfadres.land (287)
* datumEersteInschrijvingGBA (549 t/m 554)
* datumInschrijvingInGemeente (555 t/m 560)
* geboorte.datum.type (577)
* immigratie.datumVestigingInNederland.datum (578)
* europeesKiesrecht.einddatumUitsluiting.jaar (579)
* uitsluitingKiesrecht.einddatum.maand (580)
* opschortingBijhouding.datum.langFormaat (581)
* overlijden.datum.onbekend (582)
* verblijfstitel.datumEinde.langFormaat (583)
* verblijfstitel.datumIngang.datum (584)

zijn volgens de GBA API response niet toegestaan.

**Comment by fsamwel** [comment]
Gecheckt met actuele lijst mogelijke fields paden die toegestaan zouden moeten worden. De volgende paden geven een fields foutmelding "Parameter bevat een niet bestaande veldnaam.". Zie bijlage met fields die fouten geven
[fields-fouten.txt](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/files/10580538/fields-fouten.txt)

**Comment by KayodeBakker** [comment]
@fsamwel @CathyDingemanse Zal ik deze maar negeren aangezien informatievragen-gba wordt uitgekleed?

**Comment by KayodeBakker** [comment]
@fsamwel Ik bedoel negeren omdat informatievragen-gba niet meer zal bestaan binnenkort. Ik kan niet weten of de scenarios falen door fouten in de feature of aan mijn code. Als dit probleem overgenomen wordt naar een nieuwe feature/scenario dan zal die daar weer kapot gaan en dan zal het een nieuwe issue zijn.

**Comment by fsamwel** [comment]
betekent dat de complete lijst van mogelijke fields waarden in fields-gba features moeten worden overgenomen.

**Comment by fsamwel** [comment]
maar dit issue heeft denk ik niks te maken met informatievragen-gba. Het gaat om alle mogelijke fields, zoals die in https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/blob/develop/features/fields-Persoon.csv voorkomen

**Comment by KayodeBakker** [comment]
@fsamwel Dus wat doen we nu met deze issue? Ik zie geen reden meer om deze open te houden. Als je wel reden ziet dan stel ik voor dat je deze alsnog sluit en een nieuwe aanmaakt want ik weet niet waar we het nu nog over hebben als er iets nog niet klopt.

**Comment by fsamwel** [comment]
kan worden gesloten. zit allemaal in features
