### ISSUE TITLE
Scenario fouten rni-gba.feature

### ISSUE THREAD

**Issue by KayodeBakker** [BRP-API/Haal-Centraal-BRP-bevragen#1405]
**Beschrijf de bug**
Bij het uitvoeren van regel 138 van gba-dev feature rni-gba dan is er een foutieve verwachting en tevens ook weer een impliciete verwachting die niet eerder is gemeld.

Allereerst de foutieve verwachting:

```json
[
   {
     "burgerservicenummer": "000000061",
     "geheimhoudingPersoonsgegevens": "true",
     "rni": [
       {
         "deelnemer": {
           "code": "0101",
           "omschrijving": "Belastingdienst (inzake heffingen en toeslagen)"
         },
         "omschrijvingVerdrag": "Belastingverdrag tussen België en Nederland",
         "categorie": "Inschrijving"
       }
     ]
   }
 ]
```
Hierboven wordt verwacht dat geheimhoudingPersoonsgegevens de waarde true heeft, maar dat is een brpproxy verwachting en niet een gba api verwachting. Hier hoort "geheimhoudingPersoonsgegevens": "7" terug en dit klopt ook.

Daarnaast wordt er ook verwacht dat bij geheimhoudingPersoonsgegevens altijd de RNI wordt geretourneerd, echter is dit weer logica dat aan een API wordt gevraagd dat alleen maar data hoeft te retourneren. Het lastige hier is het stukje 
wel leveren RNI-deelnemer categorie 7 **wanneer er geheimhouding is**. Wordt hier bedoeld wanneer er geheimhouding is waar de waarde **niet** 0 is? Het is nu niet expliciet genoeg.

Daarnaast zijn er ook anderen:
Op regel 103 staat een scenario beschreven waar de fields 'naam.voornamen,verblijfplaats.verblijfadres.postcode' zijn. Volgens eerdere afspraken zou in het geval van een gevraagde object zoals verblijfplaats welke geen data heeft dan een lege verblijfplaats worden getoond.

Nu is de verwachting:
```json
{
   "naam": {
     "voornamen": "Peter"
   }
 }
```

terwijl het eigenlijk als volgt hoort te zijn:

```json
{
   "naam": {
     "voornamen": "Peter"
   }
  "verblijfplaats": {}
 }
```

**Comment by JohanBoer** [comment]
- Waarde voor geheimhoudingPersoonsgegevens op 7 gezet. Scenario faalt nog steeds (geen inhoud in response).
- Ik heb "wanneer er geheimhouding is"  vernaderd naar "wanneer de indicatie geheim niet 0 is. 
- Ik heb de lege verblijfplaats toegevoegd aan de verwachting. 

Ik bied zo een PR aan en zal naar deze issue verwijzen.

**Comment by JohanBoer** [comment]
GBA-scenario's falen nog. 

npx cucumber-js features/gba-dev/rni-gba.feature:23
npx cucumber-js features/gba-dev/rni-gba.feature:46
npx cucumber-js features/gba-dev/rni-gba.feature:138
npx cucumber-js features/gba-dev/rni-gba.feature:192

Naar mijn beste weten kloppen de scenario's nu. Als je daar vragen over hebt hoor ik dat graag

**Comment by KayodeBakker** [comment]
De gehele RNI feature in gba-dev lijkt nu te werken. Ik heb getest op versie 2.0.14.

**Comment by KayodeBakker** [comment]
@JohanBoer 
Ik zie nu bij
_"Wel leveren RNI-deelnemer voor een categorie waarvan een gegeven door de proxy wordt gebruikt om een type te bepalen # features\gba-dev\rni-gba.feature:116"_
weer wat verkeerd gaan. De verwachting is hier het krijgen van een verblijfplaats met een land waar alleen code gevuld is (5010), maar ik lever ook een omschrijving aan namelijk België. Dit wordt als fout gezien. Ik zou zeggen dat de scenario dan fout is, maar wat denk jij?
