### ISSUE TITLE
Op 'in onderzoek.xlsx' aan te brengen correcties

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1407]
Vraagje over 'in onderzoek.xlsx' waarvoor ik in de volgende image even alleen de voor de vraag relevante regels en kolommen van tabblad '8 verblijfplaats' toon. 

(![image](https://user-images.githubusercontent.com/20185784/200275087-a74358bf-14b3-49ce-8891-8bf5fcecdf52.png)

Het gaat me met name om de cellen met de gele achtergrond, allen betrekking hebbende op velden voor buitenlands adres.

Waarom zouden, als 'aanduidingGegevensInOnderzoek' de waarde '081100' (Adres) of '081200' (Locatie) heeft, 'regel1' en/of 'regel2' ook in onderzoek moeten staan? Die hebben toch niets van doen met een binnenlands adres of locatie? Mij lijkt het een foutje in het spreadsheet maar misschien is er wel een hele goede reden die ik nu niet ken.

**Comment by MelvLee** [comment]
> Vraagje over 'in onderzoek.xlsx' waarvoor ik in de volgende image even alleen de voor de vraag relevante regels en kolommen van tabblad '8 verblijfplaats' toon.
> 
> (![image](https://user-images.githubusercontent.com/20185784/200275087-a74358bf-14b3-49ce-8891-8bf5fcecdf52.png)
> 
> Het gaat me met name om de cellen met de gele achtergrond, allen betrekking hebbende op velden voor buitenlands adres.
> 
> Waarom zouden, als 'aanduidingGegevensInOnderzoek' de waarde '081100' (Adres) of '081200' (Locatie) heeft, 'regel1' en/of 'regel2' ook in onderzoek moeten staan? Die hebben toch niets van doen met een binnenlands adres of locatie? Mij lijkt het een foutje in het spreadsheet maar misschien is er wel een hele goede reden die ik nu niet ken.

Dit is al aangegeven in #1497
