### ISSUE TITLE
Waarom moet het mogelijk zijn om alleen de datumIngangOnderzoek te kunnen opvragen met fields?

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1418]
Er zijn volgens mij nu 2 situaties die elkaar tegen spreken

```
  Scenario: 'burgerservicenummer (01.20)' is in onderzoek, maar wordt niet gevraagd
    Gegeven de persoon met burgerservicenummer '000000152' heeft de volgende gegevens
    | naam                            | waarde   |
    | aanduiding in onderzoek (83.10) | 010120   |
    | datum ingang onderzoek (83.20)  | 20020701 |
    Als personen wordt gezocht met de volgende parameters
    | naam                | waarde                          |
    | type                | RaadpleegMetBurgerservicenummer |
    | burgerservicenummer | 000000152                       |
    | fields              | geslacht                        |
    Dan heeft de response een persoon zonder gegevens
```
BrpProxy vult de fields aan tot 'geslacht,inOnderzoek.geslacht,inOnderzoek.datumIngangOnderzoekPersoon' om als geslacht in onderzoek staat dit terug te kunnen geven. Omdat geslacht niet in onderzoek is en inOnderzoek.burgerservicenummer wordt weggefilterd is geen enkel inOnderzoek veld gevuld en wordt datumInOnderzoekPersoon daarom niet geretourneerd.

```
  Scenario: 'burgerservicenummer (01.20)' is in onderzoek, maar alleen inOnderzoek.datumIngangOnderzoekPersoon gevraagd
    Gegeven de persoon met burgerservicenummer '000000152' heeft de volgende gegevens
    | naam                            | waarde   |
    | aanduiding in onderzoek (83.10) | 010120   |
    | datum ingang onderzoek (83.20)  | 20020701 |
    Als personen wordt gezocht met de volgende parameters
    | naam                | waarde                          |
    | type                | RaadpleegMetBurgerservicenummer |
    | burgerservicenummer | 000000152                       |
    | fields              | inOnderzoek.datumIngangOnderzoekPersoon |
    Dan heeft de response een persoon met de volgende 'inOnderzoek' gegevens
    | naam                                    | waarde        |
    | datumIngangOnderzoekPersoon.type        | <type>        |
    | datumIngangOnderzoekPersoon.datum       | <datum>       |
    | datumIngangOnderzoekPersoon.jaar        | <jaar>        |
    | datumIngangOnderzoekPersoon.maand       | <maand>       |
    | datumIngangOnderzoekPersoon.onbekend    | <onbekend>    |
    | datumIngangOnderzoekPersoon.langFormaat | <langFormaat> |
```
BrpProxy hoeft fields niet aan te vullen. Nu worden alle inOnderzoek velden weggefilterd, maar moet datumInOnderzoek wel worden geretourneerd.

Beide scenario's hebben hetzelfde eindsituatie voordat wordt gekeken of inOnderzoek moet worden geretourneerd. Voordat ik ga proberen een oplossing te bedenken, wil ik zeker weten dat dit gewenste functionaliteit is. En of het niet beter is om fields=inOnderzoek.datumIngangOnderzoekPersoon te mappen naar fields=inOnderzoek. Maw gaat iemand ooit alleen een inOnderzoek datum zonder te hoeven weten wat dan in onderzoek is

Side note 1. Ik zie dat in fields-mapping-gba.csv dat inOnderzoek.datumIngangOnderzoekPersoon wordt gemapt naar persoonInOnderzoek.datumIngangOnderzoek. Dit kan niet worden gehonoreerd omdat zowel aanduidingGegevensInOnderzoek en datumIngangOnderzoek required velden zijn van GbaInOnderzoek
Side note 2. Even los van vorige side note: In fields-mapping-gba.csv wordt bijv. geboorte.inOnderzoek.datum gemapt naar persoonInOnderzoek en geboorte.inOnderzoek.datumIngangInOnderzoek wordt gemapt naar persoonInOnderzoek.datumIngangInOnderzoek. Wat is dan de redenering om geboorte.inOnderzoek.datum te mappen naar persoonInOnderzoek en niet naar persoonInOnderzoek.aanduidingGegevensInOnderzoek?

**Comment by melsk-r** [comment]
De eerste side note begrijp ik niet.

> Ik zie dat in fields-mapping-gba.csv dat inOnderzoek.datumIngangOnderzoekPersoon wordt gemapt naar persoonInOnderzoek.datumIngangOnderzoek. Dit kan niet worden gehonoreerd omdat zowel aanduidingGegevensInOnderzoek en datumIngangOnderzoek required velden zijn van GbaInOnderzoek

waarom kan dat niet gehonoreerd worden? Is het trouwens niet juist zo dat de mapping juist net andersom werkt? Je mapt 'persoonInOnderzoek.datumIngangOnderzoek' op 'inOnderzoek.datumIngangOnderzoekPersoon' en niet 'inOnderzoek.datumIngangOnderzoekPersoon' op 'persoonInOnderzoek.datumIngangOnderzoek'.

> Side note 2. Even los van vorige side note: In fields-mapping-gba.csv wordt bijv. geboorte.inOnderzoek.datum gemapt naar persoonInOnderzoek en geboorte.inOnderzoek.datumIngangInOnderzoek wordt gemapt naar persoonInOnderzoek.datumIngangInOnderzoek. Wat is dan de redenering om geboorte.inOnderzoek.datum te mappen naar persoonInOnderzoek en niet naar persoonInOnderzoek.aanduidingGegevensInOnderzoek?

Dit lijkt me inderdaad een foutje in het csv bestand.

**Comment by melsk-r** [comment]
> Omdat beide gba in onderzoek velden required zijn. Je kan wel alleen om de datum vragen, maar beide moet worden terug gegeven

Die begrijp ik maar ik zou zeggen dat het csv bestand dat niet in de weg staat, dat beperkt zich slechts tot dat waar het voor in het leven is geroepen, bepalen welke velden op welke velden gemapt moeten worden.

**Comment by MelvLee** [comment]
> > Omdat beide gba in onderzoek velden required zijn. Je kan wel alleen om de datum vragen, maar beide moet worden terug gegeven
> 
> Die begrijp ik maar ik zou zeggen dat het csv bestand dat niet in de weg staat, dat beperkt zich slechts tot dat waar het voor in het leven is geroepen, bepalen welke velden op welke velden gemapt moeten worden.

Dit begrijp ik niet. Zegt je dus dat als een request wordt gestuurd naar de GBA API met als fields de waarde links van de komma, dat de GBA API meer velden mag terug geven dan wat er rechts van de komma staat?
