### ISSUE TITLE
Buitelandse plaats of coördinaten worden niet in de omschrijving geplaats

### ISSUE THREAD

**Issue by JohanBoer** [BRP-API/Haal-Centraal-BRP-bevragen#1421]
Als er voor geboorteplaats, overlijdenplaats of plaats sluiting huwelijk/partnerschap sprake is van een buitenlandse plaats of coördinaten dan wordt dit opgenomen in de code van de plaats in de database. 

In deze situatie moet echter zoWel de plaats.code als de plaats.omschrijving gevuld worden met de waarde die opgehaald wordt van de database. 

**To Reproduce**
npx cucumber-js features/gba-dev/waardetabel-gba.feature:221
npx cucumber-js features/gba-dev/waardetabel-gba.feature:235
npx cucumber-js features/gba-dev/waardetabel-gba.feature:250

**Comment by KayodeBakker** [comment]
Deze slagen nu naar mijn zien. Ervaar jij dit ook? Ik heb dit getest op versie 2.0.14.
