### ISSUE TITLE
Wat is het gewenste gedrag voor zoeken met tabel waarden?

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1437]
Voorbeeld: zoek met geslachtsnaam, voorvoegsel (=tabel waarde) en geboortedatum. Voorvoegsel 'van' komt in twee vormen voor in 'lo3_voorvoegsel': 'van' en 'Van'. Voor case insensitive zoeken zou je verwachten dat bijv. 'VAN' ook mogelijk moet zijn.

**Comment by CathyDingemanse** [comment]
Als je met VAN zoekt zou je zowel "van" als "Van" terug moeten krijgen. En geen foutmelding. Ook vAn em vaN zou beide tabelwaarden moeten teruggeven.
