### ISSUE TITLE
Wat moeten proxy en gba API doen wanneer in fields een gba veld gevraagd is?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1438]
Bijvoorbeeld "fields": ["verblijfplaats.naamOpenbareRuimte", "verblijfplaats.regel1"]

Moet dat dan geleverd worden door de gba API en vervolgens eruit gefilterd door de proxy? Of een foutmelding geven?

In dat geval wordt er wel (in ieder geval aan RvIG kant) geprotocolleerd dat het betreffende veld geleverd is, maar krijgt de gebruiker achter de proxy het veld niet.

De GBA API werkt nu onvoorspelbaar op dit punt. Vraag je alleen een gba veld dat een waarde heeft, dan krijg je het. Vraag je dat veld plus een veld zonder waarde, krijg je een leeg object.

```
{
  "fields": ["verblijfplaats.naamOpenbareRuimte", "verblijfplaats.regel1"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999993653"]
}
```

geeft:
```
{
    "personen": [
        {
            "verblijfplaats": {}
        }
    ],
    "type": "RaadpleegMetBurgerservicenummer"
}
```

maar:
```
{
  "fields": ["verblijfplaats.naamOpenbareRuimte"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999993653"]
}
```

geeft:
```
{
    "personen": [
        {
            "verblijfplaats": {
                "naamOpenbareRuimte": "Boterdiep"
            }
        }
    ],
    "type": "RaadpleegMetBurgerservicenummer"
}
```

**Comment by fsamwel** [comment]
Getest op proxy. Die geeft een foutmelding wanneer je vraagt om een gba veld.

**Comment by JohanBoer** [comment]
> Getest op proxy. Die geeft een foutmelding wanneer je vraagt om een gba veld.

En dat is toch terecht? Als het gevraagde gba-veld niet voorkomt in de fields.csv moet er een parameter-fout gegeven worden. 
@fsamwel: kan dit issue dan gesloten worden ?

**Comment by KayodeBakker** [comment]
@JohanBoer @fsamwel Is dit nog relevant?
