### ISSUE TITLE
Polymorfie en informatievragen geven foutmelding wanneer gebruiker niet voor alle bronvelden geautoriseerd is

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1441]
In LO BRP staat dat een foutmelding moet worden gegeven wanneer een gegeven gevraagd wordt waar men niet voor geautoriseerd is. Dit kan vervelend uitwerken wanneer iemand voor een deel van die gegevens wel en een ander deel niet geautoriseerd is.

Dit kan zowel op niveau van de autorisaties van de ambtenaar als op niveau van de afnemer spelen.

**nationaliteiten**
Wanneer je iets vraagt van een nationaliteit, halen we daarbij (ook) zowel nationaliteit als aanduiding bijzonder Nederlanderschap op, om type te bepalen.

Bijvoorbeeld afnemer [Tabel35_880101_07](https://publicaties.rvig.nl/dsresource?objectid=a4afb640-ad34-4a94-bb70-66b86a2646fe&type=pdf) is wel geautoriseerd voor nationaliteit, maar niet voor aanduiding bijzonder Nederlanderschap.

Wanneer deze afnemer de API aanroept met fields=["nationaliteiten.nationaliteit"], zal de API bij RvIG dit volgens [fields-mapping-gba.feature](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/features/gba-dev/fields-mapping-gba.feature) vertalen naar fields=["nationaliteiten.nationaliteit", "nationaliteiten.aanduidingBijzonderNederlanderschap"].
De API bij RvIG zal vervolgens een foutmelding geven, omdat de afnemer niet geautoriseerd is voor nationaliteiten.aanduidingBijzonderNederlanderschap.

**verblijfplaats**
Wanneer je iets vraagt van de verblijfplaats, halen we daarbij (ook) alle gegevens uit groep 11 (adres), 12 (locatie) en 13 (verblijfadres buitenland) op, dus alle velden van verblijfadres, om het type te bepalen.

In de autorisaties van een gemeente zie ik dat sommige afnemers niet geautoriseerd zijn voor groep 13 (verblijfadres buitenland), of alleen voor land en datum vertrek, niet voor de adresregels.

Wanneer dus een gebruiker zonder autorisatie voor verblijfadres buitenland de API aanroept met bijvoorbeeld fields=["verblijfplaats.functieAdres"], dan wordt dit vertaald naar fields met o.a. ook straat, huisnummer, enz., en land, regel1, regel2, enz. De API bij RvIG zal vervolgens een foutmelding geven, omdat de afnemer niet geautoriseerd is voor land en regel1.
De gebruiker kan daardoor niets van de verblijfplaats vragen, ook geen gegevens waarvoor deze wel geautoriseerd is, ook wanneer de gevraagde persoon een Nederlands adres heeft (alleen gegevens relevant blijken waarvoor gebruiker wel geautoriseerd is).

**datumVan**
Veld verblijfplaats.datumVan wordt gevuld uit óf datumAanvangAdreshouding, óf datumAanvangAdresBuitenland. 

In de autorisaties van een gemeente zie ik dat sommige afnemers wel geautoriseerd zijn voor datumAanvangAdreshouding  én voor verblijfadres buitenland (land, regel1, regel2, regel3), maar niet voor datumAanvangAdresBuitenland. Dus wanneer een gebruiker zonder autorisatie voor datumAanvangAdresBuitenland  de API aanroept met fields=["verblijfplaats.datumVan"], wordt dat vertaald naar fields=["verblijfplaats. datumAanvangAdreshouding", "verblijfplaats. datumAanvangAdresBuitenland", {plus alle velden van verblijfadres, zie vorige punt}]. De API bij RvIG zal vervolgens een foutmelding geven, omdat de afnemer niet geautoriseerd is voor datumAanvangAdresBuitenland.
De gebruiker kan daardoor niet om datumVan vragen, ook niet wanneer de gevraagde persoon een Nederlands adres heeft en dus alleen datumAanvangAdreshouding (waarvoor de gebruiker wel geautoriseerd is).

**adressering.adresregel1 enz.**
De adresregel velden in adressering worden samengesteld uit alle velden van verblijfadres.

In de autorisaties van een gemeente zie ik dat sommige afnemers niet geautoriseerd zijn voor groep 13 (verblijfadres buitenland), of alleen voor land en datum vertrek, niet voor de adresregels.

Een afnemer met die autorisatie kan dan geen adressering adresregels krijgen, want vragen daarom wordt in de API vertaald naar het vragen om alle verblijfadres velden inclusief adresregels buitenland. Deze gebruiker krijgt dan een foutmelding op autorisatie, ook wanneer de gevraagde persoon een adres in Nederland heeft. Dit geldt ook voor de response bij zoeken, waarin alleen de adresregels zitten en geen lossen adresvelden.

Hoe gaan we hiermee om?

1. voor de afnemer (bij RvIG) of gebruiker (bij afnemer) uitbreiden autorisaties, zodat dit probleem wordt opgelost
2. geen foutmelding geven bij vragen om meer dan waarvoor geautoriseerd en alleen leveren waarvoor wel geautoriseerd

Ad 1. 
* voor de Gaba autorisaties (van afnemer bij RvIG) is onduidelijk wat de reden is voor de beperkte autorisatie. kan uitgezocht worden.

* voor interne autorisaties is onduidelijk waarom sommige afnemers bijvoorbeeld geen buitenlands adres mogen krijgen en wel een Nederlands adres. Wanneer daar wel een goede reden voor is, is de API mogelijk niet goed ontworpen.

Ad 2. 
* onduidelijk of RvIG dit accepteert  

* wat lever je wanneer je het type niet kan bepalen omdat alleen niet-geautoriseerde gegevens een waarde hebben?
Nationaliteit gevraagd en persoon heeft aanduiding bijzonder Nederlanderschap. De gba API levert dan `"nationaliteiten": [{}]`.
Wat wordt het type? Of wordt dan heel de nationaliteit niet geleverd (leeg object mag niet wat type is required)? Dus `"nationaliteiten": []`?

* complexiteit van en mogelijkheden voor intern autoriseren worden beperkt voor afnemers/deelnemers
Bijvoorbeeld niet mogelijk om in interne autorisaties gebaseerd op resource model aan te geven dat gebruiker van adresregels wel Nederlands en niet buitenlands adres mag ontvangen. Of verblijfplaats datumVan wel van Nederlands adres, maar niet van buitenlands adres mag ontvangen. Of verblijfplaats wel type=Adres, maar niet type=VerblijfplaatsBuitenland mag ontvangen.

**Comment by MelvLee** [comment]
We hebben volgens mij ooit aangegeven dat als een consumer adressering gegevens of leeftijd wordt gevraagd, dat de consumer **binnen die context** respectievelijk geautoriseerd is om naam gegevens van partner, verblijfplaats gegevens en geboortedatum en datumoverlijden te vragen. Klopt dit nog? Als dit nog klopt, moet dus nog nieuwe autorisaties worden gespecificeerd voor de informatie velden.

Verder staan we nu toe om fields paden voor volledige paden te gebruiken. Bijv. verblijfadres voor verblijfplaats.verblijfadres.
Dit zou je ook kunnen doortrekken voor autorisatie. verblijfadresBinnenland als je alleen de verblijfadres gegevens wilt hebben van een binnenlands verblijfplaats of verblijfadresBuitenland voor verblijfadres gegevens van een buitenlands verblijfadres, conform de component namen zoals gespecificeerd in verblijfplaats.yaml. Hetzelfde kan ook worden gedaan voor nationaliteiten: nationaliteitBekend,behandeldAlsNederlander, enz.

En als je geautoriseerd bent om meerdere type verblijfplaatsen te mogen bevragen, bijv. adressen en locaties en je wilt ze beide hebben, dan kan dat als volgt: fields=adres,locatie of fields=verblijfadresBinnenland,verblijfadresLocatie als je alleen de verblijfadres gegevens wilt hebben van adressen en locaties

Geeft je als consumer fields=verblijfplaats, dan wil je dus van alle type verblijfplaatsen de velden hebben. Volgens mij kan hierdoor de autorisatie vooraf worden gedaan ipv achteraf nadat de gegevens al zijn bevraagd.

**Comment by fsamwel** [comment]
@MelvLee begrijp ik het zo goed?:
Als ik alleen verblijfplaats.datumIngangGeldigheid wil hebben, en ik ben niet geautoriseerd voor verblijfplaatsBuitenland of verblijfplaatsOnbekend, dat ik moet vragen fields=["verblijfplaats.datumIngangGeldigheid", "verblijfadresBinnenland", "verblijfadresLocatie"]?
De GbaPersoon levert dan datumIngangGeldigheid, plus de binnenlandse adresvelden (straat, huisnr. enz.) of locatie, maar niet land en regels. De proxy levert voor een binnenlands adres of locatie verblijfplaats met alleen type en datumIngangGeldigheid.
Wanneer de gevraagde persoon een buitenlans adres heeft wordt (door de proxy) verblijfplaats helemaal niet geleverd (ook geen datumIngangGeldigheid en geen leeg object)

En voor nationaliteit als ik nationaliteit vraag en niet geautoriseerd ben voor bijzonder Nederlanderschap, gebruik ik fields=["nationaliteiten.nationaliteit", "nationaliteitBekend"]. Voor een persoon met nationaliteit levert GbaPersoon dan de nationaliteit en de proxy levert type en nationaliteit. Voor een persoon met bijzonderNederlanderschap levert GbaPersoon een nationaliteit als leeg object, en levert de proxy nationaliteiten als lege array.

Werkt het zo?

Ik vind het wel een beetje verwarrend dat je voor verblijfplaats "verblijfadresBinnenland" enz. gebruikt. Dat verwijst niet naar de schemacomponent die je wilt kunnen ontvangen (dat is voor verblijfadresBinnenland dan "Adres"), maar naar de responsecomponent in de proxy die je misschien niet wilt ontvangen.

Het werkt ook wat verwarrend dat hier het toevoegen van een extra pad in fields het aantal te leveren velden vanuit een ander pad beperkt moet worden: toevoegen van "nationaliteitBekend" zorgt dat bij "nationaliteit" niet ook "bijzonbderNederlanderschap" wordt meegeleverd. Of had je dat niet zo bedoeld?

**Comment by MelvLee** [comment]
> @MelvLee begrijp ik het zo goed?: Als ik alleen verblijfplaats.datumIngangGeldigheid wil hebben, en ik ben niet geautoriseerd voor verblijfplaatsBuitenland of verblijfplaatsOnbekend, dat ik moet vragen fields=["verblijfplaats.datumIngangGeldigheid", "verblijfadresBinnenland", "verblijfadresLocatie"]?
Het moet worden fields=["adres.datumIngangGeldigheid","locatie.datumIngangGeldigheid","verblijfadresBinnenland","verblijfadresLocatie"]. VerblijfplaatsBuitenland heeft ook een datumIngangGeldigheid veld. 

> De GbaPersoon levert dan datumIngangGeldigheid, plus de binnenlandse adresvelden (straat, huisnr. enz.) of locatie, maar niet land en regels.
Klopt

> De proxy levert voor een binnenlands adres of locatie verblijfplaats met alleen type en datumIngangGeldigheid. Wanneer de gevraagde persoon een buitenlans adres heeft wordt (door de proxy) verblijfplaats helemaal niet geleverd (ook geen datumIngangGeldigheid en geen leeg object)
Dit hangt af van wat de GBA API levert. Als deze geen leeg object geeft kan deze ook niet door de proxy worden doorgegeven. Ik zou geen leeg object leveren als een consumer niet geautoriseerd is voor verblijfplaats buitenland. Want dan kan de consumer dat wel afleiden.

> 
> En voor nationaliteit als ik nationaliteit vraag en niet geautoriseerd ben voor bijzonder Nederlanderschap, gebruik ik fields=["nationaliteiten.nationaliteit", "nationaliteitBekend"].
Alleen NationaliteitBekend heeft een nationaliteit veld, dus ik denk dat fields moet zijn ["nationaliteitBekend"] of ["nationaliteiten.nationaliteitBekend"]. En als alleen nationaliteit veld word gevraagd dan moet fields gelijk zijn aan ["nationaliteitBekend.nationaliteit"] of ["nationaliteiten.nationaliteitBekend.nationaliteit"]

> Voor een persoon met nationaliteit levert GbaPersoon dan de nationaliteit en de proxy levert type en nationaliteit. Voor een persoon met bijzonderNederlanderschap levert GbaPersoon een nationaliteit als leeg object, en levert de proxy nationaliteiten als lege array.

De GBA moet bijzonderNedelandschap niet als leeg object retourneren, want de proxy kan hiermee niet concluderen of de consumer niet geautoriseerd is of dat de persoon de gevraagde velden niet heeft.

> 
> Werkt het zo?
> 
> Ik vind het wel een beetje verwarrend dat je voor verblijfplaats "verblijfadresBinnenland" enz. gebruikt. Dat verwijst niet naar de schemacomponent die je wilt kunnen ontvangen (dat is voor verblijfadresBinnenland dan "Adres"), maar naar de responsecomponent in de proxy die je misschien niet wilt ontvangen.

Als je verblijfplaats buitenland wil dan vraag je dat met fields=["verblijfplaatsBuitenland"]. Als je verblijfadres wil van een verblijfplaats buitenland, dan kan dat met fields=["verblijfplaatsBuitenland.verblijfadres"]. Als er hiervoor een verkorte fields pad moet worden gedefinieerd, dan moet dat helaas fields=["verblijfadresBuitenland"] worden.

> 
> Het werkt ook wat verwarrend dat hier het toevoegen van een extra pad in fields het aantal te leveren velden vanuit een ander pad beperkt moet worden: toevoegen van "nationaliteitBekend" zorgt dat bij "nationaliteit" niet ook "bijzonbderNederlanderschap" wordt meegeleverd. Of had je dat niet zo bedoeld?

Nee, zo heb ik het niet bedoeld. Een consumer die geautoriseerd is voor bijzonder nederlanderschap kan al voldoen met fields=["nationaliteiten"]. Is hij niet geautoriseerd voor bijzonder nederlanderschap, maar wel voor de andere soorten nationaliteiten en hij wil die ook hebben, dan moet hij dat doen met fields=["nationaliteitBekend","staatloos","nationaliteitOnbekend"]
