### ISSUE TITLE
Als medewerker van de gemeente wil ik uitsluitend die vervblijfplaats gegevens kunnen vragen die ik mag ontvangen

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#1449]
...zodat ik uitsluitend het verblijfsadres en de adresregels 1,2,3 ontvang waarvoor ik doelbinding heb.

**Acceptatiecriteria**
- Ik wil de mogelijkheid krijgen expliciet en uitputtend die gegevens te vragen die ik mag ontvangen
- Ik wil de mogelijkheid krijgen adresgegevens als groep op te vragen, zonder de "datum van" of  "ingangsdatum geldigheid".
- ik wil de de "datum van" en  "ingangsdatum geldigheid" expliciet apart kunnen opvragen.

Gegeven:
- ik ben geautoriseerd voor verblijfplaats binnenland, locatie, onbekendAdres en verblijfplaats buitenland
- ik ben wel geautoriseerd voor verblijfplaats binnenland, locatie niet geautoriseerd voor verblijfplaats buitenland en onbekendAdres

- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
Afspraak 1: we introduceren een alias voor:

 adressering binnenland
- adresseringBinnenland.adresregel 1

en verblijfplaats binnenland voor het type adres en locatie
- verblijfplaatsBinnenland.verblijfsadres
- verblijfplaatsBinnenland.Datumvan

Afspraak 2: we geven een foutmelding als een afnemer vraagt om gegevens waarvoor hij niet is geautoriseerd.

**Comment by MelvLee** [comment]
afspraak 5 is eigenlijk geen onderdeel van het autorisatie issue en de bijbehorende fields alias oplossing

**Comment by MelvLee** [comment]
zie: #1451

**Comment by fsamwel** [comment]
> Afspraak 4: AdresOnkend wordt uitsluitend geleverd wanneer landcode = 0000

Hoe gaan we nu om met de volgende situatie (verblijfplaats feature regel 98)?
      En de persoon heeft de volgende 'verblijfplaats' gegevens

      | naam                                   | waarde                 |
      | land adres buitenland (13.10)          | 0000                   |
      | datum aanvang adres buitenland (13.20) | 00000000               |
      | regel 2 adres buitenland (13.40)       | Pietermaai 19, Curaçao |

Dit is geen geheel theoretische situatie, ik heb zulke gevallen gevonden in de RvIG database.

**Comment by MelvLee** [comment]
> > Afspraak 4: AdresOnkend wordt uitsluitend geleverd wanneer landcode = 0000
> 
> Hoe gaan we nu om met de volgende situatie (verblijfplaats feature regel 98)? En de persoon heeft de volgende 'verblijfplaats' gegevens
> 
> ```
>   | naam                                   | waarde                 |
>   | land adres buitenland (13.10)          | 0000                   |
>   | datum aanvang adres buitenland (13.20) | 00000000               |
>   | regel 2 adres buitenland (13.40)       | Pietermaai 19, Curaçao |
> ```
> 
> Dit is geen geheel theoretische situatie, ik heb zulke gevallen gevonden in de RvIG database.
> 
> Of verandert afspraak 4 hier niks aan, vervalt daarbij alleen het kijken naar standaardwaarden in het adres (groep 11)?

Je kan je afvragen of het een fout is of luiheid dat de element 13.10 niet is gevuld, want in element 13.40 staat wel een land. Code technisch kan het land wel uit element 13.40 worden geparst (complex), en dan de code op te gaan zoeken (case insensitive en diakrietloos om bijv. ook curacao, CURAÇAO, curaçao te kunnen vinden) in de land code tabel (complex), maar is het de effort waard

**Comment by fsamwel** [comment]
> > Afspraak 4: AdresOnkend wordt uitsluitend geleverd wanneer landcode = 0000
> 
> Hoe gaan we nu om met de volgende situatie (verblijfplaats feature regel 98)? En de persoon heeft de volgende 'verblijfplaats' gegevens
> 
> ```
>   | naam                                   | waarde                 |
>   | land adres buitenland (13.10)          | 0000                   |
>   | datum aanvang adres buitenland (13.20) | 00000000               |
>   | regel 2 adres buitenland (13.40)       | Pietermaai 19, Curaçao |
> ```
> 
> Dit is geen geheel theoretische situatie, ik heb zulke gevallen gevonden in de RvIG database.
> 
> Of verandert afspraak 4 hier niks aan, vervalt daarbij alleen het kijken naar standaardwaarden in het adres (groep 11)?

Ik heb dit nagevraagd bij RvIG (Frans) en het blijkt toch niet voor te komen (geldt zowel voor verblijf buitenland zonder landcode als Nederlands adres zonder straat:
_Dit soort overtredingen van de gegevensstructuur worden inderdaad maandelijks gecontroleerd door de bestandscontrolemodule en gerapporteerd aan de betreffende gemeente.
Maar ook bij een intergemeentelijke verhuizing moet de ontvangende gemeente de persoonslijst controleren op de minimumvereisten. Als verplichte rubrieken ontbreken, moet de persoonslijst geweigerd worden met een Pf03-bericht (pagina 394-395 LO BRP 4.1).
Dus je kunt er gevoeglijk vanuit gaan dat hier geen of nauwelijks afwijkingen op zijn._

Bovenstaande vraag kunnen we dus verder negeren en VerblijfplaatsOnbekend kan op alleen landcode=0000 bepaald worden.
