### ISSUE TITLE
De response van de Proxy API is incorrect n.a.v. het bevragen van een locatie.

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1464]
Het gaat om het abstracte scenario '&lt;component in onderzoek> van de categorie verblijfplaats is in onderzoek' in de branch 'e2e-automation-inOnderzoek.

In de response van de Proxy geldt binnen verblijfplaats
* dat de waarde van type ten onrechte 'Adres' is, dit moet 'Locatie' zijn.
  _Komt waarschijnlijk omdat woonplaats in de response van de GBA API voorkomt. Kan dat veroorzaakt worden doordat 'gemeentecode (92.10)' gevuld is?_
* dat inOnderzoek mist met de property type met de waarde true.
* dat binnen verblijfadres ten onrechte woonplaats voorkomt
  _Zie eerdere opmerking._
* dat binnen verblijfadres ten onrechte locatiebeschrijving en inOnderzoek niet voorkomt

**Comment by MelvLee** [comment]
Wat is de reden dat gemeente van inschrijving is toegevoegd aan de scenario? Zou er een verschil moeten zijn in resultaat als het wel/niet in de scenario voorkomt?

De gba api mapt gemeente van inschrijving naar woonplaats omdat woonplaats (11.70) geen waarde heeft (adres.feature rule op regel 100). Omdat woonplaats nu is gevuld, wordt dit verblijfplaats gezien als een Adres (verblijfplaats.feature rule op regel 6 + scenario op regel 11)

Is het mappen van gemeente van inschrijving naar woonplaats niet een taak van de proxy en had dit niet moeten gebeuren voor alleen het bepalen voor adresregel2 (adres.feature rule op regel 100)?

#1465 is in principe een duplicaat

**Comment by melsk-r** [comment]
> Wat is de reden dat gemeente van inschrijving is toegevoegd aan de scenario? Zou er een verschil moeten zijn in resultaat als het wel/niet in de scenario voorkomt?

Waarschijnlijk omdat ik in de veronderstelling was dat dit veld verplicht was in de database maar dat geldt waarschijnlijk juist voor gemeentecode (92.10).
 
> De gba api mapt gemeente van inschrijving naar woonplaats omdat woonplaats (11.70) geen waarde heeft (adres.feature rule op regel 100). Omdat woonplaats nu is gevuld, wordt dit verblijfplaats gezien als een Adres (verblijfplaats.feature rule op regel 6 + scenario op regel 11)
> 
> Is het mappen van gemeente van inschrijving naar woonplaats niet een taak van de proxy en had dit niet moeten gebeuren voor alleen het bepalen voor adresregel2 (adres.feature rule op regel 100)?

Volgens mij heb je gelijk.

> #1465 is in principe een duplicaat

Niet helemaal want voor het daarin genoemde speelt alleen dat daar het type onterecht 'Adres' is. Maar de oorzaak is mogelijk wel hetzelfde als hier.
