### ISSUE TITLE
Als berichtonwikkelaar wil ik weten welke onderdelen van het LO-GBA opgenomen worden in deze bevragingen API. 

### ISSUE THREAD

**Issue by JohanBoer** [BRP-API/Haal-Centraal-BRP-bevragen#147]
...zodat ik de API-specificatie op kan stellen en kan verifieren of die compleet is.
[Onderhanden wijzigingen n.a.v. LO GBA.docx](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2807139/Onderhanden.wijzigingen.n.a.v.LO.GBA.docx)

**Definition of done**
- [x] Analyse opstellen van verschil tussen huidige API-spec en LO-GBA
- [x] Beslissingen van productowner per punt van de Analyse
- [ ] Genomen beslissingen doorvoeren in de API-spec

**Comment by CathyDingemanse** [comment]
Hierbij mijn antwoorden 
[Onderhanden.wijzigingen.n.a.v.LO.GBA COMMENTAAR CD.docx](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2807383/Onderhanden.wijzigingen.n.a.v.LO.GBA.COMMENTAAR.CD.docx)

**Comment by JohanBoer** [comment]
GertJan: 2)	Als er nog nieuwe GBA-rubrieken aan het model worden toegevoegd die een datum betreffen, voor deze datumvelden controleren of deze (deels) onbekend kunnen zijn

**Comment by gertjanvanderkooij** [comment]
Bijgaand mijn review op document.
[Onderhanden.wijzigingen.n.a.v.LO.GBA.COMMENTAARCD_ReaGKJ.docx](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2879307/Onderhanden.wijzigingen.n.a.v.LO.GBA.COMMENTAARCD_ReaGKJ.docx)

**Comment by CathyDingemanse** [comment]
Hierbij mijn reactie.
[Onderhanden.wijzigingen.n.a.v.LO.GBA.COMMENTAARCD_ReaGKJ_PO.docx](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/files/2915522/Onderhanden.wijzigingen.n.a.v.LO.GBA.COMMENTAARCD_ReaGKJ_PO.docx)

**Comment by JohanBoer** [comment]
@CathyDingemanse  Frank constateert dat conform bovenstaand document het element "indicatie onjuist" (84.10) zou moeten worden opgenomen in de verblijfplaats. 
Ik meen mij te kunnen herinneren dat we die indicatie niet op zouden nemen, maarkan daar nergens documentatie over vinden. 
Wel hebben we gedocumenteerd dat bij de partner, ouder en kind de indicatie onjuist niet opgenomen wordt. 

Wil jij uitsluitsel geven of indicatie onjuist in de verblijfplaats moet worden op[genomen ?

**Comment by fsamwel** [comment]
> @CathyDingemanse Frank constateert dat conform bovenstaand document het element "indicatie onjuist" (84.10) zou moeten worden opgenomen in de verblijfplaats.

Er zit nu ook een inconsistentie tussen de API specificatie, waar in Verblijfplaats _geen_ indicatieOnjuist is opgenomen, en de feature indicatie onjuist, waarin staat "Alleen voor de categorie 08.58 Verblijfplaats wordt de indicatie onjuist opgenomen."

**Comment by CathyDingemanse** [comment]
@JohanBoer @fsamwel 
We hebben idd afgespreken dat we niets opnemen met een indicatie onjuist. Dat geldt dus ook voor een Verblijfplaats met indicatie onjuist.

**Comment by gertjanvanderkooij** [comment]
Heb ik op zich geen probleem mee; eerder is hierover gemeld dat SocialeZaken hier specifieke behoefte aan had (zie reactie Cathy op 28-2 j.l op mijn review 'OnderhandenWijzigingennavLOGBA' hierboven):

_"Voor Categorie 08/58 is ‘Indicatie onjuist’ nu als ‘Graag opnemen’ aangegeven; eerder is een besluit genomen om de categorieën met de indicatie ‘onjuist’ in z’n geheel niet te leveren. Draaien we dit nu terug? Dan alleen voor adres of geldt ook hier dit aspect generiek te behandelen?"_
 
_"IS EEN FUNCTIONELE WENS VAN SOCIALE ZAKEN (UITKERINGSFRAUDE). GELDT NIET VOOR ANDERE CATEGORIEEN. DEZE KUNNEN WE ER ALTIJD NOG BIJ LEVEREN ALS EEN AFNEMER MET DEZE BEHOEFTE ZICH MELDT."_

**Comment by CathyDingemanse** [comment]
Tjonge, het is maar goed dat er nog iemand oplet! Thnx Gert-Jan! Deze dus wel opnemen.

**Comment by fsamwel** [comment]
Is het voor gebruikers dan niet logischer hiervoor een eigen endpoint te maken, of het in (historische) bewoning op te nemen? Anders moet elke consumer bij een adres eerst checken of het onjuist is. Wanneer de developer (van iets anders dan sociale zaken) dat "vergeet" wordt mogelijk een onjuist adres gebruikt.

**Comment by JohanBoer** [comment]
Prio laag, maar de content moet wel gedocumenteerd worden in de design decisions. Taak voor Johan
