### ISSUE TITLE
Missen we niet een feature die beschrijft dat de gba-api alleen actuele gegevens levert?

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1490]
Volgens mij wordt impliciet van uit gegaan dat als een categorie wordt gevraagd die historie ondersteund, dat alleen gegevens uit de database rij met volg_nr 0 wordt geleverd.

Verder zou naar mijn mening alle scenario's die te maken hebben met wijzigingen en correcties in deze feature file terecht moeten komen om bovenstaande rule te illustreren. Deze scenario's zijn niet relevant als end to end test en volgens mij ook niet interessant/relevant voor consumers

**Comment by KayodeBakker** [comment]
Voor mij als persoon dat de API implementeert, is dit een open deur. Echter het is alleen een open deur omdat ik al jaren bekend ben met dit soort onderwerpen. Als ik een compleet nieuw iemand met nul achtergrond in dit onderwerp erop zou zetten om de specificaties te implementeren, dan zal deze niet rekening houden met volg_nr == 0. In die zin lijkt het me zeker nuttig als documentatie.
