### ISSUE TITLE
Straat vullen uit straatnaam of openbare ruimte naam?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1493]
In v1.3 werd straat gevuld uit openbare ruimtenaam wanneer die een waarde heeft, anders uit straat.

In feature [Adres](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/features/adres.feature) staat dit nog:
`Rule: Voor een binnenlands adres wordt veld "straat" gevuld met de naam openbare ruimte (11.15) wanneer die bekend is, en anders met straatnaam (11.10). Veld "korteNaam" wordt gevuld met straatnaam (11.10).`

In de features onder bevragen/persoon/verblijfplaats vind ik dat niet meer terug.

Ik dacht dat we dit ook niet meer zouden doen, net als dat we woonplaats niet meer vullen uit gemeenteVanInschrijving. verblijfadres is immers alleen bedoeld voor legacy.

Is hier ook een beslissing over genomen?

**Comment by MelvLee** [comment]
Voor fields straat en korteNaam zijn de volgende 2 scenario's gespecificeerd:
- https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/features/bevragen/persoon/verblijfplaats/adres/verblijfadres/fields.feature#L72
- https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/features/bevragen/persoon/verblijfplaats/adres/verblijfadres/fields.feature#L94

Wat betreft de woonplaats, ik dacht dat die alleen gold bij het samenstellen van adresregel2. Zie mijn opmerking in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/1464

**Comment by fsamwel** [comment]
in dit feature, regels 72 en 94 staat dus inderdaad dat met straat alleen openbare ruimtenaam wordt gevraagd. Wanneer die leeg is, wordt straat niet geleverd. Dat was in de "oude" adres.feature dus nog niet zo. Vandaar mijn vraag of dit een expliciete beslissing is.

**Comment by fsamwel** [comment]
de vraag is dus, wanneer straatnaam een waarde heeft en naam openbare ruimte ontbreekt, lever je dan bij fields=verblijfplaats.verblijfadres.straat ook de waarde uit straatnaam

**Comment by fsamwel** [comment]
deze (adres.feature) en andere features doornemen of er nog verblijfplaats scenario's in zitten of rules die op verblijfplaats betrekking kunnen hebben.

Afgesproken dat @JohanBoer  dit doet

**Comment by MelvLee** [comment]
> de vraag is dus, wanneer straatnaam een waarde heeft en naam openbare ruimte ontbreekt, lever je dan bij fields=verblijfplaats.verblijfadres.straat ook de waarde uit straatnaam

Ik weet niet of je dit moet doen. Ik denk dat als of straatnaam of naam openbare ruimte in onderzoek staat en fields=verblijfplaats.verblijfadres.straat dat dit tot verwarring/verkeerde conclusie kan leiden bij een consumer. Zie onderstaande scenario's:

```

  Scenario: 'naam openbare ruimte' heeft geen waarde en is in onderzoek, en wordt gevraagd
    Gegeven de persoon met burgerservicenummer '000000152' heeft de volgende 'verblijfplaats' gegevens
    | naam                            | waarde   |
    | aanduiding in onderzoek (83.10) | 081115   |
    | datum ingang onderzoek (83.20)  | 20020701 |
    En de 'verblijfplaats' heeft de volgende 'adres' gegevens
    | naam                 | waarde |
    | gemeentecode (92.10) | 0519   |
    | straatnaam (11.10)   | Spui   |
    Als personen wordt gezocht met de volgende parameters
    | naam                | waarde                              |
    | type                | RaadpleegMetBurgerservicenummer     |
    | burgerservicenummer | 000000152                           |
    | fields              | verblijfplaats.verblijfadres.straat |
    Dan heeft de response een persoon met de volgende 'verblijfplaats' gegevens
    | naam                                                       | waarde      |
    | type                                                       | Adres       |
    | verblijfadres.straat                                       | Spui        |
    | verblijfadres.inOnderzoek.straat                           | true        |
    | verblijfadres.inOnderzoek.datumIngangOnderzoek.type        | Datum       |
    | verblijfadres.inOnderzoek.datumIngangOnderzoek.datum       | 2002-07-01  |
    | verblijfadres.inOnderzoek.datumIngangOnderzoek.langFormaat | 1 juli 2002 |
    # is dit correct? Geen waarde van naam openbare ruimte kan de reden van in onderzoek zijn en nu lijkt of de waarde Spui in onderzoek is

  Scenario: 'straatnaam' heeft standaardwaarde, is in onderzoek en wordt niet gevraagd. naam openbare ruimte heeft een waarde en wordt gevraagd
    Gegeven de persoon met burgerservicenummer '000000152' heeft de volgende 'verblijfplaats' gegevens
    | naam                            | waarde   |
    | aanduiding in onderzoek (83.10) | 081110   |
    | datum ingang onderzoek (83.20)  | 20020701 |
    En de 'verblijfplaats' heeft de volgende 'adres' gegevens
    | naam                         | waarde |
    | gemeentecode (92.10)         | 0519   |
    | straatnaam (11.10)           | .      |
    | naam openbare ruimte (11.15) | Spui   |
    Als personen wordt gezocht met de volgende parameters
    | naam                | waarde                              |
    | type                | RaadpleegMetBurgerservicenummer     |
    | burgerservicenummer | 000000152                           |
    | fields              | verblijfplaats.verblijfadres.straat |
    Dan heeft de response een persoon met de volgende 'verblijfplaats' gegevens
    | naam                                                       | waarde      |
    | type                                                       | Adres       |
    | inOnderzoek.type                                           | true        |
    | inOnderzoek.datumIngangOnderzoek.type                      | Datum       |
    | inOnderzoek.datumIngangOnderzoek.datum                     | 2002-07-01  |
    | inOnderzoek.datumIngangOnderzoek.langFormaat               | 1 juli 2002 |
    | verblijfadres.straat                                       | Spui        |
    | verblijfadres.inOnderzoek.straat                           | true        |
    | verblijfadres.inOnderzoek.datumIngangOnderzoek.type        | Datum       |
    | verblijfadres.inOnderzoek.datumIngangOnderzoek.datum       | 2002-07-01  |
    | verblijfadres.inOnderzoek.datumIngangOnderzoek.langFormaat | 1 juli 2002 |
    # omdat straatnaam in onderzoek is, is naam openbare ruimte ook in onderzoek (uit xls sheet). Is dit correct?
```

**Comment by JohanBoer** [comment]
Vanmorgen tijdens de bespreking dit besluit expliciet gemaakt : 

- De property verblijfplaats.verblijfadres.straat wordt alleen gevuld met de waarde van verblijfplaats.naamOpenbareRuimte (uit de GBA-API). Als deze ontbreekt of leeg is wordt verblijfplaats.verblijfadres.straat niet geleverd.  Dit geldt ook voor verblijfplaatsBinnenland.verblijfadres.straat 
- De property verblijfplaats.verblijfadres.korteNaam wordt alleen gevuld met de waarde van verblijfplaats.straat (uit de GBA-API). Als die ontbreekt of leeg is wordt verblijfplaats.verblijfadres.korteNaam niet geleverd. Dit geldt ook voor verblijfsplaatsBinnenland.verblijfadres.korteNaam.
- De functionaliteit dat een er altijd een waarde in de straat geleverd zou moeten worden is inmiddels overgeheveld naar adressering. In adressering.adresregel1 wordt dus in principe verblijfplaats.straat gebruikt, maar als die leeg is wordt |verblijfplaats.naamOpenbareRuimte gebruikt om adressering.adresregel1 op te stellen. Dit geldt ook voor adresseringBinnenland.adresregel1

Vanwege deze beslissing zijn de volgende wijzigingen doorgevoerd: 
- In fields-mapping.csv een aanpassing gedaan op regel 56 en 75. Daar is de verblijfplaats.straat niet meer nodig als met fields verblijfplaats.verbijfadres.straat gevraagd wordt. 
- In fields-mapping.csv is op regel 7 en op regel 19 verblijfplaats.naamOpenbareRuimte toegevoegd
- Bij adres.feature is de Rule op regel 6 verwijderd en is het eerste scenario (_opnemen straat en korteNaam bij een binnenlands adres_) verwijderd. 
Er is nu geen "special" bij het vullen van de straatnaam. Dit vullen is in de fields.feature beschreven,

**Comment by fsamwel** [comment]
> De functionaliteit dat een er altijd een waarde in de straat geleverd zou moeten worden is inmiddels overgeheveld naar adressering. In adressering.adresregel1 wordt dus in principe verblijfplaats.straat gebruikt, maar als die leeg is wordt |verblijfplaats.naamOpenbareRuimte gebruikt om adressering.adresregel1 op te stellen. Dit geldt ook voor adresseringBinnenland.adresregel1

Dit is naam mijn mening een overbodige regel. Kan niet voorkomen. Komt het toch voor dan is het foute data en kan je m.i. beter helemaal geen adresregel opstellen.

Gelukkig is @JohanBoer in P.R. #1505 vergeten dit door te voeren. En is de stelling "is inmiddels overgeheveld" niet waar, althans niet in de adres feature. Ik zou dat dus zo laten.

**Comment by fsamwel** [comment]
voor de duidelijkheid: in adresregel1 gebruiken we altijd straatnaam (korteNaam) en nooit naamOpenbareRuimte, omdat de openbare ruimtenaam heel lang kan zijn en dan niet meer in een adresvenster past.

**Comment by fsamwel** [comment]
zie verder de discussie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/1505#issuecomment-1352927583 en https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/1505#issuecomment-1352942873

Oorspronkelijk hebben we straat en korteNaam geïntroduceerd in plaats van naamOpenbareRuimte en straat, vanuit de gedachte dat een gebruiker het begrip straat kent en veel minder vaak weet wat bedoeld wordt met naamOpenbareRuimte (het vereist BAG kennis om dat te begrijpen). En de beste waarde, de officiële straatnaam zit in naamOpenbareRuimte. Maar naamOpenbareRuimte heeft niet altijd een waarde, namelijk wanneer het geen BAG adres is en er dus geen officiële straatnaam bepaald/vastgelegd is.

Daarna hebben we adresregels bedacht. 
Daarmee is verblijfadres verworden tot iets voor legacy (afnemers bijvoorbeeld die nog zelf de adresregels willen samenstellen). Voor hen is de huidige indeling erg verwarrend. Wanneer ze in hun bestaande applicatie het veld straat gebruiken, is de fout erg snel gemaakt om ook uit de API het veld straat te gebruiken. Maar dat is dan fout, omdat daar openbareRuimteNaam in zit.

**Comment by JohanBoer** [comment]
Inmiddels is dit onderwerp uitgebreid aan bod gekomen in een dagstart en is daar een tweetal Pull Requests voor gemaakt. (#1508  en #1509 ).
