### ISSUE TITLE
hoe melden unauthorized op parameter?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1494]
Volgens de API specificaties kent de response bij status code 403 geen invalidParams. Bij het valideren tegen autorisatie kan de conclusie zijn dat een parameter is gebruikt waarvoor men niet geautoriseerd is, of met fields een veld gevraagd is waar men niet voor geautoriseerd is.

In [fields-alias-fout-cases.feature](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/features/bevragen/persoon/verblijfplaats/fields-alias-fout-cases.feature) bijvoorbeeld wordt er wel een invalidParams verwacht bij statuscode 403. Die verwachting is dus in strijd met de specificaties.

Hoe lossen we dit op?
- geen invalidParams leveren bij 403
- wel invalidParams, dus specificaties aanpassen

**Comment by CathyDingemanse** [comment]
@fsamwel wat is het alternatief?

**Comment by MelvLee** [comment]
>     * geen invalidParams leveren bij 403

Het wordt deze, conform jouw autorisatie p.r.
