### ISSUE TITLE
zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving uitbreiden met zoeken op diacrieten

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1495]
bij zoeken op straatnaam kan de straat in 4 verschillende kolommen van de lo3_adres tabel gezocht moeten worden.

Bijvoorbeeld een lange straatnaam met diakriet erin heeft de volgende waarden in de tabel
| tabel kolom | waarde |
|-- |-- |
| straat_naam | Henriette Roland Holstln |
| diak_straat_naam | Henriëtte Roland Holstln |
| open_ruimte_naam | Henriette Roland Holstlaan |
| diak_open_ruimte_naam | Henriëtte Roland Holstlaan |

We moeten dit adres (dus de personen die daar wonen) vinden met invoer van al die 4 varianten. Dat is nu niet gespecificeerd in de feature in een rule. En daarvoor zijn er nog geen scenario's in de feature. Voorheen in de wildcard feature stond dit wel uitgelegd (maar uiteraard niet in een testautomatiseerbare vorm).

Ik vraag me ook af of de automatisering dit ondersteunt (opgeven van een straat of openbare ruimte met diakriet).

**Comment by CathyDingemanse** [comment]
Scenario's kunnen conform voorbeeld worden toegevoegd. Het heeft wat mij betreft niet een hoge prioriteit. Diakrietloos zoeken is prima om mee van start te gaan.
