### ISSUE TITLE
Valt datum aanvang adres buitenland onder adres buitenland groep?

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1515]
Zie in_onderzoek.xls tab verblijfplaats regel 23. Dit is niet in overeenstemming met hele groep adres (regel 10) en hele groep locatie (regel 21)

**Comment by melsk-r** [comment]
Mij lijkt deze vorm meer correct:

![image](https://user-images.githubusercontent.com/20185784/208706925-ac570dd8-e45d-45d7-a7c8-6e7faee65da4.png)

Cellen met een gele achtergrond zijn gewijzigd.
Grijze 'X' betekent verwijderen.
Rode 'X' toevoegen.

**Comment by melsk-r** [comment]
Zie ook issue #1317.

**Comment by melsk-r** [comment]
Alle bovenstaande wijzigingen moeten worden doorgevoerd behalve de twee rode kruisjes onder datumVan.
