### ISSUE TITLE
vragen van adresregels1,2 en/of 3

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1524]
In features/adres.feature regel 139 staat dat er voor een buitenlands adres alleen adresregels wordt geleverd als tenminste land en één regel een waarde hebben. Echter in de fields-mapping-gba.csv staat dat als adressering.adresregel1 wordt gevraagd dat alleen verblijfplaats.regel1 wordt geleverd. Als verblijfplaats.land niet wordt geleverd kan deze rule niet worden geïmplementeerd.

Soortgelijks wordt ook gespecificeerd voor binnenlands adres. Hiervoor mag alleen adresregels worden geleverd als tenminste straatnaam en huisnummer een waarde hebben (regel 178). Als nu alleen adressering.adresregel2 wordt gevraagd moet volgens de fields-mapping-gba.csv alleen postcode, woonplaats en gemeentevaninschrijving worden geleverd. Als straat en huisnummer niet wordt geleverd kan deze rule niet worden geïmplementeerd.

Welke is niet correct? De rules of de mapping?

**Comment by CathyDingemanse** [comment]
Op basis van de mailwisseling van Frans Rijkers van 15-2-2022 concludeer ik dat de csv onjuist is. 
De proxy moet tenminste het land en alle regels terugkrijgen. Pas dan kan de rule worden geimplementeerd dat tnminste het land en één regel een waarde moet hebben.

**Comment by CathyDingemanse** [comment]
Voor het binnenlands adres geldt hetzelfde. De csv moet worden aangepast. De proxy moet sowieso straatnaam en huisnummer terugkrijgen.
