### ISSUE TITLE
Wijzigingen noodzakelijk in features na verkorte fields verwijdering

### ISSUE THREAD

**Issue by KayodeBakker** [BRP-API/Haal-Centraal-BRP-bevragen#1525]
De volgende scenarios falen nu omdat deze een verkorte field verwachten:

- features\gba-dev\bag-identificatie.feature:33
- features\gba-dev\bag-identificatie.feature:34
- features\gba-dev\bag-identificatie.feature:35
- features\gba-dev\bag-identificatie.feature:37
- features\gba-dev\immigratie.feature:62
- features\gba-dev\waardetabel-gba.feature:88
- features\dev\immigratie.feature:42
- features\dev\persoonbeperkt-verblijfplaats-binnenland.feature:5
- features\immigratie.feature:22
- features\immigratie.feature:23
- features\immigratie.feature:24
- features\immigratie.feature:25
- features\immigratie.feature:29
- features\immigratie.feature:42
- features\waardetabel.feature:105
- features\dev\verblijfplaats-onbekend.feature:23
- features\dev\verblijfplaats-onbekend.feature:25
- features\dev\verblijfplaats-onbekend.feature:26

Graag deze bijstellen zodat dit resultaat niet meer plaatsvindt.
**Let op.**  Ik heb nog niet gekeken naar alle features onder de features\bevragen folder met uitzondering van de GBA features.

**Comment by JohanBoer** [comment]
De volgende scenarios falen nu omdat deze een verkorte field verwachten:

features\gba-dev\bag-identificatie.feature:33 --> opgelost
features\gba-dev\bag-identificatie.feature:34 --> opgelost
features\gba-dev\bag-identificatie.feature:35 --> opgelost
features\gba-dev\bag-identificatie.feature:37 --> opgelost
features\gba-dev\immigratie.feature:62   --> opgelost
features\gba-dev\waardetabel-gba.feature:88  --> opgelost
features\dev\immigratie.feature:42 --> opgelost 
features\dev\persoonbeperkt-verblijfplaats-binnenland.feature:5 --> aangepast. Fields is goed. Scenario faalt nog. 
features\immigratie.feature:22  --> opgelost
features\immigratie.feature:23  --> opgelost
features\immigratie.feature:24  --> opgelost
features\immigratie.feature:25  --> opgelost
features\immigratie.feature:29   --> opgelost
features\immigratie.feature:42   --> opgelost
features\in_onderzoek.feature:1096 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1097 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1098 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1099 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1100 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1101 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1102 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1103 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1104 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1105 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1106 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\in_onderzoek.feature:1107 --> scenario is correct. Implementatie adressering.datuminonderzoek ontbreekt
features\waardetabel.feature:105 --> Scenario herstelt. Faalt nog steeds.
Graag deze bijstellen zodat dit resultaat niet meer plaatsvindt.
Let op. Ik heb nog niet gekeken naar alle features onder de features\bevragen folder met uitzondering van de GBA features.
