### ISSUE TITLE
Missende proxy field in fields-mapping-gba.csv

### ISSUE THREAD

**Issue by KayodeBakker** [BRP-API/Haal-Centraal-BRP-bevragen#1526]
De volgende field is niet opgenomen in de fields-mapping-gba.csv:

- verblijfplaats.verblijfadres.inOnderzoek.

Graag dit opnemen.

**Comment by JohanBoer** [comment]
Volgenbs mij hebben we afgesproken dat "inOnderzoek" niet meer in de fields gevraagd mag worden. Het wordt genegeerd (er komt geen foutmelding op) Als er sprake is van inonderzoek, dan moet dit altijd meegeleverd worden. Volgens mij moet dit field dus NIET opgenomen worden in de fiels-mapping-gba.csv

**Comment by KayodeBakker** [comment]
Okay dat is nieuws voor mij want ik krijg bij de GBA API nu deze field als je kijkt naar de volgende scenario:
features\dev\verblijfplaats-binnenland-verblijfadres.feature:27
