### ISSUE TITLE
Insert fout bij scenario

### ISSUE THREAD

**Issue by KayodeBakker** [BRP-API/Haal-Centraal-BRP-bevragen#1529]
Bij de volgende scenarios is er een insert fout:

- features\dev\persoon-adressering-inonderzoek.feature:330
- features\dev\persoon-adressering-inonderzoek.feature:383

De foutmelding is ongeveer als volgt:
``` gherkin
...
error: column "inschrijving_gemeente_code" of relation "lo3_adres" does not exist
...
```

Graag de scenario bijstellen zodat deze fout niet meer plaatsvindt.

**Comment by JohanBoer** [comment]
Betreffende fout is verholpen, maar alle scenario's falen nu. Ik veronderstel dat dat is omdat adressering.inonderzoek nog niet is geimplementeerd.
