### ISSUE TITLE
Geen aanhef, aanschrijfwijze en gebruikinlopendetekst in onderzoek mapping bij partner in onderzoek in in_onderzoek.xls

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bevragen#1542]
Het zal ongeveer hetzelfde zijn als bij categorie persoon met als verschil dat aanhef, aanschrijfwijze en gebruikinlopendetekst niet in onderzoek zijn als voornamen, aanduiding naamgebruik of geslacht partner in onderzoek zijn. Klopt dit?

**Comment by CathyDingemanse** [comment]
aanhef, aanschrijfwijze en gebruikinlopendetekst  worden alleen beïnvloed door geslachtsnaam, adellijke titel, voorvoegsel. Jpouw aanname is correct.
