### ISSUE TITLE
Buitenlandse plaats wordt gezet in zowel code als omschrijving, alleen in omschrijving verwacht

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1543]
Bijvoorbeeld:
```
{
  "fields": ["geboorte.plaats"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999993653"]
}
```
levert:
```
            "geboorte": {
                "plaats": {
                    "code": "Thann",
                    "omschrijving": "Thann"
                }
            }
```

Deze buitenlandse plaatsnaam moet alleen in omschrijving gezet worden. De code moet immers een echte code in de landelijke tabel zijn, en dat is dit niet.

Zelfde speelt op alle plekken waar geboorte voorkomt (ouders, partners, kinderen), in overlijden, en ouders.aangaanHuwelijkPartnerschap.

**Comment by MelvLee** [comment]
@fsamwel , de specificaties hierover staan in waardetabel.feature (regel 256) en waardetabel-gba.feature (regel 216)

**Comment by KayodeBakker** [comment]
Dit zou moeten werken in versie 2.0.21.
