### ISSUE TITLE
Corrigeren urls in API specificaties

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1557]
Servers laten verwijzen naar:
1. lokale installatie
2. RvIG proefomgeving
3. RvIG productieomgeving

verwijderen verwijzing naar APILAB testserver

**Comment by CathyDingemanse** [comment]
Frank heeft dit gedaan voor de verblijfplaatshistorie. De rest moet ook.
