### ISSUE TITLE
Bij opschorting wordt datum wel meegeleverd in GbaPersoon

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1558]
Bij raadplegen wordt in geval van opschorting bijhouding naast de reden ook de datum meegeleverd.

Dat is niet de bedoeling, zie [fields.feature](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/blob/develop/features/fields.feature):
```
  Rule: Wanneer de bijhouding van een persoon is opgeschort en de reden hiervan is bekend, dan wordt dit bij elke vraag terug gegeven
    - wanneer er een reden opschorting bijhouding is, wordt deze reden geleverd, ook wanneer hier niet om gevraagd is
    - de datum opschorting bijhouding wordt alleen geleverd wanneer daarom gevraagd is met fields
```

N.B. bij zoeken (GbaPersoonBeperkt) wordt (terecht) alleen reden geleverd en wordt datum niet meegeleverd. Dat kan daar ook niet, omdat datum niet in de specificaties zijn opgenomen voor GbaPersoonBeperkt

**Comment by KayodeBakker** [comment]
Deze is ook in 2.0.21 aangepast.

**Comment by fsamwel** [comment]
opgelost
