### ISSUE TITLE
Hoe protocolleren we fields=ouders.ouderAanduiding?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1571]
ouders.ouderAanduiding wordt bepaald uit het bestaan van de categorie, hiervoor moet er ten minste 1 veld een waarde hebben van de ouder, maar dat kan in principe elk veld zijn.

Hoe protocolleren we dit?
- alsof alle velden van de persoon zijn gevraagd
- niet
- ...

**Comment by CathyDingemanse** [comment]
Ik vraag mij af: is het een persoonsgegeven? Als er om gevraagd wordt, wat zegt het gegeven dan? 
Ik stel voor om niets te protocolleren als ouders.ouderAanduiding wordt gevraagd.

**Comment by fsamwel** [comment]
oke, zo is het ook beschreven in de feature
