### ISSUE TITLE
Instance in foutbericht

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1573]
In een foutbericht wordt nu het volgende opgenomen (bij aanroepen op localhost: "instance": "https:///haalcentraal/api/brp/personen",

Dit is geen correcte url. het deel "https://" kan eruit

**Comment by KayodeBakker** [comment]
Dit is al aangepast in versie 2.0.21.

**Comment by fsamwel** [comment]
opgelost
