### ISSUE TITLE
Persoon niet geleverd die wel bestaat in de database

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1575]
```
{
  "fields": ["burgerservicenummer"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999993483"]
}
```
geeft:
```
{
    "personen": [],
    "type": "RaadpleegMetBurgerservicenummer"
}
```

Ik had hier wel een persoon verwacht, want ik kan die wel vinden in de database (pl_id=1039)

**Comment by KayodeBakker** [comment]
Dit probleem vindt niet plaats in de versie 2.0.21. Ik krijg zelf nu het volgende terug:

```json
{
    "personen": [
        {
            "burgerservicenummer": "999993483",
            "geheimhoudingPersoonsgegevens": 2,
            "opschortingBijhouding": {
                "datum": "20140702",
                "reden": {
                    "code": "E",
                    "omschrijving": "emigratie"
                }
            }
        }
    ],
    "type": "RaadpleegMetBurgerservicenummer"
}
```

**Comment by fsamwel** [comment]
@KayodeBakker ik draai nu versie 2.0.21 maar krijg de persoon niet.

Vreemd is dat wanneer ik de select query draai die in de logging is gezet, ik wel een resultaatrij krijg.

**Comment by fsamwel** [comment]
ik zie dit ook bij RvIG acceptatie, waar ik persoon in API met raadplegen op burgerservicenummer niet krijg, maar wel in GBA-V applicatie of directe query op de database

**Comment by KayodeBakker** [comment]
Kan je dit nogmaals testen met 2.0.23? Ik heb sinds 2.0.21 dit probleem niet meer gezien op het voorbeeld dat jij noemt. Ook op dit moment met 2.0.23 zie ik gewoon het resultaat dat ik eerder heb genoemd.

**Comment by fsamwel** [comment]
ik zie dit lokaal inderdaad niet meer
