### ISSUE TITLE
indicatieGezagMinderjarige wordt niet gehaald uit de tabel

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1584]
De omschrijving van indicatieGezagMinderjarige lijkt niet te worden gehaald uit de betreffende tabel (lo3_gezagsverhouding). De tekst in indicatieGezagMinderjarige.omschrijving staat wijkt af van wat in de tabel staat (ook al is het maar een hoofdletterverschil, het is een tabel die kan wijzigen).

N.B. Ook valt op dat tabel lo3_gezagsverhouding niet is meegenomen in de haal_centraal database.

**Comment by KayodeBakker** [comment]
Het is omdat de tabel niet is opgenomen, dat ik een verhaal methode heb staan. Als je wil dat ik iets aanpas hierover dan stel ik voor dat je of een scenario maakt die dit vertoont of een overzicht levert van wat de waarden moet zijn want ik weet nu niet welke omschrijving fout is en wat het moet worden.

**Comment by fsamwel** [comment]
Het is een tabel, omdat de omschrijvingen elk moment kunnen wijzigen en er elk moment nieuwe codes kunnen worden toegevoegd. Wanneer er een nieuwe code is toegevoegd aan de tabel (is al het geval in onze testdatabase, daar zit bijvoorbeeld code 2C in) en die wordt gebruikt bij een persoon, levert de API die nu niet. Het issue is dus nog wat groter dan hierboven beschreven, omdat zelfs de code niet doorkomt. Minimaal de code moet doorkomen, ook wanneer die niet voorkomt in de tabel.

hiervoor PR #1605 gemaakt die betreffende situatie(s) in scenario test

**Comment by KayodeBakker** [comment]
@fsamwel Deze is gefixt in 2.0.25. Kan je valideren dat het nu wel goed functioneert (In principe draaien de feature scenarios gewoon dus dat zou genoeg test moeten zijn.)
