### ISSUE TITLE
verblijfstitel met code 98 wordt wel geleverd door gba API

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1585]
In de verblijfstitel.feature staat `Rule: een verblijfstitel met aanduiding 98 "geen verblijfstitel (meer)" wordt niet opgenomen`

Deze regel komt niet terug in verblijfstitel/dev/verblijfstitel-gba.feature. Dus lijkt het nu dat de gba API dit wel moet leveren en de proxy het er weer uit moet filteren.

Ik denk dat het -voor data minimalisatie- beter is dat de gba API dit al niet levert.

@CathyDingemanse @MelvLee @KayodeBakker is er voor jullie een reden om dit in de proxy op te lossen?

@KayodeBakker De gba app lijkt nu trouwens wel de aanduiding=98 eruit te filteren, maar niet de rest van de verblijfstitel (begindatum en einddatum. Ik krijg dan bijvoorbeeld:
```
        {
            "burgerservicenummer": "999993367",
            "verblijfstitel": {
                "datumIngang": "20040520"
            }
        }
```

**Comment by CathyDingemanse** [comment]
@fsamwel nee, er geen reden om dit in de proxy op te lossen. Lijkt mij prima om het de gba API niet te laten leveren.

**Comment by KayodeBakker** [comment]
Is opgelost in 2.0.23.
