### ISSUE TITLE
bij actuele + ontbonden partner worden ten onrechte beide geleverd

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1586]
Bijvoorbeeld:
```
{
  "fields": ["partners"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999993926"]
}
```

Dit geeft nu meerdere partners, zowel een actuele, als twee ontbonden huwelijken.

zie features/bevragen/persoon/partner/overzicht.feature:
Rule: Als er een actueel huwelijk of geregistreerd partnerschap is wordt alleen dit actueel huwelijk of geregistreerd partnerschap geleverd

**Comment by fsamwel** [comment]
Zelfde geldt voor situatie dat er meerdere ontbonden relaties zijn (geen actuele). Dan moet alleen de laatst ontbonden partner getoond worden.

bijvoorbeeld
```
{
  "fields": ["partners"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999991905"]
}
```
Nu krijg ik twee partners, met ontbindingHuwelijkPartnerschap datum respectievelijk 19830328 en 20000103.
Ik verwacht nu alleen de partner met ontbindingHuwelijkPartnerschap  datum20000103.

**Comment by fsamwel** [comment]
N.B. de proxy lost dit op wanneer je ten minste "partners.ontbindingHuwelijkPartnerschap" vraagt. Alleen dan kan de proxy bepalen welke van de partners de juiste is. Vraag je dat niet, bijvoorbeeld alleen partners.naam, dan krijg je de actuele en alle ex-partners en kan je (de gebruiker) niet bepalen welke van die partners de juiste (actuele of laatste) is.

**Comment by KayodeBakker** [comment]
De issue die je noemt bij 999993926 en 999991905 zijn opgelost in 2.0.23.

> N.B. de proxy lost dit op wanneer je ten minste "partners.ontbindingHuwelijkPartnerschap" vraagt. Alleen dan kan de proxy bepalen welke van de partners de juiste is. Vraag je dat niet, bijvoorbeeld alleen partners.naam, dan krijg je de actuele en alle ex-partners en kan je (de gebruiker) niet bepalen welke van die partners de juiste (actuele of laatste) is.

Ik volg niet helemaal wat je hiermee bedoelt.

**Comment by fsamwel** [comment]
opgelost, maar vervangen door #1608 (niet de juiste partner wordt geleverd)
