### ISSUE TITLE
Reexecuted statuscode not handled: 403

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1601]
Bij een gebruiker (op RviG acceptatie, met beperkte autorisatie, geen gemeente) krijg ik bij elk request RaadpleegMetBurgerservicenummer, zelfs als fields=["burgerservicenummer"], de volgende foutmelding:

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/37143495/217285335-c6e4cda3-25b5-456d-b4e9-d3af14ab4989.png">

**Comment by KayodeBakker** [comment]
@fsamwel Kan je de bevraging aanleveren? Dit zou niet mogen gebeuren.

**Comment by fsamwel** [comment]
ik krijg die bijvoorbeeld bij onderstaand request (waar op zich niks bijzonders aan is):
<img width="775" alt="image" src="https://user-images.githubusercontent.com/37143495/217810944-ae34e805-b215-4ce6-a593-097f06ed15af.png">

Dit gebeurt alleen bij de gebruiker met afnemer code 990304. Deze heeft beperkte autorisaties op ad_hoc_rubrieken, verder zijn alle autorisatie instellingen identiek aan wat de andere afnemers hebben. Heb het niet lokaal kunnen reproduceren met dezelfde autorisatie instellingen (behalve natuurlijk de afnemer_code zelf) als deze gebruiker heeft.

**Comment by KayodeBakker** [comment]
@fsamwel Kan jij een insert statement aanleveren voor afnemer met code 990304? Ik heb deze niet en kan dit totaal niet nabootsen daardoor.

**Comment by fsamwel** [comment]
INSERT INTO public.lo3_autorisatie(
	autorisatie_id, afnemer_code, geheimhouding_ind, verstrekkings_beperking, afnemer_naam, adres_vraag_bevoegdheid, ad_hoc_medium, tabel_regel_start_datum, ad_hoc_rubrieken)
	VALUES ((SELECT max(autorisatie_id)+1 FROM public.lo3_autorisatie), 990304, 0, 0, 'Derde', 1, 'N', 20220101, '10110 10120 10210 10220 10230 10240 10310 10320 10330 10410 16110 18110 18120 18210 18220 18230 18510 18610 40510 50110 50120 50210 50220 50230 50240 50310 50610 50710 50740 58110 58120 58210 58230 58510 60810 77010 80910 81010 81020 81030 81110 81115 81120 81130 81140 81150 81160 81170 81180 81190 81210 81310 81320 81330 81340 81350 90110 90120 90210 90220 90230 90240 550610 55810 558120 558210 558220 558510 580910 581010 581020 581030 581110 581115 581120 581130 581140 581150 581160 581170 581180 581190 581210 581310 581320 581330 581340 581350');

**Comment by KayodeBakker** [comment]
@fsamwel Ik kan het hiermee en de bovenstaande request niet nabootsen. Ik weet wel waar de stuk code is dat de foutmelding levert, maar het probleem is dat een 403 daar nooit kan en mag komen. Ik heb er nu maar van gemaakt dat als er toch een 403 plaatsvindt, dat deze een standaard 403 foutmelding levert met code "authorization" en tekst "U bent niet geautoriseerd voor deze operatie.".

Verder weet ik niet wat ik hiermee kan doen.

**Comment by KayodeBakker** [comment]
@fsamwel Nog steeds kan ik deze niet nabootsen. Ik stel voor dat je er tijd aan spendeert om dit lokaal na te bootsen aangezien lokaal dit nooit voor lijkt te komen.
