### ISSUE TITLE
Overlijden leveren wanneer er geen overlijden is, maar alleen onderzoek?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1626]
Voor alle andere gegevens (zoals ouders, partners, kinderen, nationaliteit, verblijfstitel) hebben we een regel in de volgende vorm:
> Rule: Wanneer alleen gegevens in groep 81, 82, 83, 84, 85 en/of 86 zijn opgenomen en geen gegevens in groep <groepnummers met gewone gegevens>, dan wordt de <groep of relatie> niet opgenomen

Maar in /features/bevragen/persoon/overlijden/dev/fields-gba.feature hebben we een scenario:
```
Abstract Scenario: '<type>' van een overlijden is in onderzoek en één of meerdere velden wordt gevraagd met field pad '<fields>'
    Gegeven de persoon met burgerservicenummer '000000152' heeft de volgende 'overlijden' gegevens
    | naam                            | waarde                    |
    | aanduiding in onderzoek (83.10) | <aanduiding in onderzoek> |
    | datum ingang onderzoek (83.20)  | 20020701                  |
    Als gba personen wordt gezocht met de volgende parameters
    | naam                | waarde                          |
    | type                | RaadpleegMetBurgerservicenummer |
    | burgerservicenummer | 000000152                       |
    | fields              | <fields>                        |
    Dan heeft de response een persoon met de volgende 'overlijden' gegevens
    | naam                                      | waarde                    |
    | inOnderzoek.aanduidingGegevensInOnderzoek | <aanduiding in onderzoek> |
    | inOnderzoek.datumIngangOnderzoek          | 20020701                  |
```

@CathyDingemanse Hier wordt dus verwacht dat onderzoek geleverd wordt van overlijden, terwijl er geen overlijden is. Is dat terecht?
Moet dat dan ook gelden voor andere gegevens, zoals verblijfstitel, kiesrecht, enz.?

@gertjanvanderkooij @fransrijkers kan dat voorkomen, dat er onderzoek loopt op een categorie terwijl geen van de echte gegevens (groepnummer < 80) een waarde heeft?

**Comment by fransrijkers** [comment]
De procedure voor het in onderzoek zetten van een 'lege' categorie is niet beschreven in het LO BRP en ook niet in de HUP. Je zou daarmee kunnen zeggen, dat deze situatie niet kan/mag bestaan. Specifiek bij de categorie overlijden levert deze situatie een probleem op, omdat het onduidelijk is of de bijhouding van de persoonslijst moet worden opgeschort vanwege overlijden. Feitelijk is het niet mogelijk om de bijhouding op te schorten vanwege het ontbreken van een overlijdensdatum waarvan de opschortingsdatum wordt afgeleid.
Er is wel eens gedacht over de mogelijkheid om het in onderzoek zetten van een lege categorie expliciet toe te voegen, om kenbaar te maken dat er een officieel document in het dossier staat waaruit een gegeven blijkt dat niet kan worden opgenomen. Zoals een overlijdensakte van een niet-ingezetene die niet door een ABO kan worden aangemeld. Maar dat is nu nog geen mogelijkheid. En als dat ooit in het LO komt, dan zou het m.i. moeten gelden voor alle categorieën die in onderzoek gezet kunnen worden, en niet alleen voor overlijden.

**Comment by CathyDingemanse** [comment]
Gezien het antwoord van Frans stel ik voor om:

Rule: Wanneer alleen gegevens in groep 81, 82, 83, 84, 85 en/of 86 zijn opgenomen en geen gegevens in groep , dan wordt de niet opgenomen

voor alle categorieën te laten gelden.

**Comment by CathyDingemanse** [comment]
done
