### ISSUE TITLE
Bij sturen bericht met onjuiste encoding komt 500 server error

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1638]
gebruikt bijvoorbeeld de client cp1252 encoding dan wordt in de request body "Revés" geëncodeerd verstuurd als "Rev[0xe9]s"
Dit veroorzaakt 500 server error.

"Unable to translate bytes [39] at index 111 from specified codepage to Unicode."

**Comment by KayodeBakker** [comment]
@fsamwel Graag dat je een voorbeeld aanlevert + welke API versie want ik kan dit niet nabootsen en het is ook vrij cryptisch benoemd deze issue.

**Comment by fsamwel** [comment]
is inmiddels opgelost
