### ISSUE TITLE
toestaan toevoeging "charset=utf-8" aan content-type

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1639]
Wanneer ik een request naar de API stuur met Content-Type: application/json; charset=utf-8
dan krijg ik een 406:
```
{
   "type": "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.13",
   "title": "Media Type wordt niet ondersteund.",
   "status": 415,
   "detail": "Ondersteunde content type: */*, application/json. Default: application/json.",
   "instance": "/haalcentraal/api/brp/personen",
   "code": "unsupportedMediaType"
}
```

Dit is volgens mij een valide aanroep. Wij leveren toch in utf-8?

N.B. wanneer ik een andere toevoeging doe (Content-Type: application/json;charset=cp1252), krijg ik vreemd genoeg geen 415 foutmelding, maar wel pattern fouten op de parameters met diacrieten.  Althans wanneer ik dit naar de proxy stuur. Wanneer ik dat direct naar de gba API stuur, krijg ik wel de 415 fout. 
De proxy negeert denk ik de charset. @MelvLee klopt dat? Hoort de API (gba en proxy) de (in content-type) gestuurde charset interpreteren of valideren?

Sturen van utf-8 geeft dus zowel via de proxy (die dit vermoedelijk gewoon doorstuurt naar de gba API) als direct op de gba API de 415 fout.

N.B. ik heb dit nodig, omdat ReadyAPI in de configuratie bij RvIG default cp1252 encoding gebruikt en de gba API dat niet begrijpt.
Zie #1638.

**Comment by KayodeBakker** [comment]
Fixed in 2.0.29

**Comment by MelvLee** [comment]
Moet dit niet ook voor de Accept header?

**Comment by fsamwel** [comment]
> Moet dit niet ook voor de Accept header?

Denk het eigenlijk wel. Ook daar mag de gebruiker character encoding opgeven en kan die daarmee vragen om iets wat we wel (utf-8) of niet (al het andere) kunnen leveren.

Kunnen we dit (voor zowel content-type als accept) ook in een feature stoppen? Er is nu denk ik nog geen template voor de als stap die dat kan, toch?

**Comment by MelvLee** [comment]
> > Moet dit niet ook voor de Accept header?
> 
> Denk het eigenlijk wel. Ook daar mag de gebruiker character encoding opgeven en kan die daarmee vragen om iets wat we wel (utf-8) of niet (al het andere) kunnen leveren.
> 
> Kunnen we dit (voor zowel content-type als accept) ook in een feature stoppen? Er is nu denk ik nog geen template voor de als stap die dat kan, toch?

ik zal dit implementeren en aanbieden in een p.r.

**Comment by CathyDingemanse** [comment]
fixed
