### ISSUE TITLE
HaalCentraal test API: 501 error bij het bevragen van personen

### ISSUE THREAD

**Issue by Snijhuis** [BRP-API/Haal-Centraal-BRP-bevragen#1643]
**Beschrijf de bug**
Bij zoeken op personen krijgen we de 501 status (not implemented) 

**To Reproduce**
Stappen om de bug te reproduceren
1. Gebruik de zoekfunctie om een persoon te zoeken
2. Bij het bevragen van de API krijgen we de 501 response
3. Hieronder de loggin

Steps to reproduce:

Zoek persoon op achternaam: Me* (met wilcard)
Expected
Lijst met personen wordt opgehaald uit BRP

Actual
Exceptie in log met melding:

09:24:50,034 INFO  [org.jboss.weld.Interceptor] (default task-23) WELD-001703: Unable to determine the @Intercepted Bean<?> for [UnbackedAnnotatedParameter] Parameter 1 of [UnbackedAnnotatedConstructor] @Inject public io.smallrye.faulttolerance.FaultToleranceInterceptor(@Intercepted Bean<?>, FaultToleranceOperationProvider, StrategyCache, FallbackHandlerProvider, MetricsProvider, ExecutorHolder, RequestContextIntegration, CircuitBreakerMaintenanceImpl, SpecCompatibility)
09:24:50,509 WARNING [net.atos.client.brp.BRPClientService] (default task-23) Error while calling listPersonen: Server response from BRP bevragen: 501 (Not Implemented)

**Comment by CathyDingemanse** [comment]
Hi Sander, gebruik je de API lab omgeving (v2.0 beta)? Die is onlangs uitgezet, omdat deze een jaar achter liep op v2.0 IO.
Hiervan hebben gebruikers met een API key bericht gekregen, maar jij blijkbaar niet. Excuses daarvoor. 

Lees hier hoe je lokaal een testomgeving kunt opzetten, inclusief testpersonen van RvIG: 
https://brp-api.github.io/Haal-Centraal-BRP-bevragen/getting-started-v2

**Comment by Snijhuis** [comment]
Dank voor de snelle reactie Cathy. We gaan even kijken of de goede versie gebruikt wordt.
