### ISSUE TITLE
aangaan huwelijk partnerschap wordt geleverd als partner is verwijderd zonder correctie

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1658]
Wanneer een partner onjuist is en daarvoor in de actuele categorie geen gegevens van groepen 1, 2, 3, 6, 7 en 15 gevuld zijn, en dit niet gedaan is met een correctie (de historische gegevens hebben indicatie onjuist), maar met een wijziging, dan wordt aangaanHuwelijkPartnerschap nu wel geleverd.

Zie bijvoorbeeld in scenario "huwelijk is onjuist - maar dit is niet als correctie doorgevoerd" (regel 173) in:
https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/blob/9d5e9e83d92e75eaaf52014122959b437be8640d/features/bevragen/persoon/partner/dev/overzicht-gba.feature

Hiervoor alvast concept PR gemaakt: #1657

**Comment by KayodeBakker** [comment]
Functioneel kan ik je niet vertellen of dit iets is dat we willen ondersteunen. Code technisch is dit voor mij niet anders dan de rule bij ouders die vergelijkbaar functioneert.

**Comment by CathyDingemanse** [comment]
conform PR #1657 gesloten
