### ISSUE TITLE
Brp provider Haal Centraal is niet geïmplementeerd. 501 (v1)

### ISSUE THREAD

**Issue by rderooij** [BRP-API/Haal-Centraal-BRP-bevragen#1689]
**Beschrijf de bug**
Ingeschreven personen raadplegen werkt niet meer.

**To Reproduce**
GET: https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/999995777

Header: x-api-key [xxxx]

```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_NotImplemented",
    "title": "Brp provider Haal Centraal is niet geïmplementeerd.",
    "status": 501,
    "instance": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/999995777",
    "code": "serverError"
}
```

**Verwacht gedrag**
Verwacht testdata terug van haalcentraal.

**Comment by CathyDingemanse** [comment]
Je hebt een belangrijk bericht gemist vrees ik. Het bericht was:
----------------------------------------------
Beste afnemer,
 
De BRP Bevragen repo’s zijn door VNG Realisatie overgedragen aan RvIG. De proefomgeving voor de API lab versie BRP Bevragen v2.0 beta is sterk verouderd en per 1-2-2023 niet meer beschikbaar.
De actuele versie van BRP Bevragen v2.0 io kun je lokaal installeren. Lees hier hoe je dat aanpakt. Zo kun je jouw taakapplicatie of viewer nu al aansluiten op de BRP bevragen API.
Neem je deel aan de pilot BRP? Dan volgt vanzelf een uitnodiging om aan te sluiten op de RvIG proefomgeving, zodat je ook de beveiliging kunt uittesten. Wil je deelnemen aan de pilot Haal Centraal? Stuur dan een reply op deze mail.
 
Heb je vragen? Schiet dan een issue in via Github, of neem contact op met mij of een van mijn RvIG collega’s. Dat kan via dit emailadres, of telefonisch. Succes met aansluiten!
 
Met vriendelijke groet,
 
Cathy Dingemanse
PO BRP Bevragen
RvIG, programma Toekomst BRP
+31653789556

**Comment by CathyDingemanse** [comment]
Inmiddels is de proefomgeving vernieuwd. Zoals vermeld op de Getting Started op de website 
https://brp-api.github.io/Haal-Centraal-BRP-bevragen/v2/getting-started 

kun je de API uitproberen op:

https://proefomgeving.haalcentraal.nl

**Comment by rderooij** [comment]
Dank je wel, maar is er nog wel een proefomgeving voor v1 nog ergens beschikbaar? api/v1?

**Comment by shazada** [comment]
> 

Kunnen we nog de V1.3 nog via de docker-compose lokaal draaien of is dat ook niet meer mogelijk?
We zijn namelijk al in productie met deze versie dus vind het een beetje vreemd dat we inderdaad het bericht gemist hebben, maar ook dat er geen rekening mee gehouden is dat men al wellicht live is..

**Comment by CathyDingemanse** [comment]
Beste @shazada, Haal Centraal heeft nooit een docker compose voor v1.3 aangeboden. Dat is dus nooit mogelijk geweest. De docker compose is alleen beschikbaar gemaakt voor v2.0 (IO). 

Er is wel rekening mee gehouden dat gemeenten met v1.3 live zijn (bijvoorbeeld de gemeente Den Haag). Daarom kun kun je de specificaties nog steeds bij ons vinden, ookal worden deze door RvIG niet gebruikt. Met welke gemeente zijn jullie al live?

**Comment by shazada** [comment]
@CathyDingemanse bij Gemeente Utrechtse Heuvelrug. 
Duidelijk, dus we zullen met de specs, dus voor nu even zelf dummy content genereren.

En de oude v1.3 dummy endpoint https://www.haalcentraal.nl/haalcentraal/api/brp
Is deze nog als een compose of een andere mogelijkheid beschikbaar zodat we deze in onze omgeving kunnen hangen?

**Comment by CathyDingemanse** [comment]
Helaas niet Tahir, de v1.3 proefomgeving is destijds beschikbaar gesteld door de gemeente Den Haag.

**Comment by TobzT** [comment]
Hallo,

Tijdens het implementeren van de BRP API v2.0 in onze omgeving probeer ik de api op te starten met een maven command, en ik krijg deze error tijdens het uitvoeren.

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.31.0:build (start) on project BRP: Unable to pull 'build:latest' : {"message":"pull access denied for build, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"} (Not Found: 404) -> [Help 1]

Is het mogelijk dat ik geen toegang heb tot de docker repository?

Als ik de brp-proxy en brp-mock uitzet mag ik wel booten naar docker.

**Comment by TobzT** [comment]
Op dit moment heb ik een docker-compose file die ik probeer te runnen via maven.

Als ik docker-compose up run boot alles wel netjes.

dit is de docker-compose.yml file:
`version: "2.7"

services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80

  jaeger:
    container_name: jaeger
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 13133:13133
      - 16686:16686
      - 4317:55680

  brpproxy:
    container_name: brpproxy
    image: iswish/haal-centraal-brp-bevragen-proxy:latest
    build:
      context: .
      dockerfile: src/BrpProxy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
      # - Routes__0__DownstreamScheme=https
      # - Routes__0__DownstreamHostAndPorts__0__Host=proefomgeving-gba.haalcentraal.nl
      # - Routes__0__DownstreamHostAndPorts__0__Port=443
    ports:
      - "5001:5000"
    # volumes:
    #   - ./src/config/BrpProxy/configuration:/app/configuration

  gbamock:
    container_name: gbamock
    image: iswish/haal-centraal-brp-bevragen-gba-mock:latest
    build:
      context: .
      dockerfile: src/BrpService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"
`

**Comment by MelvLee** [comment]
@TobzT, ik wou eigenlijk je Maven configuratie zien. Wat ik namelijk niet kan opmaken uit de foutmelding is welke image er wordt gepulled voor de build actie en welke repository de fabric8io plugin probeert te benaderen.

**Comment by TobzT** [comment]
Waar in de maven configuratie kan ik dit vinden? 

Het enige wat ik kan vinden dat bij de fabric8io plugin hoort is:

```
<!-- Docker -->
		<fabric8.maven.plugin.version>3.5.42</fabric8.maven.plugin.version>
		<fabric8.docker.maven.plugin.version>0.33.0</fabric8.docker.maven.plugin.version>
```
en

```
<distributionManagement>
		<repository>
			<id>releases</id>
			<url>https://nexus.contezza.nl/repository/releases/</url>
		</repository>
		<snapshotRepository>
			<id>snapshots</id>
			<url>https://nexus.contezza.nl/repository/snapshots/</url>
			<uniqueVersion>false</uniqueVersion>
		</snapshotRepository>
	</distributionManagement>

	<scm>
		<connection>scm:git:https://git.contezza.nl/develop/products/${project.artifactId}.git</connection>
		<url>https://git.contezza.nl/develop/products/${project.artifactId}.git</url>
		<developerConnection>scm:git:https://git.contezza.nl/develop/products/${project.artifactId}.git</developerConnection>
		<tag>HEAD</tag>
	</scm>
```

We hebben onze eigen nexus repository.

Sorry als ik het verkeerd heb begrepen, ik ben nog nieuw tot maven.

**Comment by TobzT** [comment]
Is hier al meer over bekend?

**Comment by MelvLee** [comment]
@TobzT, ik heb ook geen ervaring met maven en fabriq8io. Ik kan uit de foutmelding en de configuratie snippets die je hebt gestuurd niet opmaken voor welke docker registry je geen toegang hebt. De docker registry voor de brpproxy is niet private. Ik denk dus niet dat het hieraan ligt.
