### ISSUE TITLE
Als tester wil ik dat relaties altijd in dezelfde volgorde geleverd worden

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1702]
zodat ik een regressietest kan maken die bij een volgende release zal slagen.

Bij verschillende versies van de gba API worden relaties nationaliteiten, ouders, partners en kinderen niet altijd in dezelfde volgorde geleverd. Dit is erg onhandig, omdat dan regressietests falen terwijl er in bijvoorbeeld nationaliteiten[0] of kinderen[2] niet meer dezelfde nationaliteit of hetzelfde kind geleverd wordt.

Kan de code zo gemaakt worden dat dit altijd in een vaste volgorde wordt geleverd (bij ongewijzigde data in de registratie).

Ik stel voor dat nationaliteiten, partners en kinderen gesorteerd worden op stapelnummer.

En voor ouders: ouders[0]=ouder1 en ouders[1]=ouder2

N.B. in versie 2.0.39 is de volgorde van nationaliteiten (bij 1 nationaliteit en 1 bijzonder NL-schap) weer gewijzigd.

**Comment by KayodeBakker** [comment]
Nog even ter informatie. Ik kan dit totaal niet nabootsen. Ik heb de wijziging gemaakt zoals voorgesteld is, maar ik heb niet veel vertrouwen dat het de oplossing zal zijn.

**Comment by sergei-maertens** [comment]
heeft de volgorde hier een semantische betekenis? Indien niet zou ik er eerder voor opteren om in de test ongesorteerde sets te gebruiken voor de vergelijken in plaats van gesorteerde lists :)
