### ISSUE TITLE
Fields combinatie geeft 500 internal server error

### ISSUE THREAD

**Issue by michelvankasteren** [BRP-API/Haal-Centraal-BRP-bevragen#1710]
Wanneer field "naam.geslachtsnaam","partners" worden opgevraagd komt er een 500 internal server error terug. "naam.voornamen","partners" en andere combinaties gaan wel goed.

POST https://proefomgeving.haalcentraal.nl/haalcentraal/api/brp/personen
Accept: application/json
x-api-key: *******************************
User-Agent: RestSharp/108.0.2.0
{  "fields":["naam.geslachtsnaam","partners"], "burgerservicenummer":["999993653"], "type":"RaadpleegMetBurgerservicenummer" }

/haalcentraal/api/brp/personen

Correcte response bijvoorbeeld:
{"type":"RaadpleegMetBurgerservicenummer","personen":[{"naam":{"geslachtsnaam":"Moulin"},"partners":[{"geslacht":{"code":"M","omschrijving":"man"},"soortVerbintenis":{"code":"H","omschrijving":"huwelijk"},"naam":{"voornamen":"Jean Marie","geslachtsnaam":"Beaudelaire","voorletters":"J.M."},"geboorte":{"land":{"code":"5002","omschrijving":"Frankrijk"},"plaats":{"omschrijving":"Saint Amarin"},"datum":{"type":"Datum","datum":"1976-08-01","langFormaat":"1 augustus 1976"}},"aangaanHuwelijkPartnerschap":{"datum":{"type":"Datum","datum":"2008-12-01","langFormaat":"1 december 2008"},"land":{"code":"5002","omschrijving":"Frankrijk"},"plaats":{"omschrijving":"Thann"}}}]}]}

**Comment by MelvLee** [comment]
gefixt in brpproxy v2.0.21 (https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/pkgs/container/haal-centraal-brp-bevragen-proxy)
