### ISSUE TITLE
als ik zowel adressering als adresseringBinnenland vraag, krijg ik alleen adresseringBinnenland

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1716]
{
  "fields": ["adressering","adresseringBinnenland"],
  "type": "RaadpleegMetBurgerservicenummer",
  "burgerservicenummer": ["999993422"]
}

Deze persoon heeft een buitenlands adres. Nu levert de proxy geen adresregels.

Ik denk dat fields moet werken als optelling. Dus het toevoegen van een extra veld in fields moet niet leiden tot minder krijgen.

**Comment by CathyDingemanse** [comment]
fixed
