### ISSUE TITLE
Documenatie beschikbaar maken in Swagger

### ISSUE THREAD

**Issue by Sc0tTyXL** [BRP-API/Haal-Centraal-BRP-bevragen#1728]
Hallo,

De documentatie is alleen maar beschikbaar in Redoc.
Helaas is Redoc totaal on overzichtelijk.

Graag de documentatie beschikbaar maken in Swagger.

**Comment by CathyDingemanse** [comment]
Goedemiddag! Dat is niet gedaan omdat Swagger geen polymorfisme ondersteunt, waardoor de beschrijving van de interface niet begrijpelijk kan worden gedocumenteerd in Swagger. 

Mag ik vragen wie u bent en namens welke leverancier of overheidsorganisatie u dit vraagt?
