### ISSUE TITLE
Missende informatie adressering

### ISSUE THREAD

**Issue by Sc0tTyXL** [BRP-API/Haal-Centraal-BRP-bevragen#1729]
**Beschrijf de bug**
adresregel1 bevat straat en huis nummer in 1 string
adresregel2 bevat postcode en woonplaats in 1 string

Ook staat er nu niet of het gaat om een woon of brief adres

**To Reproduce**
Open de documentatie

**Verwacht gedrag**
Losse velden voor straat, huisnummer, postcode en woonplaats.
Zodat niet iedereen een implementatie moet schrijven voor het parsen van deze adres gegeven.

**Comment by Sc0tTyXL** [comment]
In deze user story wordt verwezen naar de BAG:
https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/833

De objecten in de BAG bevatting wel deze velden, hoe moet er nu gematched worden?

**Comment by CathyDingemanse** [comment]
Adresregel 1 en adresregel 2 zijn onderdeel van adressering. Adressering is bedoeld voor het aanschrijven van personen (sturen van brieven etc.) en is zo afgekort dat het altijd past in een vensterenvelop of in een selectielijstje op een scherm. Als je adressering gebruikt hoef je als afnemer niets aan te passen als een van de onderliggende gegevens  wijzigt, bijvoorbeeld in de BAG. Het gebruik van losse gegevens leidt vaker tot een breaking change en heeft daarmee impat op afnemers. Adressering is maximaal evolvable. 

Voor afnemers die toch de afzonderlijke BAG gegevens willen gebruiken verwijs ik naar het verblijfadres (onderdeel van binnenlands adres) binnen verblijfplaats van Persoon. De response van het type Persoon krijg je als je de operatie raadpleegMetBurgerservicenummer gebruikt. 

Succes bij uw keuze!

**Comment by Sc0tTyXL** [comment]
Ik zie nu dat Redoc niet automatisch het juiste response type toont bij de request en dat je deze handmatig moet selecteren.
Zie ook mijn andere issue [Redoc is overzichtelijk](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/1728)

In het antwoord RaadpleegMetBurgerservicenummer zie ik geen verblijf adres staan of binnenlands adres. Wel verplaats met type string:
![image](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/assets/24222938/0594065a-3ec2-4933-8352-aa9a0fa14e73)

**Comment by Dennisenzo** [comment]
Ik loop ook tegen dit probleem aan. De adresregels zijn vrijwel niet te parsen naar de losse componenten gezien de mogelijke variaties eindeloos zijn. Het enige dat Redoc over 'verblijfplaats' zegt is dat er een string genaamd 'type' in zit. In mijn tests ben ik nog geen response met een ingevulde verblijfplaats tegengekomen.

Is hier enige update over? Er zijn veel systemen die deze losse adrescomponenten gebruiken.

**Comment by MelvLee** [comment]
> Het enige dat Redoc over 'verblijfplaats' zegt is dat er een string genaamd 'type' in zit.

Mijn vermoeden is dat er in Redoc in de *Response samples* wordt gekeken. In dit geval klopt het dat nu alleen een string genaamd 'type' wordt getoond. Wij zullen uitzoeken hoe er betere samples in Redoc kan worden getoond.
Voor een betere view is het handiger om naar de response schema te kijken onder responses. Selecteer voor type 'RaadpleegMetBurgerservicenummer'

![image](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/assets/18151729/747e0a49-7f53-4fed-9798-b465ef4fa29e)

Er wordt dan een overzicht getoond van alle te bevragen velden, ook verblijfplaats velden

![image](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/assets/18151729/c997a38f-a27e-4d72-8aef-1c9978affc68)


> In mijn tests ben ik nog geen response met een ingevulde verblijfplaats tegengekomen.

Verblijfplaats velden worden geleverd als in de fields parameter 'verblijfplaats' of één of meerdere specifieke 'verblijfplaats' veldnamen wordt opgegeven. Dit kan alleen via RaadpleegMetBurgerservicenummer

**Comment by CathyDingemanse** [comment]
solved
