### ISSUE TITLE
Correcties in README.md en index.md

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#1732]
Er zijn enkele kleine dingen die n.m.m. op de README.md en index.md moeten worden aangepast.

**README.md**
* Verwijder in de sectie 'Bronnen' de link naar 'Productvisie Haal Centraal'. De link is niet meer correct en wordt ook niet meer aangeboden in de GH Pages site van deze repo.
* Wijzig de link onder 'Stelselcatalogus' naar 'https://www.stelselcatalogus.nl/registraties/registratie?id=http://opendata.stelselcatalogus.nl/id/registratie/BRP'.

**index.md**
* Indien de link naar Stelselcatalogus hier niet meer staat omdat deze niet meer correct was dan kun je deze weer opnemen op dezelfde wijze als voor README.md wordt voorgesteld.

**Comment by CathyDingemanse** [comment]
wordt veranderd bij realisatie nieuwe portal
