### ISSUE TITLE
Corrigeren wat gelogd wordt door de GBA API

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1733]
1. Elke API (personen, reisdocumenten en bewoning) logt voor log.logger altijd ‘API’. Hier had ik de naam van de API verwacht, bijvoorbeeld ‘haalcentraal-bewoningen-api’ of 'haalcentraal-personen-API'
2. De API logt url.path niet. Dan kan je niet zien welke url gebruikt is. Zo kan je aan de logging dus ook niet zien op deze op acc of lap is ontstaan. En in combinatie met ontbreken log.logger kan je helemaal niet zien welke API de fout veroorzaakt heeft.
3. Request.id wordt niet gelogd. Deze moet worden overgenomen uit de Request-ID header die door de loadbalancer is toegevoegd. Deze hebben we nodig om een bericht door de hele loggingketen heen te kunnen volgen.
4. Token wordt gelogd als array, bijvoorbeeld ‘"token": ["afnemerID=990300", "OIN=00000004900000004000"]’ en wordt daardoor niet uit elkaar getrokken en als toonbare/filterbare gegevens opgenomen. Ik denk dat dit moet worden gelost als "token": { "afnemerID": 990300", "OIN": "00000004900000004000" } Dus niet sturen als array (blokhaken), maar als object (accolades).
5. Request.body.type wordt niet gelogd als apart veld. Ik krijg nu alleen request.body.stringified door, maar had hier graag ook een apart toonbaar/filterbaar veld van gehad (uiteraard alleen wanneer de request body valide json is en type bevat).

Voor punt 5 staat in het logging document: 

> Veld “type” wordt eruitgehaald naar apart veld request.body.type, wanneer het in het request zit.
> Idem voor “fields” naar request.body.fields
> Kayo zoekt uit of ook gelogd kan worden wanneer de API de request niet kan parsen.

**Comment by MelvLee** [comment]
@fsamwel, uit het logging document kan ik niet opmaken of de logs compliant moeten zijn aan [Elastic Common Schema](https://www.elastic.co/guide/en/ecs/8.11/index.html) of dat alleen veld namen wordt gebruikt die ook in de Elastic Common Schema voorkomen en geen compliancy.

Zo wordt er bijv. in het logging document aangegeven dat log.logger de naam van de service moet bevatten die de logging zet, terwijl volgens de ECS documentatie log.logger gebruikt moet worden voor de naam van de logger binnen de applicatie. Zie https://www.elastic.co/guide/en/ecs/8.11/ecs-log.html#field-log-logger. Informatie over de API, zoals de naam en de versie zouden volgens mij in resp. service.name en service.version moeten staan. Zie: https://www.elastic.co/guide/en/ecs/8.11/ecs-service.html

Verder staat in het logging document dat het veld 'request.body.stringified' moet worden gebruikt om de stringified variant van de request body te loggen. In ECS is er het veld 'request.body.content' dat volgens mij hiervoor moet worden gebruikt.

Ook zie ik in het logging document staan dat er nog een oplossing moet worden bedacht voor het loggen van de stack trace van een exceptie. Volgens mij is in het ECS hiervoor de error velden gedefinieerd. Zie: https://www.elastic.co/guide/en/ecs/8.11/ecs-error.html

In het logging document staat niet aangegeven wat voor waarde er in de log.level veld moet staan. Uit een dump van de bevragen API zie ik dat alle log regels voor log.level alleen de waarde 'error' hebben. Wat ik hieruit opmaak is dat er dan een ander veld moet worden gebruikt om te bepalen of er een fout in de API is opgetreden. Ik vermoed de response.status_code. Dit is naar mijn mening niet handig. Niet alle applicaties zijn HTTP APIs die over HTTP communiceren en volgens mij gebruiken monitoring tools de log level om te bepalen of er moet worden genotificeerd.

Ik zou ervoor willen pleiten om als er ECS veld namen worden gebruikt om ook ECS compliant te loggen. Dit heeft namelijk als voordeel dat onze logs niet mogelijk in de toekomst zullen conflicteren en kan de SDKs van Elastic worden gebruikt om de logs op te maken ipv deze zelf te implementeren. Zie hiervoor de dotnet repo van Elastic: https://github.com/elastic/ecs-dotnet/tree/main/src

**Comment by CathyDingemanse** [comment]
done
