### ISSUE TITLE
Wat levert de gezagsmodule bij invoer van een overleden persoon?

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#1764]
Zowel bij de raadpleeg als bij de zoek op adresseerbaar object kunnen overleden personen worden opgegeven. 
De vraag is of wij hier in de API een correctie moeten doen.

**Comment by fsamwel** [comment]
- wanneer de overleden persoon minderjarig is, is het gezag niet te bepalen. Dat is ook wat de personen API levert als gezag: "GezagNietTeBepalen".
- wanneer de overleden persoon meerderjarig is, heeft deze geen gezag meer over de kinderen. Er wordt dan dus geen gezag geleverd.
