### ISSUE TITLE
De example voor gezag in de redoc OAS spec is niet geimplementeerd

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#1813]
**Beschrijf de verbetering**
Graag een example implementeren van tweehoofdig ouderlijk gezag

**Comment by fsamwel** [comment]
Pull request https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/pull/1815 gemaakt. Alleen geeft de OAS lint een foutmelding waar ik de oorzaak niet van begrijp. Lijkt op de genereerversies, voor mijn aanpassingen zijn doorgevoerd op de genereerversies. @MelvLee zie jij de oorzaak hiervan?
