### ISSUE TITLE
Als PO wil ik toelichting bij gezag niet te bepalen aanhouden 

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#1832]
...zodat de BVD niet onbevoegd over een toelichting van gezag niet te bepalen kan beschikken.

Deze functionaliteit wordt aangehouden totdat de besluit DO hierop is aangepast.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [x] gegenereerde code
- [ ] testgevallen

**Comment by nielskorporaal** [comment]
Code aanpassingen om toelichting aan te houden in personen-informatie-service staan klaar in [PR 16](https://github.com/BRP-API/personen-informatie-service/pull/16)

**Comment by CathyDingemanse** [comment]
toelichting kan worden doorgevoerd. Toelichting is opgenomen in het LO Q1-2025 als onderdeel van gezag.
