### ISSUE TITLE
Onjuiste poortnummers in de Getting Started

### ISSUE THREAD

**Issue by PeterZaal** [BRP-API/Haal-Centraal-BRP-bevragen#1839]
**Onjuiste poortnummers in de Getting Started**
In de [Getting Started](https://[brp-api.github.io/Haal-Centraal-BRP-bevragen/v2/getting-started](https://brp-api.github.io/Haal-Centraal-BRP-bevragen/v2/getting-started)) worden aanwijzingen gegeven hoe de BRP API Personen lokaal getest kan worden.
Hierbij wordt zowel bij het Docker voorbeeld als bij het Kubernetes voorbeeld http://localhost:5001 getoond, maar dit moet http://localhost:5010 zijn.

**Comment by CathyDingemanse** [comment]
Scherp! Dank voor het melden @PeterZaal. Is opgelost!
