### ISSUE TITLE
De depricated gegevens zijn nog niet depricated in in onderzoek.

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#1841]
Graag depricaten

**Comment by MelvLee** [comment]
@CathyDingemanse, volgens mij betreft het alleen het veld InOnderzoek.indicatieGezagMinderjarige. Als dat klopt, dan kunnen we #1853 worden ge-approved en kan het ook mee met #1831

**Comment by CathyDingemanse** [comment]
Ja klopt!
