### ISSUE TITLE
User stories versie 2.1 t/ v2.3 worden nog niet getoond op de portal

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#1850]
**Beschrijf de bug**
Een heldere beschrijving van wat de bug is.

**To Reproduce**
Stappen om de bug te reproduceren
1. Ga naar '...'
2. Click op '....'
3. Scroll down naar '....'

Geef het reproductie path mee

**Verwacht gedrag**
Een beknopte beschrijving van het gedrag wat verwacht was.

**Screenshots**
Voeg eventueel een screenshot toe

**Comment by MelvLee** [comment]
@CathyDingemanse , done

**Comment by CathyDingemanse** [comment]
@MelvLee, super! thnx!
