### ISSUE TITLE
Als afnemer wil ik dat het maximum aantal gevonden personen bij het zoeken op een adres gelijk is aan de andere dienstverlening van RvIG

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#1867]
zodat afnemers meer grote gezinnen en verblijfplaatsen met meer tijdelijke bewoners (opvanglocaties, jeugdzorginrichtingen etc.) kan vinden.

De Ad hoc webservice levert maximaal 10 adressen per adresvraag, en max 30 personen per adres.
De BRP API verruimt het aantal gevonden resultaten naar 30 personen bij de volgende zoekoperaties:
zoekMetPostcodeEnHuisnummer
zoekMetStraatHuisnummerEnGemeentevaninschrijving
zoekMetNummeraanduidingIdentificatie
zoekMetAdresseerbaarObjectIdentificatie

**Comment by Patrick-4488** [comment]
eerst per adres naar maximaal 30 personen

**Comment by Patrick-4488** [comment]
Dit geldt alleen bij adresseerbaar objecten, de andere zoekfuncties moeten wel op 10 personen blijven

Scenario bij bewoning kan in 1 stap X aantal personen opvoeren, kijken of dat te hergebruiken is.

**Comment by fsamwel** [comment]
> Dit geldt alleen bij adresseerbaar objecten, de andere zoekfuncties moeten wel op 10 personen blijven

De zoekfuncties die maximaal 30 personen mogen leveren staan bovenaan genoemd. Dat is dus niet alleen zoekMetAdresseerbaarObjectIdentificatie.

De zoekfuncties die maximaal 10 personen mogen leveren zijn ZoekMetGeslachtsnaamEnGeboortedatum en ZoekMetNaamEnGemeenteVanInschrijving.

Bij RaadpleegMetBurgerservicenummer is er geen controle op maximaal aantal gevonden personen. Hier zit de beperking al in de validatie op het request. Er mogen maximaal 20 burgerservicenummers worden opgegeven

**Comment by Patrick-4488** [comment]
1. ik pas nu de hardcoded waarde van 10 aan naar 30 voor de 4 zoekfuncties 
2. pas alle gerelateerde features aan 
3. maak een issue aan om een nette oplossing te maken (zoals nswag introduceren en maxitems opnemen in oas)
