### ISSUE TITLE
Verwijder underscores uit componentnamen en enumeratie-namen

### ISSUE THREAD

**Issue by JohanBoer** [BRP-API/Haal-Centraal-BRP-bevragen#685]
In het BRK-project is besloten om alleen underscores te gebruiken in de properties _embedded en de _links.
Alle componentnemen en alle enumeratie-namen bevatten geen underscores meer. 

Uit Haal-Centraal consistentie overwegingen wordt deze wijziging doorgevoerd als er een volgende minor versie wordt doorgevoerd.

**Comment by fsamwel** [comment]
dit gaat alleen om componentnamen, niet om enumeratiewaarden. Anders is het inderdaad een breaking change

**Comment by KayodeBakker** [comment]
@CathyDingemanse Ik maak nog even een apart issue aan, maar dit komt aardig in de buurt wat jij net hebt besproken met Jeroen over de nette naam notaties van enums
