### ISSUE TITLE
Als medewerker van de gemeente wil ik op adresseerbaar objectidentificatie kunnen zoeken in de BRP

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#801]
...omdat personen op een standplaats ligplaats en verblijfsobject worden ingeschreven en dit als identificatie verblijfplaats door afnemende systemen wordt gebruikt.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Versie 1.2.0 is al ge-released dus deze funtionalieit kan niet meer in versie 1.2 opgenomen worden.

**Comment by CathyDingemanse** [comment]
done
