### ISSUE TITLE
Als VNG-Realisatie wil ik een test voor de API die we zelf kunnen onderhouden

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#83]
zodat...
* aangetoond wordt dat de referentie-implementatie van de provider voldoet aan de standaard
* een leverancier van een/de provider kan testen dat zijn applicatie voldoet aan de standaard
* de test gebruikt kan worden voor een compliancy test op de standaard
* de beheerder(s) van de standaard en belanghebbenden de dekking van de test kunnen begrijpen
* de beheerder(s) van de standaard en belanghebbenden de test kunnen uitbreiden of corrigeren zonder daarvoor een specifieke programmeertaal te hoeven kennen
* developers van een client kunnen zien hoe de API werkt/moet werken in verschillende grenssituaties en foutsituaties

Hiermee wordt invulling gegeven aan definition of done element "testgevallen".

**Comment by fsamwel** [comment]
Ik stel voor de testgevallen te beschrijven in Gherkin Syntax. De implementatie daarvan kan vervolgens in een willekeurige geschikte variant van Cucumber gebeuren, zoals met Behave.

**Comment by JohanBoer** [comment]
Buiten scope

**Comment by JohanBoer** [comment]
Voorstel om deze voor deel 2 binnen scope te halen. Met het maken van een referentieimplementatie en het beschikbaar krijgen van een testvoorziening is dit te doen.
