### ISSUE TITLE
Als gebruiker wil ik de volledige naam krijgen

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#832]
...zodat ik deze direct kan tonen zonder deze zelf samen te stellen met verschillende logica

Nu moet de volledige naam worden samengesteld uit voornamen, adellijke titel of predicaat, voorvoegsel en geslachtsnaam.

Dat is nog niet zo heel makkelijke als het lijkt want:
- voorvoegsel moet met kleine letters worden geschreven, tenzij er geen voornaam en geen adellijke titel is
- een predicaat moet voor de voornamen worden geplaatst, een titel tussen voornamen en voorvoegsel
- ik weet niet vooraf of alle onderdelen voorkomen (m.n. voorvoegsel en adellijkeTitelPredikaat) in de response

Ik denk dat vrijwel elke gebruiker, zeker bij het tonen van zoekresultaten, de volledige naam moet tonen. Dus dan is het veel handiger wanneer daarvoor direct een gegeven uit de API kan worden gebruikt, zonder eerst meerdere velden samen te moeten voegen

Als gebruiker kan ik niet zien of adellijkeTitelPredikaat een predicaat bevat of een adellijke titel. De aanduiding "soort" die in de betreffende tabel zit wordt niet meegeleverd. Dus moet ik zelf logica hebben "als adellijkeTitelPredikaat in {"jonkheer", "jonkvrouw"} dan ...". Dat is riskant, want een landelijke tabel kan elk moment worden gewijzigd zonder versiewijziging van de API, maar dat kan wel breaking zijn.

**Comment by JohanBoer** [comment]
We hebben in de API-specificatie aanschrijfwijze en gebruikInLopendeTekst gedefinieerd voor de naam.
Is dit een derde variant daarop ?

**Comment by CathyDingemanse** [comment]
done
