### ISSUE TITLE
Als PO wil ik dat de adres feature consistent is met BAG en NEN 5825:2002, zodat zij voor gebruiker consistent zijn 

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#833]
De [adres feature](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/adres.feature) stelt de adresregels op een andere manier samen dan in de Haal Centraal BAG API. In de BAG API worden de adresregels samengesteld conform NEN 5825:2002. Zie de [adresregels feature voor de BAG API](https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/blob/master/features/adresregels.feature).

Ik denk dat adresregels in de BRP op dezelfde manier zouden moeten worden samengesteld als in de BAG, beide volgens NEN 5825:2002.

**Comment by CathyDingemanse** [comment]
Het gaat dus om het toevoegen van logica voor een iets andere representatie van:

- huisnummers en huisnummervoegingen
- postcode
- woonplaats

Voor de BAG adressen kan de RvIG evt. de BAG API gebruiken (en evt. een caching mechanisme implementeren)

Voor de niet-BAG adressen zal RvIG een stukje van deze logica zelf moeten implementeren. 
@Strijm zou jij evt de code met de RvIG kunnen delen?

**Comment by fsamwel** [comment]
@CathyDingemanse ik heb de [adresregels feature voor de BAG API](https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/blob/master/features/adresregels.feature) doorgenomen. Deze is voldoende input (duidelijk en compleet genoeg) om de [adres feature voor de BRP](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/adres.feature) te kunnen opstellen.

**Comment by fsamwel** [comment]
als we toch bezig zijn met de adresregels, moeten we ook controleren of de aanduidingBijHuisnummer correct is opgenomen. Nu wordt die achteraan geplaatst. Bijvoorbeeld "1e Exloërmond 3 tegenover"

Op [wikipedia](https://nl.wikipedia.org/wiki/Huisnummer#Woonboten) staat dit op in andere variant beschreven, waar het tussen straat en huisnummer wordt gezet, en "tegenover" wordt afgekort als "t/o". Bijvoorbeeld "Steenkade t/o 56".

Wellicht staat in NEN 5825:2002 ook beschreven hoe dit officieel moet worden opgenomen.
