### ISSUE TITLE
Als PO wil ik dat leeftijd wordt aangevuld met "wordt dit jaar [leeftijd]" en "wordt deze maand [leeftijd]"

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#860]
...zodat consumers niet alsnog geboortedatum hoeven te raadplegen om de leeftijd voor hun proces vast te stellen bij een onvolledige geboortedatum.

Dus als alleen jaar bekend is (en niet maand en dag) of als jaar en maand bekend zijn (en niet dag).

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by gertjanvanderkooij** [comment]
Waarom niet gekozen voor 'dagenTotNieuweleeftijd' (oid); kan consumer zelf bepalen/berekenen welke periode voor hem van belang is.

**Comment by fsamwel** [comment]
> Waarom niet gekozen voor 'dagenTotNieuweleeftijd' (oid); kan consumer zelf bepalen/berekenen welke periode voor hem van belang is.

het doel van deze user story is iets van leeftijd doorgeven wanneer de geboortedatum gedeeltelijk (on)bekend is.

**Comment by fsamwel** [comment]
@CathyDingemanse dit zou je ook kunnen oplossen met één gegeven: leeftijdMinimaal. Bij onbekende maand wordt de leeftijd gegeven die de persoon vorig jaar heeft gekregen. Bij onbekende dag wordt de leeftijd die de persoon vorige maand heeft gekregen.

voordeel: 1 gegeven waarin gekeken kan worden (bijvoorbeeld bij check of iemand meerderjarig is)
nadeel: voor gebruiker onduidelijk wat de nauwkeurigheid hiervan is
verschil t.o.v. wordtDitJaar&wordtDezeMaand: waarde is soms 1 minder (anders zou het leeftijdMaximaal worden)

**Comment by JohanBoer** [comment]
Oppakken na 2.0. Vereist onderzoek bij Stakeholders / gebruikers
