### ISSUE TITLE
Als PO wil ik het voor consumers mogelijk maken geen BSN in de database op te slaan 

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#861]
...zodat zij efficiënter aan de AVG kunnen voldoen (zonder encryptie te hoeven toepassen).

_Threat type:_
Information Disclosure. Toegang tot data waarvoor niet is geautoriseerd

_Threat:_
Ongeautoriseerde toegang tot opslag van BSN in combinatie met andere PII

_Countermeasure:_
GET endpoint toevoegen en GUID/UUID als pad-parameter definiëren.

**Acceptatiecriteria**
- evolvable introductie

**Comment by melsk-r** [comment]
Moet de titel niet luiden 'Als PO wil ik het voor consumers mogelijk maken geen BSN in de eigen database op te slaan'?

**Comment by fsamwel** [comment]
deze GET doen we nu nog niet. In het ontwerp van de API (nu alleen POST) moet wel worden gezorgd dat dit later kan worden toegevoegd (inclusief links naar de GET bij gevonden personen) zonder breaking changes (dus evolvable)
