### ISSUE TITLE
Als PO wil ik onderzoeken of de docker image van de informatievragenProxy kan worden gehost door Haven.commonground.nl 

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#895]
...zodat gemeenten die deelnemen aan de pilot BRP de container daar kunnen downloaden

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
@JohanBoer onderzoek jij de mogelijkheden?

**Comment by JohanBoer** [comment]
Er wordt een Hackathon georganiseerd (13 t/m 17 juni) door VNG waarbij alle API's en initiatieven die nu binnen de VNG lopen met elkaar in relatie worden gebracht. Daar gaan de Haal Centraal API's ook een rol spelen. In dat kader gaan we uitzoeken hoe we de proxy binnen Haven beschikbaar kunnen maken. Daarvoor is in het kader van deze Hackathon kennis van Haven beschikbaar.
