### ISSUE TITLE
Als medewerker van een gemeente wil ik weten welke gegevens de status "in onderzoek" hebben

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#907]
...zodat ik kan bepalen of ik moet terugmelden en wat ik moet terugmelden.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by gertjanvanderkooij** [comment]
Welke gedachtenlijn willen we hier volgen? 

- Grofmazig in BRP Actueel, Historie, Bewoning (indicator 'er is iets in onderzoek')
- Fijnmazig op te halen via apart endpoint 'BRP InOnderzoek', waarin tot op elementniveau (en waarvoor geautoriseerd) kan worden afgedaald?

**Comment by fsamwel** [comment]
@gertjanvanderkooij fijnmaziger maken van inOnderzoek, bijvoorbeeld met een extra endpoint kan eventueel later worden toegevoegd. Lukt nu niet voor v2.0 door te voeren. Komt op de backlog.
