### ISSUE TITLE
Vragen m.b.t. aanhef.feature

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#914]
Ik heb aanhef.feature nog eens doorgenomen en heb naar aanleiding daarvan enkele vragen en enkele mogelijke verbeteringen.

### Tabel regel 24 t/m 40
Waarom wordt bij de andere titels dan Prins, Prinses als het geslacht niet bekend is niet ook een gender neutrale aanhef gebruikt. is dat niet 'Hoogwelgeborene' en 'Hooggeborene'?

Als het geslacht onbekend is welke titels worden er dan toegekend? Als Prinses is toegekend dan weet je toch ook dat het een vrouw is en als het Prins is dan weet je toch dat het een man is. In welke situatie kan het nu voorkomen dat je het geslacht niet kent maar wel de titel? Of wordt de adelijke titel niet toegekend zoals in de tabel vermeldt maar krijgt deze een code en moet de daadwerkelijke titel worden bepaald a.d.h.v. dat veld en de geslachtsaanduiding?
Ik zou haast zeggen dat de tabel er als volgt uit zou moeten zien:

```
  | Baron                    | man                 | Hoogwelgeboren heer   |
  | Barones                  | vrouw               | Hoogwelgeboren vrouwe |
  | ?                        | onbekend            | Hoogwelgeborene       |
  | Graaf                    | man                 | Hooggeboren heer      |
  | Gravin                   | vrouw               | Hooggeboren vrouwe    |
  | ?                        | onbekend            | Hooggeborene          |
  | Hertog                   | man                 | Hoogwelgeboren heer   |
  | Hertogin                 | vrouw               | Hoogwelgeboren vrouwe |
  | ?                        | onbekend            | Hoogwelgeborene       |
  | Jonkheer                 | man                 | Hoogwelgeboren heer   |
  | Jonkvrouw                | vrouw               | Hoogwelgeboren vrouwe |
  | ?                        | onbekend            | Hoogwelgeborene       |
  | Markies                  | man                 | Hoogwelgeboren heer   |
  | Markiezin                | vrouw               | Hoogwelgeboren vrouwe |
  | ?                        | onbekend            | Hoogwelgeborene       |
  | Prins                    | man                 | Hoogheid              |
  | Prinses                  | vrouw               | Hoogheid              |
  | ?                        | onbekend            | Hoogheid              |
  | Ridder                   | man                 | Hoogwelgeboren heer   |
  | Ridder                   | vrouw               | Hoogwelgeboren vrouwe |
  | Ridder                   | onbekend            | Hoogwelgeborene       |
```
Toegegeven, ik zou niet weten wat er op de plaats van de vraagtekens zou moeten komen te staan.
In ieder geval kan in de rijen waar vrouw staat de mannelijke titel weg en in de rijen waar man staat de vrouwelijke titel.

### Regel 86
Wat als beide partners een adelijke titel/predicaat hebben, heeft dat nog wel invloed op de aanhef? Met name de situaties waarbij beide titels/predicaten van elkaar afwijken. Welke titel/predicaat is dan dominant? Dus stel dat een gravin trouwt met een Baron.

### Tabel regel 113 t/m 123
In regel 118 staat:
`| Partner na eigen   | onbekend        | GA VV GN-VP GP      | F. Groenen-Groenink       | Geachte F. Groenen-Groenink|`

Je hebt bij aanduidingNaamgebruik ook een versie voor de vrouw maar niet een voor de man. Is dat ook de situatie dat je als man er niet voor kunt kiezen om de Partner naam na de eigen naam te laten vermelden of is dat gewoon een ommissie in de tabel? Als dit daadwerkelijk de situatie is dan zou je dus zeggen dat als 'aanduidingNaamgebruik' de waarde 'Partner na eigen' heeft je ook weet dat het een vrouw betreft.

### Regel 125
Persoonlijk zou ik er voor kiezen nog wat toelichting of zelfs een apart scenario op te nemen (ook omdat de voorbeelden niet uitputtend zijn), bijv:

```
Als een voorvoegsel is vastgelegd beginnend met een hoofdletter dan wordt deze altijd beginnend met een hoofdletter weergegeven.

Als een voorvoegsel is vastgelegd beginnend met een kleine letter dan wordt deze beginnend met een hoofdletter weergegeven  indien deze onderdeel uitmaakt van de eerste of enige te vermelden naam en het geslacht bekend is.

In alle andere gevallen wordt een voorvoegsel beginnend met een kleine letter weergegeven.
```
Wellicht goed om ook nog een voorbeeld op te nemen, een kopie van regel 131 maar dan in de 'Partner na eigen' vorm. bijv.

`| Partner na eigen        | onbekend     | van    | Velzen | In het | Veld   | Geachte G.M. In het Veld-van Velzen |`

**Comment by fsamwel** [comment]
> Waarom wordt bij de andere titels dan Prins, Prinses als het geslacht niet bekend is niet ook een gender neutrale aanhef gebruikt. is dat niet 'Hoogwelgeborene' en 'Hooggeborene'?

Omdat wij dit soort aanspreekvormen niet zelf verzinnen

**Comment by fsamwel** [comment]
> Als Prinses is toegekend dan weet je toch ook dat het een vrouw is en als het Prins is dan weet je toch dat het een man is.

As de titel een geslacht suggereert, maar tóch is de geslachtsaanduiding "O", dan moet je denk ik de geslachtsaanduiding volgen. Bij een persoon, anders misschien dan een pas geboren baby, wordt zover ik kan begrepen heb alleen "O" gevuld voor mensen die bewust aangeven niet als een "man" of "vrouw" aangeduid te willen worden (omdat ze dat niet zijn). het gaat dus vaker om iemand die geen van beide traditionele geslachten heeft dan om een situatie waarbij de gemeente het geslacht niet kent.
Je wilt niet dat iemand die een geslachtswijziging heeft doorgemaakt van man of vrouw naar onbekend, vervolgens wordt aangeschreven met "Hoogwelgeboren vrouwe" of "Hoogwelgeboren heer".
Besef wel dat het hier gaat om de combinatie van een persoon met een adellijke titel én een onbekend geslacht. Komt wellicht nog niet zo vaak voor. Het is meer beschreven vanuit het principe dat geslachtswijziging voor elke persoon moet leiden tot de juiste aanhef, niet vanuit een poging om bij onbekedwaarden toch een zo goed mogelijke inschatting van het juiste geslacht te bedenken. Dit vanuit het uitgangspunt dat het verkeerde geslacht noemen is erger dan geen geslacht noemen. En een verkeerde titel noemen is erger dan geen titel noemen.

**Comment by fsamwel** [comment]
> Regel 86

Wat als beide partners een adelijke titel/predicaat hebben, heeft dat nog wel invloed op de aanhef? Met name de situaties waarbij beide titels/predicaten van elkaar afwijken. Welke titel/predicaat is dan dominant? Dus stel dat een gravin trouwt met een Baron.

hier is een aparte rule en apart scenario voor gemaakt die beschrijft welke je moet kiezen. Dat is de titel van de partner

**Comment by fsamwel** [comment]
> Je hebt bij aanduidingNaamgebruik ook een versie voor de vrouw maar niet een voor de man. Is dat ook de situatie dat je als man er niet voor kunt kiezen om de Partner naam na de eigen naam te laten vermelden of is dat gewoon een ommissie in de tabel?

Ik weet niet van een regel dat je als man niet de naam van je partner zou mogen gebruiken. Zou ook behoorlijk discriminerend zijn. Is gewoon een keuze geweest om niet alle mogelijke combinaties in de tabel op te nemen.

**Comment by melsk-r** [comment]
> > Waarom wordt bij de andere titels dan Prins, Prinses als het geslacht niet bekend is niet ook een gender neutrale aanhef gebruikt. is dat niet 'Hoogwelgeborene' en 'Hooggeborene'?
> 
> Omdat wij dit soort aanspreekvormen niet zelf verzinnen

Begrijp ik, ik vroeg het me alleen maar af.

**Comment by melsk-r** [comment]
> > Als Prinses is toegekend dan weet je toch ook dat het een vrouw is en als het Prins is dan weet je toch dat het een man is.
> 
> As de titel een geslacht suggereert, maar tóch is de geslachtsaanduiding "O", dan moet je denk ik de geslachtsaanduiding volgen. Bij een persoon, anders misschien dan een pas geboren baby, wordt zover ik kan begrepen heb alleen "O" gevuld voor mensen die bewust aangeven niet als een "man" of "vrouw" aangeduid te willen worden (omdat ze dat niet zijn). het gaat dus vaker om iemand die geen van beide traditionele geslachten heeft dan om een situatie waarbij de gemeente het geslacht niet kent. Je wilt niet dat iemand die een geslachtswijziging heeft doorgemaakt van man of vrouw naar onbekend, vervolgens wordt aangeschreven met "Hoogwelgeboren vrouwe" of "Hoogwelgeboren heer". Besef wel dat het hier gaat om de combinatie van een persoon met een adellijke titel én een onbekend geslacht. Komt wellicht nog niet zo vaak voor. Het is meer beschreven vanuit het principe dat geslachtswijziging voor elke persoon moet leiden tot de juiste aanhef, niet vanuit een poging om bij onbekedwaarden toch een zo goed mogelijke inschatting van het juiste geslacht te bedenken. Dit vanuit het uitgangspunt dat het verkeerde geslacht noemen is erger dan geen geslacht noemen. En een verkeerde titel noemen is erger dan geen titel noemen.

Wellicht ook omdat een geslachtsverandering niet altijd leidt tot het aanpassen van een adellijke titel of predikaat waardoor een persoon die vrouw geworden is nog steeds als adellijke titel 'B' heeft staan?

**Comment by melsk-r** [comment]
> > Je hebt bij aanduidingNaamgebruik ook een versie voor de vrouw maar niet een voor de man. Is dat ook de situatie dat je als man er niet voor kunt kiezen om de Partner naam na de eigen naam te laten vermelden of is dat gewoon een ommissie in de tabel?
> 
> Ik weet niet van een regel dat je als man niet de naam van je partner zou mogen gebruiken. Zou ook behoorlijk discriminerend zijn. Is gewoon een keuze geweest om niet alle mogelijke combinaties in de tabel op te nemen.

Het woordje 'ook' in 'Is dat ook de situatie dat je als man ...' is er per ongeluk in geslopen.
Duidelijk dat je niet alle situaties in de tabel wil opnemen.

**Comment by fsamwel** [comment]
@melsk-r is dit issue nu nog relevant gezien de pull request op aanhef? Is die duidelijk genoeg?

**Comment by melsk-r** [comment]
Hij is in ieder geval op diverse punten verbeterd. Dit issue dwong me echter weer een keer naar het feature te kijken en ik zie daarin nog enkele dingen waarvan ik vermoed dat ze niet correct zijn in aanhef.feature.

Zo zou ik de Rule in regel 17 wijzigen in

>  Rule: De aanhef voor een persoon zonder adellijke titel of predicaat (en evt. partner zonder adellijke titel of predicaat) wordt samengesteld afhankelijk van de geslachtsaanduiding en de waarde van aanduidingNaamgebruik, waarbij geldt dat:

Moet in regel 121 niet het volgende

>     | P           |             | Groenen       |                     | Groenink              | Geachte mevrouw Groenink                |

staan? 
En moet in regel 123 niet juist

>     | V           |             | Groenen       |                     | Groenink              | Geachte mevrouw Groenink-Groenen       |

staan?
Moet regel 211 niet als volgt

>   - Wanneer de persoon de geslachtsnaam van de echtgenoot/partner gebruikt en deze partner heeft geen titel of predikaat zonder de eigen geslachtsnaam: aanduidingNaamgebruik is "P"

beschreven worden? Anders kan hij volgens mij conflicteren met het scenario in regel 899 (voorbeeld regel 930).
En moet om dezelfde reden regel 212 niet als volgt

>   - Wanneer de persoon een predicaat heeft en de geslachtsaanduiding is gelijk aan "V" (vrouw) en betrokkene gebruikt de naam van de (ex)partner (aanduidingNaamgebruik is ongelijk aan "E") en deze (ex)partner heeft geen titel of predikaat

beschreven worden?
