### ISSUE TITLE
wanneer is een ouder een OnbekendOuder?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#940]
Wanneer gebruiken we bij Ouders type OnbekendOuder?

1. wanneer geen enkel gegeven een waarde heeft
2. wanneer alleen ouderAanduiding een waarde heeft
3. wanneer ouderAanduiding, geslachtsaanduiding en/of datumIngangFamilierechtelijkeBetrekking een waarde hebben

Ad 1.
ouderAanduiding heeft per definitie altijd een waarde. Dit kan dus niet voorkomen.

Ad 2.
Volgens HUP wordt bijvoorbeeld bij een vondeling het volgende ingevuld:
- ouder1: geslachtsnaam: ".",  geslachtsaanduiding: "V", datumIngangFamilierechtelijkeBetrekking: geboortedatum
- ouder2: alleen akte en geldigheid

Wanneer alleen ouderAanduiding een waarde heeft (en in de bron ook akte en geldigheid), betekent dit dat het geen ouder is, dit betekent dus iets heel anders dan "OnbekendOuder". 

Ad 3.
Volgens LO en HUP GBA worden bij een volledig onbekende ouder wel geslachtsnaam(=="."),  geslachtsaanduiding en datumIngangFamilierechtelijkeBetrekking gevuld.

Voorstel:
- Als de ouder geen enkele waarde heeft in naam (ook niet "."), dan nemen we de ouder niet op (verantwoordelijkheid: RvIG)
- Als er geen -niet standaard/onbekendwaarde- waarde zit in burgerservicenummer, geboorte of naam, dan is het type "OnbekendOuder" (verantwoordelijkheid: proxy)
- Anders  is het type "Ouder" (verantwoordelijkheid: proxy)

| geslachtsnaam | geslachtsaanduiding | datumIngangFamilierechtelijkeBetrekking | ouder |
|-- |--- |--- |--- |
| waarde | M/V/O | Datum | Ouder |
| waarde | M/V/O | OnbekendDatum | Ouder |
| waarde |   | OnbekendDatum | Ouder |
| . | M/V/O | Datum | OnbekendOuder |
| . | M/V/O | OnbekendDatum | OnbekendOuder |
| . | | Datum | OnbekendOuder |
| . | | OnbekendDatum | OnbekendOuder |
| | | | Geen ouder: niet opnemen |

N.B. dan moeten we velden toevoegen aan OnbekendOuder:
- ouderAanduiding (#937)
- geslachtsaanduiding 
- datumIngangFamilierechtelijkeBetrekking

**Comment by CathyDingemanse** [comment]
Lijkt mij een prima voorstel. Hoe werkt dan: 

- Als er geen -niet standaard/onbekendwaarde- waarde zit in burgerservicenummer, geboorte of naam, dan is het type "OnbekendOuder" (verantwoordelijkheid: proxy) 

precies?

Ik neem aan dat deze zin over de oudergegevens gaat. Als zowel BSN als geboorte als naam geen standaard onbekendwaarde hebben dan is de ouder toch bekend? Ik snap nog niet goed wat hier staat.

**Comment by fsamwel** [comment]
Wanneer een ouder echt bestaat (de condities van tweede en derde Gullit hierboven), dan is minimaal geslachtsnaam en datum familierechtelijke betrekking gevuld, als dan niet met respectievelijk een punt en 00000000.

De proxy filtert de onbekendwaarden uit de RvIG response. Dus geslachtsnaam="." wordt uit het antwoord gefilterd. Wanneer daarna er geen burgerservicenummer, naam of geboorte meer is, dan is het een OnbekendOuder.

In dat geval kan er dus wel een waarde zijn voor geslachtsaanduiding en ook een waarde voor datumIngangFamilierechtelijkeBetrekking

Bijvoorbeeld wanneer alleen geslachtsaanduiding en datumIngangFamilierechtelijkeBetrekking bekend is. De geslachtsnaam is dan in GBA-V een punt):
```
"ouders" [ {
  "type": "OnbekendOuder",
  "geslachtsaanduiding": { "code": "V", "omschrijving": "vrouw" },
  "datumIngangFamilierechtelijkeBetrekking": { "type": "Datum", "datum": "2022-03-11" }
} ]
```

De situatie hierboven speelt bijvoorbeeld bij een vondeling. Er wordt dan een moeder geregistreerd.

Maar als er wel iets identificerends bekend is van de ouder, wordt het type "Ouder". Bijvoorbeeld wanneer alleen de geslachtsnaam bekend is:
```
"ouders" [ {
  "type": "Ouder",
  "geslachtsaanduiding": { "code": "V", "omschrijving": "vrouw" },
  "datumIngangFamilierechtelijkeBetrekking": { "type": "Datum", "datum": "2022-03-11" },
  "naam": { "geslachtsnaam": "Jansen" }
} ]
```

of wanneer alleen het geboortejaar bekend is:
```
"ouders" [ {
  "type": "Ouder",
  "geslachtsaanduiding": { "code": "V", "omschrijving": "vrouw" },
  "datumIngangFamilierechtelijkeBetrekking": { "type": "Datum", "datum": "2022-03-11" },
  "geboorte": { "datum": { "type": "JaarDatum", "jaar": 1956 } }
} ]
```

**Comment by fsamwel** [comment]
ik heb dit inmiddels doorgevoerd in Pull Request #941

**Comment by CathyDingemanse** [comment]
Ok, toch nog even: wat is de toegevoegde waarde van de voorgestelde gegevens 
- geslacht "vrouw" (wat nu overigens niet meer zo hoeft te zijn, ook al heeft hij/zij hen een kind ter wereld gebracht);
- de datum ingang familierechtelijke betrekking bij de vondeling die gelijk is aan de geboortedatum
tov de boolean die er nu staat?

Ik ben er niet van overtuigd dat dit iets toevoegt voor een afnemer.

**Comment by fsamwel** [comment]
We leveren niet deze gegeven. Keuze tussen alleen boolean leveren of de ouder niet leveren.

Keuze hangt af van of bij partner en kind nog wel de onbekend versie voor kan komen. Dan voor consistentie ook bij ouder een OnbekendOuder houden. Anders de onbekend ouder niet leveren.

**Comment by fsamwel** [comment]
@CathyDingemanse en hoe gaan we hiermee om bij een partner? Wanneer geslachtsnaam van de partner is onbekend, maar er is wel een aangaanHuwelijkPartnerschap (datum)? Leveren we dan ook alleen OnbekendPartner met de boolean en zonder aangaanHuwelijkPartnerschap? Dan is niet meer zichtbaar sinds wanneer de persoon deze (onbekende) partner heeft.

**Comment by fsamwel** [comment]
voor ouders, partners en kinderen is het onderscheid tussen bekend en onbekend niet functioneel relevant. We weten daarom niet goed wat een onbekende ouder/partner/kind is.

Wel is het belangrijk dat een gebruiker kan bepalen of er bijvoorbeeld een partner is, zonder alle gegevens van de partner op te hoeven vragen (data-minimalisatie). Daarvoor is veld type wel nuttig.

Of er een partner is, wordt bepaald uit dat er ten minste één veld gevuld is met een waarde (ook standaardwaarde) van 02 naam of 06.10 datum sluiting/aangaan en 15.10 soort verbintenis, dus alleen gegevens binnen Gaba autorisatie.

- [ ] Verwijderen onbekend types voor ouders, partners en kinderen uit specificaties
- [ ] Aanpassen van features voor ouders, partners en kinderen
- [ ] check andere features
- [ ] aanpassen mapping

**Comment by JohanBoer** [comment]
> Wel is het belangrijk dat een gebruiker kan bepalen of er bijvoorbeeld een partner is, zonder alle gegevens van de partner op te hoeven vragen (data-minimalisatie). Daarvoor is veld type wel nuttig.

Ik ben wel benieuwd hoe ik dit in de specificatie moet implementeren. Als het Onbekend type voor ouder, kind en partner moet verwijderen is hier geen sparake meer van polymorfie. Het veld type is dan ook niet meer nodig. Wat zet ik dan in het type op het moment dat ik alleen wil weten of er een kind / ouder / partner is zonder de gegevens op te willen vragen ? 
Volgens mij zou dan een boolean met als propertynaam bv. "kindAanwezig" of iets dergelijks beter op zijn plaats zijn dan een property type.

**Comment by fsamwel** [comment]
> Als het Onbekend type voor ouder, kind en partner moet verwijderen is hier geen sparake meer van polymorfie. Het veld type is dan ook niet meer nodig.

Volgens mij hebben we afgesproken dat we wel polymorfisme houden, maar dan met mapping naar maar één type. Dus het veld type blijft juist om die reden wel behouden.

**Comment by JohanBoer** [comment]
> Volgens mij hebben we afgesproken dat we wel polymorfisme houden, maar dan met mapping naar maar één type. Dus het veld type blijft juist om die reden wel behouden.

Ik werk het uit conform deze afspraak.
Dan gaan we er van uit dat je een ander type in het veld type kan opnemen dan in de mapping is weergegeven. Ik vind het ook geen logische keuze. Wat voegt polymorfisme hier nu nog toe ?

**Comment by fsamwel** [comment]
> Dan gaan we er van uit dat je een ander type in het veld type kan opnemen dan in de mapping is weergegeven. Ik vind het ook geen logische keuze. Wat voegt polymorfisme hier nu nog toe ?

Wat het toevoegt is dat het hierdoor mogelijk wordt om te zien dat er een ouder/partner/kind is, ook wanneer geen gevraagd gegeven van die relatie een waarde heeft. Je krijgt dan de relatie met alleen veld type met een waarde.
Je kan dan ook bijvoorbeeld het aantal kinderen opvragen met fields=kinderen.type.
