### ISSUE TITLE
'InOnderzoek' component in common.yaml onderbrengen.

### ISSUE THREAD

**Issue by melsk-r** [BRP-API/Haal-Centraal-BRP-bevragen#948]
Het '[InOnderzoek](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/b563db211904d026bea3543c1d4e80037b01fdca/specificatie/persoon.yaml#L194)' in 'persoon.yaml' is n.m.m. meer op zijn plaats in de 'common.yaml'.

Het is niet specifiek van toepassing op Persoon en er wordt ook in diverse yaml schema's naar verwezen.

**Comment by fsamwel** [comment]
de manier waarop we inOnderzoek leveren is tot nu niet generiek voor meerdere domeinen. In BAG leveren we dat in de vorm mogelijkOnjuist. In BRK en WOZ kennen we geen inOnderzoek. Dus zolang inOnderzoek alleen nog in BRP gebruikt wordt, zou ik het ook daar definiëren

**Comment by melsk-r** [comment]
Met 'common.yaml' doelde ik niet op het bestand met deze naam in 'Haal-Centraal-common' maar in het bestand met deze naam in 'Haal-Centraal-BRP-bevragen' zoals dat door @MelvLee is geïntroduceerd in de feature/2.0.0 branch.

**Comment by melsk-r** [comment]
Dit gaan we doorvoeren als er geen PR's meer openstaan, dus vlak voordat we de 2.0 versie gaan publiceren.
