### ISSUE TITLE
feature maken voor autorisatie i.c.m. fields

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#960]
we moeten m.i. een duidelijke uitspraak doen (in dit feature of een apart feature autorisatie) over wat moet gebeuren wanneer gevraagd wordt om een gegeven waarvoor men niet geautoriseerd is.

foutmelding niet geautoriseerd
antwoord leveren zonder niet-geautoriseerde gevraagde gegeven

**Comment by fsamwel** [comment]
zie keuze hiervoor in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/852#issuecomment-982886352

**Comment by fsamwel** [comment]
@MelvLee @JohanBoer @melsk-r ik heb aanzet voor autorisatiefeature gemaakt. Althans alleen de rules en scenario-namen, plus een aanduiding voor te gebruiken gegevens. De automatisering hiervan bestaat denk ik nog niet, hierbij zijn er verschillende gebruikers nodig met per scenario te maken autorisaties. En per gebruiker soms gemeentecode in de Oauth token.

Kunnen jullie helpen deze feature de (m.n. Gegeven en Als stappen uit te werken en bijbehorende automatisering te maken? Ik heb bij het eerste scenario een aanzet daarvoor gemaakt. Is die werkbaar of moet dat anders beschreven worden?

De feature staat hier: https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/autorisatie/features/autorisatie.feature

**Comment by fsamwel** [comment]
afgesproken dat Melvin automatisering uitwerkt en template voor de feature bewerkt

**Comment by MelvLee** [comment]
@fsamwel, voorbeeld scenario is toegevoegd.

**Comment by melsk-r** [comment]
Hoe moet ik beide uitgewerkte scenario's in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/autorisatie/features/autorisatie.feature interpreteren.

Volgens mij zijn het dezelfde scenario's alleen in een wat andere vorm.

Als dat zo is dan vind ik de eerste het duidelijks. De Gegeven steps die in de tweede zijn toegevoegd voor het definiëren zijn volgens mij niet van belang voor dit scenario, aan het uitlezen van deze ingebrachte waarden komt de API als het goed is toch al niet toe. Mocht dat toch gewenst zijn, voeg dan 
```
      En de persoon met burgerservicenummer '000000024' heeft de volgende 'verblijfplaats' gegevens
      | gemeente van inschrijving (09.10) |
      | 0599                              |
       En de 'verblijfplaats' heeft de volgende 'adres' gegevens
      | gemeente_code | identificatiecode nummeraanduiding (11.90) |
      | 0599          | 0599200000219679                           |
```
toe aan het eerste scenario.
