### ISSUE TITLE
Als PO wil ik weten welke meet- en loggingstandaarden door API Gateways worden gebruikt

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#987]
...zodat de logging van de proxy hierop kan aansluiten c.q. in dit ecosysteem past

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
voorstel: volgen https://opentelemetry.io
